### ISSUE TITLE
Bounty to translate Bisq software into Japanese

### ISSUE THREAD

**Issue by y3v63n** [bisq-network/proposals#104]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Following discussions with @arunasurya and @ripcurlx as well as [input](https://github.com/bisq-network/growth/issues/141) from other community members, I would like to propose a bounty to translate the Bisq software into Japanese.

### Rationale:

 - Recently, the bisq's new JPY order book has been [launched](https://github.com/bisq-network/growth/issues/140).
 - Though the current volumes are low, it was [pointed out](https://github.com/bisq-network/growth/issues/150#issuecomment-513795242) that the potential of Japan as a market for Bisq could be significant.
 - It was also [noted](https://github.com/bisq-network/growth/issues/141#issuecomment-508505028) that the language barrier could constrain user adoption in Japan.
 - The latter point could be supported by the fact that in the [English Profficiency Index](https://www.ef.co.th/__/~/media/centralefcom/epi/downloads/full-reports/v8/ef-epi-2018-english.pdf), Japan holds 49th position with Low Proficiency.
 - There's little info about impact of software localization with specific figures due to sensitivity of this information, however my personal experience in localization and some [other sources](https://www.reddit.com/r/gamedev/comments/4d7umm/we_sold_25000_copies_on_steam_in_12_languages/) suggest that Japanese translation pays off well.

### Budget:
- Translation: 15,589 untranslated words at 0.07 BSQ/w = 1,091.23 BSQ
- Review: 16,564 words at 0.035 BSQ/w = 579.74 BSQ
- Total: 1670,97 BSQ

It might seem pricey, but bear in mind that we apply our standard rates for all languages, which are on the lower end of the [average rates](https://search.proz.com/employers/rates) charged by freelance translators. Morevover, Japanese is one of the most expensive languages to translate to, so I believe that the proposed budget is very realistic for the organization and at the same time appealing to participants.

**UPD (26 Jul):** This one is still pending and needs to be formally approved first, but since @jmaurice and @tdhr0917 already started working on it, I'm attaching all the instructions here.

### Tasks:
- Translate the Bisq software here: https://www.transifex.com/bisq/bisq-desktop/language/ja/
- Populate [Glossary](https://www.transifex.com/bisq/bisq-desktop/glossary/ja/?page=1) with correct Japanese terminology.
- Check the translation in the app to make sure there are no visual or functional issues.

### References
Please familarize yourself with [Bisq Translation Documentation](https://github.com/arunasurya/bisqtransifex) to learn how to submit and report your work, submit compensation requests and leave queries, etc.

### Deadline
30 days from the start.

**Comment by MwithM** [comment]
I was against this proposal at first, when I heard it on growth call, because of low volume in JPY. But JPY is still the third national currency in trading volume, so Bisq needs volume in this currency. I think that sooner or later we will need this, so the sooner we start, the better.
I didn't know that Japan speaks less English than Spain, that was a surprise for me.

**Comment by jmaurice** [comment]
Yes, the language barrier has been the biggest obstacle on-boarding new users to Bisq in Japan, as nobody really speaks English except foreigners or internationalized Japanese people. Since non-English speakers are afraid they might make a mistake and lose funds, they are too scared to try it. Currently the order book is entirely made up of a few foreigners who are the members of the Tokyo Bitcoin community, and we really need Japanese translations to get Bisq adoption in Japan. Thank you for this!

**Comment by flix1** [comment]
Excellent idea. Very much looking forward to seeing this translation made.

**Comment by jmaurice** [comment]
Since @tdhr previously did the Japanese translation for BTCPay using Transifex, he is the perfect person for this task. I just met with him and we signed up for the Bisq project on Transifex. We will begin working on this right away, so if you want to set us as the reviewers for the Japanese language that would be great. Thanks!

**Comment by jmaurice** [comment]
Since @tdhr0917 previously did the Japanese translation for BTCPay using Transifex, he is the perfect person for this task. I just met with him and we signed up for the Bisq project on Transifex. We will begin working on this right away, so if you want to set us as the reviewers for the Japanese language that would be great. Thanks!

**Comment by jmaurice** [comment]
FYI we managed to get 80% done with translations, so we submitted a PR today in the hopes of getting merged for the next release https://github.com/bisq-network/bisq/pull/3022

**Comment by y3v63n** [comment]
@jmaurice Nice! Can't wait to see users' reaction in Japan

**Comment by y3v63n** [comment]
@mpolavieja yep, closing it as approved
