### ISSUE TITLE
Bond for GitHub admin

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/proposals#108]
To lock up my bond for the [GitHub admin role](https://github.com/bisq-network/roles/issues/16).

**Comment by mpolavieja** [comment]
Hello, does this issue belong here or should it be posted at https://github.com/bisq-network/roles/?

Is this issue here in order to be linked from the DAO proposal list?  If so, I feel there is a confusion between a proposal as described here https://docs.bisq.network/proposals.html and a DAO proposal.

**Comment by chimp1984** [comment]
See https://github.com/bisq-network/proposals/issues/112#issuecomment-529192113

Bonded roles require a proposal here. After accepted and bonded they should be added by the maintainer to roles.

**Comment by mpolavieja** [comment]
Accepted on DAO voting
