### ISSUE TITLE
Develop a network of Bisq merchants by adding conditional orders

### ISSUE THREAD

**Issue by acrual** [bisq-network/proposals#123]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

# Developing a network of merchants for Bisq
(thx @manuelpolavieja for your extremely valuable input)

**Introduction**

I’m quite recent to Bisq and if I’m getting it right, **Bisq becomes useful by combining security, safety and privacy in a decentralized platform**. This holds true from the “crypto” side of things, but from a fiat point of view, there might be ways in which your fiat transfers may not be that anonymous, like for example a bank could question why you, based in France, are getting weekly transfers coming from a wide variety of European Countries, or a fake user could at some point agree on exchanging with you risking your privacy as a result.

On the other hand, bisq allows for face to face cash exchanges that are definitely private, but depending on the situation it could become a security concern.

So we can conclude that it would be ideal to find a way in which we can increase privacy but not at the expense of security and viceversa, basically minimizing these trade-offs.

This proposal intends to increase the ability of users to buy in a private, anonymous and secure way using cash from whatever fiat currency they want to get rid of.

**The idea**

Several Companies have created a network of stores (vendors) with which they typically sign a contract, and allow final users to buy vouchers in those stores for a maximum amount of fiat, that can be redeemable online for an amount of bitcoins, depending on the exchange rate. Bit2me / Tikebit and azte.co come to mind. These services claim not having KYC requirements afaik.

The idea is to allow these kind of merchants to, in a permissionless way, participate as intermediaries in the Bisq exchange, facilitating users who want to buy in cash in their stores anonymously, and securely. 

Also, the fiat transactions from stores typically have way higher volume, so small transactions like the ones happening at bisq are somewhat diluted in a higher number of them, therefore way more private that if made by a private individual.

With conditional orders, we can make this proposition a very attractive one for merchants, as trading operations would be either very profitable, or wouldn't happen at all, and given that the demand for privacy and security is likely very high the chances of achieving the former could be pretty high.

There are three stages in how this idea could be implemented, and they are all perfectly compatible in parallel:

## 1- The 1st would require minimum changes to the code

In this stage, we can promote Bisq among stores, but given that there are no conditional orders yet, this option would only suit those stores willing to assume some market risk. There are probably not a large percentage that could find it a viable option, but there are tons of small stores where the owner has plenty of time to carry out a trading activity. It is probably not negligible in worldwide terms.

It would require a minimum addition of one more payment method that we could name something like “Face to face cash-to-merchant payment in City X”. Users would be likely happy to buy with an excess 5% margin (for example), as long as they can do it anonymously and securely in cash in a store next to them.

During this stage, a cost efficient way of reaching stores would be to create online marketing material possibly including some sort of video.

## 2- The 2nd requires some changes to the code:

The largest part of the market doesn’t want to face market risk, so there is a problem: Merchants participating would suffer the risk that if the price goes down, its selling order would not be executed.

A potential solution to this is to create conditional orders, that is a selling order that would only be enabled, if there are buying orders too that allow them to earn a minimum margin. I believe that the demand for private and secure payments is high enough to justify such development

Everyone would win because:

On one hand, stores would be adding liquidity to the network acting as “market makers” especially in countries where Bisq is still small.

- Stores would be doing a small business with high margins and small cost in terms of time.
- Stores activity is likely to remain way more private than that from a person, since the transfers are diluted within a way higher number of fiat transfers
- Stores could attract new visitors and if they are selling bitcoin related products, it could be an interesting value proposition.
- Demand of an increase in anonymity would be satisfied for private users.
- Lower the barriers of entry to Bisq for users, so it is easy to get your first amount of BTC needed for security deposits or to buy BSQ
- Stores can start this activity in a permissionless way, without contracts, without minimum amounts, without any kind of commitments unlike the case of bit2me or azte.co. If they try it and they believe it can be a good business, they can increase their time dedicated to this activity. If they think it is not such a good idea, they can stop it with immediate effect. No sunk costs as a result.

## 3- The 3rd one would require some more changes to the future code of the off-chain protocol (see #118).

The aforementioned option 2, has three main inconveniences:

a)- In this model, stores are obliged to custody bitcoins. This can be a big friction if the store wants to carry out this kind of operations.
b)- It can also be a concern in terms of security
c)- Bitcoins have to be transacted twice, once from the seller to the merchant, and then from the merchant to the buyer.

So my suggestion to overcome this situation is to allow conditional orders where the trades would happen as follows:

1. A store owner opens bisq and creates a conditional order selling 0,25btc for $2500. The condition to publish it is that there is another selling offer for $2500 (100%-(acceptablefee)%). (let's assume that the acceptable fee for this store is 5%)
2. If the condition is met, the trade happens in the following way: 1st, Bisq blocks the amount of bitcoin from the seller from their bond. 2nd, the store sends the exchange in fiat to that seller ($2375), in a fiat transfer (“hidden” among a large number of other fiat transactions).
3. Automagically, once the seller acknowledges receipt of the fiat transfer, Bisq publishes an equivalent the selling offer coming from the store, for those $2500.
4. The buyer whose offer was automagically accepted sees the store precise address, and has 24 hours to show up at the store and pay in cash those $2500.
5. The store asks the buyer for a bitcoin address or an opendime device and fills in a form in bisq that demands it as part of the trade process.
6. Once the address is filled in, bisq unlocks the bitcoins from the seller and transfers them instantly to the buyers bitcoin address.
7. The buyer receives them and is happy because he has bought them without anyone knowing who he is for $2500.
8. The merchant is happy because he has earned $125 in an operation requiring very little work.
9. The seller has been happy for 3 days longer than the other two participants in the trade selling his btc for $2375.

**Other advantages of adding conditional orders**

Of course the present proposal is just one of the many advantages that adding conditional orders could have, although I believe this would be one of the most attractive ones.

In reality, Bisq would benefit any user willing to arbitrate between two different payment methods. Merchants are the ones that in my opinion can offer the most attractive payment method in terms of privacy and security, but there are likely many more such cases.

**Opendime**

An interesting idea is that from @manuelpolavieja which is to allow merchants to directly deliver opendimes to their customers. To those not familiar with this product, an opendime behaves as actual cash, as a bear instrument, loaded with whichever amount of bitcoins you want to. It is extremely easy to verify that it has the amount of bitcoins it should, and if someone has messed with it, it is tamper evident, so you are sure nobody knows the private keys.

So a scenario is that the merchant would sell the opendime filled in with the bitcoins of the seller, and the buyer could verify with his own laptop (other more inexpensive devices allow this) that the bitcoins are there. Once verified he could just walk away safely with his opendime.

**Needed efforts to make this happen**

For the 1st option, there is my opinion very little we can do, as it is nearly impossible to identify which stores will be willing to assume market risk. But a good marketing campaign could be a cost-effective option.

For the 2nd and 3rd options, once ready, we could ideally add to the internet campaign some B2B sales activity, like speaking with retail store associations, open/marketing events or even retail trade fairs where it can be explained, etc… Maybe creating stickers that these stores could put in their entrance doors. 

Also, for large chains of stores, we can visit innovation managers at these Companies, and see if there can be any interest in including this service in its portfolio. It's definitely also a sales B2B job too.

Sales Offers from stores should show up in the order book with an ID such as “In a store near you” or “Face to face cash exchange” “Merchant f2f (Madrid)” indicating the city where the store is located.

**Potential competition**

Bisq will compete in this front with the likes of FastBitcoins, Azte.co, tiketbit.com and a few more. All of them have in common that they claim KYC is not needed but they have a certain limit amount of fiat to be exchanged, and their geographical coverage is limited to a particular number of stores and jurisdictions.

I think Bisq could be a bit more convenient for the final buyer than these competing solutions, but where it is way better is in how much more convenient it is for merchants, compared to those companies’ vendors. precisely the part where these companies are struggling to grow.

Bisq won’t require any minimum commitment, nor contracts nor the like, it will be free adhesion to the service whenever the merchant wants, and in whatever amount it believes to be appropriate.

With Bisq the final buyer leaves the store with his Bitcoin. With solutions like TikeBit or Azte.co the final buyers leaves with a voucher from the store, so it is a two-step process. That two-step process also requires trust on the entity that issues the vouchers to later redeem them for Bitcoin
¿Would it make sense that the merchant dumps Bisq once he has a customer base, that is, using a centralized exchange?

Staying in Bisq is more secure (not your keys not your coins) and would relieve him from custody pains. Staying in Bisq also allows the Merchant to plan in advance, meaning that you will know when a buyer is going to enter your store willing to buy bitcoin and have the process fully automated (in the case of the second option). Also, in developing countries having access to a KYC centralized exchange might not be easy.

And finally, he wouldn’t save miner fees by having just one transaction. He would have coinbase’s fees, and then those from sending the bitcoins to the final buyer.

Some research is still needed in order to find out whether these competitors do actually allow bitcoin purchases without the need of KYC as they claim, but even if that is the case, they seem to have several limitations compared to Bisq.

**Challenges**

In a world full of noise with short attention spans B2B sales are getting more and more complicated.

But I think this is the typical product/service that will gain a lot of traction once we reach a FOMO stage and there will be huge network effects once people demand easy/fast/secure/private access to bitcoin. Things that are in favor of Bisq's adoption from the merchant point of view are the fact that there is negligible economic and mental cost to adopting it. It is as simple as downloading the app in an existing computer.

We could even consider the possibility of doing tests with several stand-alone computers and check which one is able to run Bisq at the lowest cost as a solution for those merchants without computers.

**Conclusion**

Adding conditional orders could open for Bisq a massive marketplace that could increase liquidity, usage and fees and more importantly, easyness, privacy and security for bitcoin acquisition which after all would be a great help for bitcoin's adoption.

Large easily traceble chains of stores in Western Countries, with streamlined operations, are very unlikely to adopt Bisq, but a vast majority of small stores with a single owner in Western Countries and almost every second store in emerging countries could become a potential adopter of a merchant role with virtually zero risk from the regulatory point of view.

**Comment by mpolavieja** [comment]
Great idea @acrual!!    I think this could be very interesting for merchants in developing countries where bitcoin exchanges are not easily accesible.

> In reality, Bisq would benefit any user willing to arbitrate between two different payment methods.

This is very interesting as it would significantly enhance liquidity / fungibility of payment methods within Bisq order books.  This could easily be done by any user with 2 or more payment methods.

**Comment by MwithM** [comment]
I'm somehow still surprised how underused is F2F in Bisq, so seeing a proposal to encourage people to use this payment method is very good news.

The main concern I have is that stores will be sooner or later required by local agencies to ask for KYC/AML. Keeping the offers in a private way is better vs a business level, specially considering the privacy level you can achieve with this payment method.
In the case of tikebit and bitnovo, you can buy a paper in a store without identification. But when you try to exchange this paper for bitcoins, you have to go to a plattform (bit2me, bitnovo) where [limits and corresponding KYC is applied](https://bit2me.com/preguntas-frecuentes).

My preffered protocol is the first one, although maybe is because I don't understand completely the other 2 new.
Now we can just use a % from bitcoinaverage price and remove or not display the offer if the price is too low. Creating a sell order order that would automatically become unavailable if the price goes below certain level makes sense and that would be a great option for all traders.
In the third option as I understand it, I see like there's too many parts in action where ideally there should be only two: the buyer and the seller, instead of the store, the buyer and the seller, and then also Bisq. To me, a store that wants to sell or buy bitcoins need to have those bitcoins or fiat, otherwise it gets too complex. Some inconveniences will appear, creating difficulty for mediation and also delays to the process.
An offer saying "Joe's Bar tue-sun 10:00 23:00h" allows you to accept the offer and go there the same day, and that's an advantage. Waiting another trade to be completed before the buyer gets the bitcoins doesn't make much sense to me. If buyer doesn't show up at the store, does the store have any right to return the btc to seller? I know bonds would make this situation improbable, but I want to make the point that a contract between two parts and a mediator is easier to manage than a contract between three parts and a mediator.

The Opendime option looks great, if 2of2 multisig option becomes available. Bisq can't know if the Opendime was exchanged for cash or not. Arbitrarion looks impossible, so Mutual Assured Destruction protocol is the best for these kind of trades.

**Comment by acrual** [comment]
Thanks for your feedback first of all :)

> The main concern I have is that stores will be sooner or later required by local agencies to ask for KYC/AML. Keeping the offers in a private way is better vs a business level, specially considering the privacy level you can achieve with this payment method.

Yes, but bear in mind that two things happen: 

- In the case of small stores I believe it is close to unenforceable preventing a store owner from running a piece of software in his PC and 
- Secondly, this could only be (close to) problematic in Western countries where the taxman has nothing better to do than bothering entrepreneurs. In developing countries this shouldn't be an issue.

> An offer saying "Joe's Bar tue-sun 10:00 23:00h" allows you to accept the offer and go there the same day, and that's an advantage. Waiting another trade to be completed before the buyer gets the bitcoins doesn't make much sense to me. If buyer doesn't show up at the store, does the store have any right to return the btc to seller? I know bonds would make this situation improbable, but I want to make the point that a contract between two parts and a mediator is easier to manage than a contract between three parts and a mediator.

With regards to the offer you mention, it would never be available publicly if the conditional order is enabled, because in order to show up, the buying part of the trade should happen as well. 

So summarizing, if I'm a store owner my selling order would be something like "Joe's Bar tue-sun 10-23 0,25btc for $2500" but it would never show up in the order book if a buying order to "John Smith" hasn't happened automatically, paying the store to John Smith for example $2375 for those 0,25btc. That's why implementing a conditional order is critical to make this happen.
> 
> The Opendime option looks great, if 2of2 multisig option becomes available. Bisq can't know if the Opendime was exchanged for cash or not. Arbitrarion looks impossible, so Mutual Assured Destruction protocol is the best for these kind of trades.

But with opendime the buyer just needs to get it and quickly check that the balance in the opendime's bitcoin address is right, and walk away with his opendime with its bitcoins.

**Comment by mpolavieja** [comment]
> Creating a sell order order that would automatically become unavailable if the price goes below certain level makes sense and that would be a great option for all traders.

Yes. As I understood it, the sell order would be automatically disabled if there is not available another sell order from another Bisq user with the merchant´s preferred payment method (I´ll call it the **hedge order**) at a price below a specific %.   This would be the conditional order, it would automatically enable / disable if the condition is met / not met.

But another thing would be needed, if the merchant's f2f order is taken, the merchant would need to **automatically** trigger a buy order in order to immediately take the  hedge order, so he locks his fee ( 4% or whatever distance he set his order to the hedge order).  This is generally known as an **OSO order** (Order Sends Order).

The above could be applied for any Bisq participant who is willing to arbitrate two different payment methods (i.e. Revolut vs. SEPA, HalCash vs. Revolut, etc)

N.B. The f2f merchant´s order could also be hedged outside Bisq in a liquid centralized exchange such as Kraken or Coinbase, but for that a bridge would need to be developed between Bisq's API and the centralized exchange's API would (also to open an account on the centralized exchange and exposure to custody risk), so it would be a lot more complex for the user.  Not a turnkey solution.

**Comment by acrual** [comment]
> @MwithM
> 
> > Creating a sell order order that would automatically become unavailable if the price goes below certain level makes sense and that would be a great option for all traders.
> 
> Yes. As I understood it, the sell order would be automatically disabled if there is not available another sell order from another Bisq user with the merchant´s preferred payment method (I´ll call it the **hedge order**) at a price below a specific %. This would be the conditional order, it would automatically enable / disable if the condition is met / not met.
> 
> But another thing would be needed, if the merchant's f2f order is taken, the merchant would need to **automatically** trigger a buy order in order to immediately take the hedge order, so he locks his fee ( 4% or whatever distance he set his order from the hedge order). This is generally known as an **OSO order** (Order Sends Order).
> 
> The above could be applied for any Bisq participant who is willing to arbitrate two different payment methods (i.e. Revolut vs. SEPA, HalCash vs. Revolut, etc)
> 
> N.B. The f2f merchant´s order could also be hedged outside Bisq in a liquid centralized exchange such as Kraken or Coinbase, but for that a bridge would need to be developed between Bisq's API and the centralized exchange's API (also to open an account on the centralized exchange and exposure to custody risk), so it would be a lot more complex for the user. Not a turnkey solution.

Exactly, at the end of the day what we are talking about is that merchants are in a privileged position to arbitrage any available payment methods, given that the one they can offer is the most attractive in terms of security, privacy etc...

**Comment by MwithM** [comment]
After taking a look to Bisq v2 and the new trading protocol where there's only bonded BSQ instead of BTC multisig deposits, I think that the conditional orders for merchants could be easy to implement.

### OFFER CREATION

There's 3 agents involved in this trade: seller, buyer and store.
Store creates conditional offer to sell 0.1btc that will be displayed only if there's a selling offer for bank transfer of 0.1btc.
Seller creates and offer to sell 0.1btc at $1.000 via bank transfer. Store displays a conditional offer to sell 0.1 btc at $1.030 (3% premium).
Buyer accepts store's conditional offer at $1.030.

### BONDING

Store and seller needs to lock 125% of the trading amount in BSQ bonds, equal to 1.287.5$.
Buyer locks 50% of the trading amount, $515.

### PAYMENTS

As cash payments are very hard to verify, buyer needs to be the first to pay, at store. When the $10.300 payment is made, buyer needs to be sure that store clicks "payment received" button, that will trigger an alert to buyer's Bisq app. Buyer can now walk home to wait for BTC payment, which will be sent to an address communicated via Bisq chat to seller, or to Bisq client when accepting the sell offer.
Seller will be alerted too that the F2F payment has been made. At this moment, seller can make 0.1 BTC payment to buyer. Due to bonding, there's no need to wait to receive store's bank transfer of $10.000.
Store will make the $10.000 bank transfer to seller ASAP.
Only these info needs to be shared:
- Buyer's BTC address to seller.
- Seller and store bank transfer details between each other.

### TIME LIMITS

Buyer will have 2 labour days to pay at store. When the "Payment Received" button is clicked, a new timecount will be started, giving 5 days for the bank transfer to arrive to seller. Different time limits should be used for different payment mehtods. Seller will have 48 hours to make BTC payment. Seller and buyer need to confirm payment received with their Bisq client.

### WHAT IF (MEDIATION)

Buyer doesn't go to store: lose BSQ bond, equalling $515. Store and seller doesn't have to send any payment, as the trade is cancelled. Both should be compensated.
Seller doesn't pay 0.1 BTC to buyer: seller lose BSQ bond, equalling $1287.5. Buyer should be compensated.
Store doesn't pay $1.000 bank transfer to seller: store lose BSQ bond, equalling $1287.5. Seller should be compensated.

BTC and bank transfer payments are easy to verify, and chargebacks are being prevented. Weak point is cash payment. As in the current F2F protocol, if Bisq doesn't have clear reasons to act in a certain way in case of dispute (like police reports and judge statements), store and buyer could lose their bonds. Store needs to verify that there's no counterfeit bills and buyer needs to know that the "payment received" button has been clicked. This method have some advantages compared to a F2F public place meeting: store usually has already computers to run a Bisq node, own security measures, and is very used to receive cash payments. Millions of cash payments are made every day and counterfeit bills are still rare, and going to the baker, paying your cents and not receiving your bread is even stranger. Stores usually need reputation and that runs to our favour.
Store doesn't have to keep BTC anywhere, buyer doesn't have to bring btc or laptop, so this prevents from robbery. Online smartphones are very common for most of the countries. For those who don't, a Bisq certificate could be printed at the store as a receipt, but I don't know a cryptographic way to prevent this paper from being falsified.

**Comment by mpolavieja** [comment]
Closed as stalled
