### ISSUE TITLE
Fix The Broken Dispute Resolution System

### ISSUE THREAD

**Issue by clearwater-trust** [bisq-network/proposals#129]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

The current Mediator/Arbitrator system of dispute resolution is broken.

1. It invites and encourages coinlocking
2. It discourages market makers
3. It takes TOO LONG

Security should be the number one priority. Holding funds in escrow for a prolonged period of time IS NOT secure, efficient, safe, smart, viable, tenable.

How to fix the system:

Efficiency is safety.
DO NOT keep funds locked in escrow for longer than necessary. Once the mediator has provided input it should be immediately ruled on by an arbitrator. 5+ days is NOT going to work and makes BIsq completely useless for fiat trading. **A market maker is not going to create more offers while they wait 5-10-15 days to resolve a dispute that should take seconds for an arbitrator to rule on. (ie. UNRESPONSIVE TRADING PEER)** 

Train the mediators and arbitrators.
I don't know what is going on behind the Bisq curtain. It's not clear what the mediators/arbitrators are being told. If there was a recent failure in the system, (arbitrator releasing to the wrong trader) It is VERY LIKELY a training issue NOT a systemic failure that can be resolved with clever coding.

If we get this part wrong, none of the other proposals matter. 

The operating cost of an efficient exchange INCLUDES HUMANS that review broken trades. Humans cannot be coded out of a fiat system. If Bisq wants to be a fiat on-ramp we need to price in the cost of QUALITY DISPUTE RESOLUTION.

**Comment by chimp1984** [comment]
With the release next week of v1.2.0 we introduce the new trade protocol. So I don't see much reason to discuss the current transitionaly state in a proposal. Also currently there is a bug so that one mediator gets all cases and as he was travelling his availibility was not as usual.

With v1.2.0 arbitration have to become an exceptional situation as arbitrators take quite a bit of risk by pre-funding the BSQ reimbursement (volatility risk). Payout and loss of security deposit can be defined by arbitrator. So I don't see much risk that users try to game the rules as they would risk to lose their deposit. If we find out that we get too many "not responding" cases with sellers we can increase the security deposit. The buyer deposit can be increased anyway by the maker. 

Currently there are too many bugs still but after 1.2.0. we need to put some priority on fixing those bugs and ensureing the p2p network is stable enough to not cause problems with "missed messages".

> 5-10-15 days to resolve a dispute that should take seconds for an arbitrator to rule on. (ie. UNRESPONSIVE TRADING PEER

Currently there are still too many issues with p2p network or bugs that a not responding peer does not mean he is not responding but can be that he did not received the message. Once that is fixed we can enforce the max. 2 days respond time again harder.  

Any centralized exchange takes ages once you need customer support. Waiting 1-2 weeks to get anything resolved it standard there. I think the speed of Bisq arbitration is in average much better as at those platforms. But beside that, if we go too extreme there is always the risk to punish users for honest mistakes (newbies, issue at traveling,...). To get punished for honest mistakes is usually a very negative experience and leads easily to users never returning to Bisq and bad reputation.

> It is VERY LIKELY a training issue NOT a systemic failure that can be resolved with clever coding.

Human mistakes cannot be avoided. It happened to all arbitrators in the past some times. Luckily most traders have been honest to return the funds. No amount of extra warning popups would help here.

As I don't consider that proposals as fulfilling the proposal standards (https://docs.bisq.network/proposals.html) I recommend to close that and continue the discussion elsewhere (Forum, Slack).

**Comment by mpolavieja** [comment]
@clearwater-trust what you are proposing is to rollback to the 2-3 multisig protocol which was recently deprecated and the community approved by the Bisq community to be changed to 2 of 2 multisig.  

Having this discussion at this moment is either too late (the decission is already made) or too early (we have not enough feedback yet about the result).

**Comment by doitsu232** [comment]
i encountered some issues myself doing honest newbie mistakes and lost money due to arbitrator decisions. just recently i accidentally offered more BSQ for sale than i had in my wallet and couldn't deliver in time. despite my explanation instead of helping the issue all involved parties decided i have to lose my risk deposit to the seller. very uncool. trading is really not interesting that way for beginners if you get punished so hard.
