### ISSUE TITLE
Allow unsafe payment methods if buyer locked up a BSQ bond

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/proposals#131]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

## Overview
It seems that banks become more hostile over time with P2P payments in general. To have still enough payment options in case that becomes more problematic we could try to enable payment methods which are designed for P2P payments like Paypal or CashApp. The high chargeback risk of those payment methods could be mitigated if the buyer (the one who could do the chargeback) has locked up a considerable BSQ bond.

This would be a kind of "light version" of the idea for a [off-chain trade protocol](https://github.com/bisq-network/proposals/issues/118) (OCTP) where the security is backed by BSQ bonds. In such a "light version" we could leave it to the traders to analye the risk (amount of locked up BSQ, open offers of same user,...) and we could ignore the challenge how to track parallel trades and keep that as a know imperfection for a first "test".

This is just a rough idea and would require more analysis and detail work to find out if it makes sense. In the best case it might be a roadmap for incrementally introduce the OCTP by adding features and migrating the existing trade protocol to the OCTP. For instance as next step we could remove the MultiSig deposit tx for such trades. But as said, this is a very rough idea and would require more work....

**Comment by sqrrm** [comment]
My main worry with such an approach would be the support issues due to traders not understanding the protocol and perhaps scammers trying to use it for scamming if it's more complicated to understand and use. I like the idea of a light version to see if it could work at all though, and it would be a lot easier to implement than anything like the full version OCTP that we have discussed elsewhere. I'm cautiously positive to this idea.

**Comment by clearwater-trust** [comment]
I really like to idea of BSQ bonding. Making high risk payment options available for those who have bonded the requisite amount is super smart. BSQ bonding really highlights the value/power of the DAO. We should attempt to implement all kinds of account/security stuff with it like OCTP.

**Comment by wiz** [comment]
Japan sees insecure payment methods as an obviously bad idea. How can merchants in USA even do business if it's possible to send them money and then be able to take it back from them? Also, I'd expect it would increase the number of mediation and arbitration cases, which I thought we were trying to reduce... this seems like a bad idea.

I suppose it's not directly related to your proposal, but currently when users have issues, they appear in #general or #support asking for help, but since Bisq is a decentralized network, there's not much we can do to help them except give advice. After seeing users having major issues even with secure payment methods only, I don't think we should open up the possibilities for more issues with insecure payment methods and users messing up their bonds, etc. - users really do mess things up all the time and I think we need to present them a simpler flow with minimal chances of screwing things up, so I would be against requiring BSQ bonds for them to use the insecure payment methods they want to use.

**Comment by wiz** [comment]
I also want to add that more than anything about this proposal, I really hate the thought of having to tell new users they would need to buy and hold BSQ for X months just to buy some Bitcoin on Bisq with their payment method of choice. Users should never have to buy BSQ just to trade on Bisq, because it would create artificial demand for BSQ colored Bitcoin and "pump the market".

Think about it from the newbie perspective. Imagine a user in USA who only has insecure payment method apps like PayPal and Zelle and CashApp - if they want to buy $1000 worth of Bitcoin, now they would somehow have to:

- Buy $1000 worth of BSQ
- Lockup that BSQ bond for 180 days (PayPal dispute period)
- Accept offer to Buy Bitcoin using PayPal from another person who did same BSQ bonding ??

This really sucks and newbie would probably give up on step 1, because nobody wants to buy BSQ and post a BSQ bond just to buy some Bitcoin... and even if Bisq worked absolutely perfectly through this process, users would still mess up their Bisq app somehow, and they would never use Bisq again after having painful process or risk losing funds.

I feel we need to fix the critical Bisq issues instead of adding new risky functionality into the app. Currently Bisq has many issues so I personally don't feel comfortable to hold any BSQ at the moment. Would new users feel comfortable to do this, just so they can use an insecure payment method? Why not just keep forcing users to use secure payment methods instead like we are doing now? PayPal might work fine between trusted trading parties, but Bisq is trustless so it doesn't really make sense to use trusted payment methods IMO.

**Comment by sqrrm** [comment]
@wiz While I agree that we should try to avoid more complications for traders that lead to more bugs and an overall deteriorated view of Bisq from users, the point made in the OP is that we might have to move to allow the more p2p oriented fiat platforms. If the preferred and more secure fiat payment methods, such as Zelle, stop working due to the banking side being hostile we would have no other choice.

**Comment by wiz** [comment]
I think the fundamental issue is having to buy BSQ and lock it up, users would probably be okay to lock-up BTC holdings for collateral, but obviously we would have to somehow figure out how to confiscate the Bitcoin bond, an unconfiscatable hard money :sweat:

**Comment by sqrrm** [comment]
Yes, it's not a great first step to be forced to buy BSQ. Locking BTC would be nice, but a big reason BSQ exist at all is due to not being able to put up BTC bonds in any decentralized fashion. Until BSQ has a good reputation and some stability it will be hard to make the off chain protocol with bonded BSQ work properly. Still worth discussing the concept though.

**Comment by wiz** [comment]
My thoughts about the use cases and justifications for BSQ colored coin:

1. BSQ used for voting in DAO governance is an excellent use case as it gives developers plausible deniability about who is "running bisq" and prevents Bisq from being regulated by governments.

2. BSQ used for compensation and payment of trading fees also seems fair, since only contributors can color BSQ and sell it to other Bisq users - there is no ICO-style raising capital, it's a way to charge customers reasonable fees for a useful service, and compensate contributors for their contributions.

3. BSQ used for bonds by contributors also seems reasonable, since contributors are staking their own BSQ earnings to do "trusted roles" like owning the domain name or being the GitHub admin.

4. BSQ used for bonds as trading collateral (i.e. in the v2 proposal) feels a lot harder to justify when the existing "security deposit" system, combined with "secure payment methods", works so well. The only real problem with security deposit transactions is the lack of optimization for on-chain TX fees. For example, a good start would be fixing it not to use 4 huge on-chain TXs, even a single on-chain TX with segwit/bech32 would be a huge improvement - of course moving to some multisig Lightning transaction would be best.

But requiring BSQ bonds locked up for 6 months just to use insecure payment methods doesn't really make sense - anyone who is serious about trading Bitcoin on Bisq would rather use a secure payment method, and any casual newbies who just want to try out Bisq wouldn't be willing to buy/hold and lock-up BSQ for 6 months just to buy some Bitcoin. It makes more sense to simply require them to use the existing security deposit / secure payment method system.

**Comment by mpolavieja** [comment]
What about allowing Insecure methods such as Paypal to buy BSQ directly?   The BSQ would be locked for 180 days and therefore useful for bonding. 

So newbies would not need BTC in order to be able to buy BTC.

**Comment by wiz** [comment]
Aside from the fact that somebody would need to take the counter-party risk of receiving those PayPal funds, KYC themselves and withdraw the PayPal funds into a fiat bank account, etc. that process would still be quite insecure to fraud:

1. Buy list of stolen credit cards on darknet marketplace
2. Use stolen CCs to signup PayPal accounts
3. Buy locked-up BSQ bonds on Bisq using stolen CCs on PayPal
4. Buy BTC on Bisq using stolen CCs on PayPal (with locked-up BSQ as collateral)
5. All the PayPal funds recipients would get reversed, etc. and the locked-up BSQ would only be 50% of the cost of compensating both the BTC sellers and the BSQ sellers

So maybe if you require 200% collateral and some other really strict rules, you could become a trusted third party that sells BSQ for PayPal - but why would you want to take all that risk for yourself and lockup all that capital in BSQ for 6 months, when we could just require everyone to use secure payment methods and security deposits? It's not good for decentralization or security IMO.

**Comment by chimp1984** [comment]
@mpolavieja 
> What about allowing Insecure methods such as Paypal to buy BSQ directly?....So newbies would not need BTC in order to be able to buy BTC. All the process of buying BTC will be solved within Bisq.

Interesting idea with buying BSQ directly but there is still the requirement for miner fee in BTC so problem of the first time user who has no BTC is not solved by that. ;-(

@wiz 
> secure payment methods...

As long they exist all fine and I agree that the extra friction will probably does not create any market and therefor not justify the effort to implement it. But what if you cannot use your normal bank account anymore because they become more nasty (starting already from my observations - even non Bitcoiners get more troubles with closed accounts or blocked transactions). P2P payment is not a core business for normal banks and basically serving customers seems to be not their core business at all. P2P payment platforms thought are built to serve normal customers, they dont give out loans and do not play monopoly with central bank money. All those P2P payment methods have the policy that they must be only used between friends and family members (that why the allow chargback so easily). Of course that is not reality (AirBnB, Ebay,...) but it seems it works in reality for those use case good enough that their business model has not disappeared and seems to be even extending. With Bisq its different as a scammer has zero risk. With AirBnb or others there is usually always some kind of KYC included so scamming is harder. So the only way how we could enable it for Bisq (if/once needed) would be to add some extra security. Scammers usually don't like to risk anything (they are used to not trust anyone as they know how bad the world is looking each day into their mirror ;-)). So even the security of the proposed model is far from perfect, it might be good enough to work as a first step. As said it is just a rough idea and might be to insecure or flawed anyway. I just wanted to spread it, maybe it leads to something further idea and maybe we find a way how we can integrate the OCTP without a hardfork. It would be anyway strictly optional, so maybe it would be used only by a minority. We also added Face to Face trade even it has zero security from Bisq side and it seems it is used and there are not issues so far.

Btw: There are quite a few reputation bonds in Bisq locked up. I have no idea who has done those and for what they are used. But it seems some people have found some use case for it. We should not ignore that.

<img width="1161" alt="Screen Shot 2019-10-28 at 17 59 20" src="https://user-images.githubusercontent.com/54558767/67724889-7b505a00-f9ae-11e9-959a-b83b702dc542.png">

**Comment by chimp1984** [comment]
> BSQ used for bonds as trading collateral (i.e. in the v2 proposal) feels a lot harder to justify when the existing "security deposit" system, combined with "secure payment methods", works so well. The only real problem with security deposit transactions is the lack of optimization for on-chain TX fees. For example, a good start would be fixing it not to use 4 huge on-chain TXs, even a single on-chain TX with segwit/bech32 would be a huge improvement - of course moving to some multisig Lightning transaction would be best.

There aree plenty of problems and restrictions with the current trade protocol.
- Miner fee
- Onchain privacy
- Slow due requirement for block confirmation
- Maker need to be online

Reducing to 2 tx instead of 4 might be possible but not sure and not trivial. But still does only reduce on of the many problems.

I am not sure if MultiSig on Lightning is feasible and possible in any realistic time frame. Once it is a possibility it is for sure something we need to look at. But my hopes for that are rather low (talked with some LN devs).

**Comment by mpolavieja** [comment]
> Interesting idea with buying BSQ directly but there is still the requirement for miner fee in BTC so problem of the first time user who has no BTC is not solved by that. ;-(

Yeah, for that to be possible the other trading peer should have to pay all mining fees (first the BSQ seller and then the BTC seller).

@wiz, I understand you meant the BSQ / BTC buyer could become a trusted trading peer. The bigger problem I see with my idea is that the scammer is just risking the cost of buying the CCs and/or his time.  

I am not familiar with Paypal, what happens if the receiver (the BSQ/BTC seller) withdraws all the balance from his Paypal account after receiving the quantity? Is this allowed? If a chargeback occurs, will paypal request to deposit back the chargebacked amount?

**Comment by chimp1984** [comment]
Looking again to the locked up reputation bonds. It is surprising that some are locked up > 1 year! Would be really curious what are the use cases. Seems to be not just tests, otherwise you would use a short lock time.

**Comment by mpolavieja** [comment]
> We use our freedom as reusable security deposit

Nakamoto consensus (PoW) is a succesful alternative to private property laws for a very specific kind of asset, as it handles very well ownership and transfering of bitcoin units.   Both Nakamato consensus and property laws are protocols.

Money is just one leg of a exchange.  Bisq is trying to figure out an alternative protocol for exchange.  This is an extremely difficult but very encouraging challenge.  Any ideas and brainstorming around this are extremely valuable.

Doing absolutely all exchanges on spot or fully guaranteed is very expensive.   The free market alternative to that is credit (reputation) and interest is its price.  If I may nuance a little bit the claim "freedom as reusable security deposit", the first layer of that security deposit is your equity (net worth) and future income, and if that is not enough, then it is your freedom.   

Locking BSQ is a proxy of net worth, but net worth is much more reusable and scalable than BSQ.  Cryptographically attesting net worth of individuals seems to me an unfathomable task for Bisq, that's the job of a bank.  www.lendingclub.com seems that is succesfully disintermediatinig banks, but of course they rely on KYC :(   Not sure if despite that we could pick any idea from them.

**Comment by mpolavieja** [comment]
Thinking a bit more about this I believe @wiz point is very accurate.  BTC is Money (not anyone else´s liability) while fiat payment methods are all debts, more or less risky.  So except for f2f trades a BTC seller is not really selling BTC but granting credit for a number of days (90 or 180 depending on the chargeback limit of the payment method). 

The reality is that Paypal payments are high risk "all or nothing IOUs", they are junk debt and we cannot change that.  So it is not realistic to exchange it for BTC at par.  Exchange is only possible if they trade at a very high discount, or if the buyer provides a high collateral, or provides a strong real reputation somehow backed by net worth.

**Comment by wiz** [comment]
> Btw: There are quite a few reputation bonds in Bisq locked up. I have no idea who has done those and for what they are used. But it seems some people have found some use case for it. We should not ignore that.

I think this is likely newbies locking up their BSQ by mistake trying to figure out how Bisq works.

**Comment by chimp1984** [comment]
Seems that proposal got stalled. Can be closed from my side.
