### ISSUE TITLE
Change model for asset listing

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/proposals#153]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

### Overview
We should review the cost/benefits of asset listing as it is currently in a bad state. 

Reviewing, discussing and merging assets is quite a bit of effort and we should verify if the benefit those assests add to Bisq justifies the costs.

### Details
From 38 assets added since v1.0.0 only 15 paid the listing fee (39%), so that shows that the majority is not even interested to get traded, they probably just want to add Bisq as exchange to their webpage because it is so easy and cost free.
Total paid listing fee was 843 BSQ (FAIR stood out with 365 BSQ, all others are mostly around the min. required 30 BSQ - we should consider to increase that min. required fee by DAO voting). 
I did not collect exact trade volume data (und from that derived earned trade fees), but at a quick look it seems that only 1 asset (XZC) had considerable trade volume (abount 1.5 BTC which results in about 60 BSQ trade fee revenue).    

So roughly Bisq has earned 900 BSQ for doing the work to list 38 assets. This is 23 BSQ per asset. I doubt that the effort for review, discussion (including such unpleasant ones as at https://github.com/bisq-network/bisq/pull/3789, https://github.com/bisq-network/bisq/pull/3650) and merge is justified by that revenue return where as we saw 61 % are clearly not even interested to get traded.

I think we have to reconsider the way how we deal with assets. The listing fee does not solve the up-front costs for adding an asset. So we need to add the costs upfront to ensure a filter machanism to only get added coins which have serious intentions to use Bisq for trading.

### Solutions
I would recommend 2 possible solutions. 

#### Solution 1
Put all asset listing on hold until we have found a proper solution (we can make exceptions if a maintainer considers and asset as interesting). 
We added already way too much effort (this proposal included) and the "return" value of adding assets is close to zero. We should not waste too much time on a difficult to solve problem and the overall "asset community" has such a negative track record that they are not worth to get more attention. But we should stay open for upcoming interesting ones like Blockstream's Liquid assets.

#### Solution 2
Try to find a simple model which avoids discussions and keep dev effort to a minimum while ensuring that costs for adding an asset are covered by the issuer. 
One issue here is that we WANT to support interesting assets (like GRIN, BEAM, Blocksteam's Liquid asseets,..) which come rarely but then we do not want to put a financial burden on those as those often do not have deep pockets but are often pure OS projects. 

I would suggest following model:
We create a new Github repository where only Github issues are used for asset listing (repo only contains a reame with instructions/rules). We don't want to get polluted our Github issue and PR list anymore. Asset issuer need to fork Bisq and make a branch with the asset added according to our existing requirements and link that branch in the Github issue. 
Any asset issuer can partizipate in an auction where they make an upfront BSQ payment in form of burning BSQ and post the "Proof of Burn" in the issue (use asset name as pre-image for the burn tx, post burn tx id). 
Bisq maintainers (only maintainers as those have to do the merge) can pick at each release some of the assets if the upfront paid fee seems to justify the effort. Beside that they can pick an asset if they think it is an interesting one - and they do NOT need to justify that - we don't want to get into the discussion why GRIN is more interesting than Denarius. There is no guarantee to get ever listed independent of the paid fee. If a coin smells too much like a shitcoin no amount might be enough that a maintainer will pick it. But general rule will be that they pick some of the coins which have paid most for getting listed as those show to have some "skin in the game" and justify the cost for review/merge.  
The maintainer will make himself a PR using the code from the asset issuers fork (avoiding all that pain to educate asset devs to make a PR following our guidelines). If there are severe mistakes in the branch like asset tests fail, this coin will be dropped and has little chance to get picked up again. Maintainer pull the assets when they want to spend time on that. Asset issuer who start to push and advertise they asset to maintainers will get rejected. If there is enough paid fees maintainers will come by themself as they see it as a valuable income stream for Bisq.

The upfront paid fee does not mean that there is no listing fee. Once an asset is added the issuer need to pay the listing fee and show trade activity.

I hope that model would solve several problems:
- No pollution of our Github PR and issue list with asset listing requests
- No wasted time dealing with asset PRs or issues
- Generate upfront costs to avoid all those assets which are not interested to get traded on Bisq anyway
- Bring costs/benefit into some healthy balance
- Allow interesting coins to get added without a financial barrier
- Avoid annoying discussions with shitcoiners, avoid that their troll army pollutes Bisq's communication channels
- Limit number of added assets

### Statistics
Here are some statistics taken from the Bisq app trade statistics, asset listing screen and Github release page.

Assets listed:
v1.2.3 7 Nov
Added 1 new asset: LBRY Credits (LBC)

v1.2.2 1 Nov
Added 8 new assets: Animecoin (ANI), CTSCoin (CTSC), Donu (DONU), Faircoin (FAIR), Krypton (ZOD), ndau (XND), NoteBlockchain (NTBC), uPlexa (UPX)
Removed 2 assets: Byte (GBYTE), Neos (NEOS)

v1.2.0 29 Oct
Added 7 new assets: Animecoin (ANI), CTSCoin (CTSC), Donu (DONU), Faircoin (FAIR), ndau (XND), NoteBlockchain (NTBC), uPlexa (UPX)
Removed 2 assets: Byte (GBYTE), Neos (NEOS)

v1.1.7 23.Sep
Added 14 new asset: DarkPay (D4RK), Emercoin (EMC), Ergo (ERG), Know Your Developer (KYDC), Kore (KORE), Masari (MSR), Particl (PART), PENG Coin (PENG), SixEleven (SIL), Solo (XSL), VARIUS Coin (VARIUS), Vertcoin (VTC), WORX Coin (WORX)

v1.1.3 16 Jul
Added 4 new asset: Genesis (GENX), Know Your Developer (KYD), Myce (YCE), Starwels (USDH)

v1.1.2  4 Jun
Added 2 new asset: Burnt BlackCoin (BLK-BURNT), ZeroClassic (ZERC)

v1.1.1 6 May
Added 2 new asset: List Trust Eth reOrigin (TEO) and ParsiCoin (PARS)

Listing fee and trade activity:

Paid listing fee and actively traded:
PART (30 BSQ)  		4 trades
SIL (30 BSQ)  		10 trades

Actively traded:
SOLO (0 BSQ) 		1 trade with 0,1 BTC (probably dev trade to avoided to pay listing fee)

Paid listing fee and in trial period:
DAI (64 BSQ)  		11 trades
FAIR (365 BSQ) 		2 trades
GALI (30 BSQ) 		0 trades
VTC (30 BSQ) 		0 trades

Paid listing fee but delisted du trade inactivity and trial period over:
VEIL (75 BSQ)		0 trades
KORE (40 BSQ)		0 trades
XZC (35 BSQ)		14 trades  -> was quite a bit of volume but since august not traded anymore
BTM (30 BSQ)		3 trades
D4RK (30 BSQ)		2 trades
ERG (30 BSQ)		0 trades
LBC (30 BSQ)		3 trades	
PARS (30 BSQ)		1 trade
UPX (30 BSQ)		0 trades

Conclusion:
We added 38 assets since v1.0.0. 
15 of those (39%) paid the listing fee of 843 BSQ in total. 
4 assets are actively traded (one more has only 1 trade but did not pay listing fee, so that looks like a dev trade to avoid the listing fee).
Most trade volumes is very low, only exception was XZC but it was not traded anymore since August so it got delisted. Maybe we should adjust our delisting algorithm to reflect high past trade volume for delisting period.

**Comment by MwithM** [comment]
It's embarrassing to see such a list of not traded unknown altcoins, even if very little effort us put on it.
I completely agree on the need of requiring altcoin listing solicitors to pay BSQ to start working on them. If the altcoin is successful, they could claim some of their listing fee back.
Altcoins without volume after 3 months since listing should be vanished from Bisq client, unless a relisting fee is paid.

**Comment by carsenk** [comment]
So you guys should not be biased as a decentralized exchange. You are pushing yourselves into centralization with a proposal like this, blindly hating on Denarius and other altcoin projects as well, altcoins are what keep you alive. Is it really that hard to maintain? It seems to me, that the current submission structure is entirely non-transparent and centralized, a majority of the work done by the submitter, with a handful of people only interested in BISQ to approve/deny PRs.

You should probably just delist everything and shut down BISQ, because no one is going to use it.

I will be writing some articles in regards to all of this :)

**Comment by chimp1984** [comment]
> altcoins are what keep you alive

No. See statistics. Monero is only altcoin traded with serious volume. Then there are a handful with moderate volume and those are usually old established ones. Newly added assets are to 99% wasted effort as the statistics show.

**Comment by MwithM** [comment]
It's not altcoins that are keeping us alive. Contributors, Monero and Bitcoin are.
If all the work to add a shitcoin has to be done by the submitter is because of some shitcoin maintainers who add nothing to this project.

**Comment by chimp1984** [comment]
Those are actively traded assets:
<img width="1165" alt="Screen Shot 2019-12-15 at 13 13 26" src="https://user-images.githubusercontent.com/54558767/70866853-be559500-1f3c-11ea-8ed0-89629b13a69b.png">

<img width="1158" alt="Screen Shot 2019-12-15 at 13 14 44" src="https://user-images.githubusercontent.com/54558767/70866875-e8a75280-1f3c-11ea-83a7-d553bfcd5cdc.png">


Monero, Zcash, Dash, Sia and ETH are the only one with trade volume  > 1 BTC in the past 4 months. None of the newly added 38 assets made it into that list.

**Comment by chimp1984** [comment]
> blindly hating on Denarius

No I don't hate Denarius, I don't know enough it have any opinion. But I hate the style of the discussion you and your supporters brought into our communication channel, including a rude insult of one of our most productive developers.

And I hate to spend effort on the wrong things and losing that time to spend for the important things. This descision on what a contributor spends their time is a personal subjective decision. The maintainers are not forced to spend time on reviewing, discussing and merging an asset with does not add value to Bisq by a probabilty of > 99% according to the statistics and experience we gained (this experience goes back to day 1 of Bisq but I don't want to spend effort to generate statistics for that). 

The assest which added value and which Bisq contributors from the cypherpunk ethos usually support (e.g. GRIN) can be counted on one hand. I still want to have a model where we are open to those without financial barrier, but not to be abused as free listing service from those with whom we have not much in common (e.g. shitcoins).

**Comment by carsenk** [comment]
> > altcoins are what keep you alive
> 
> No. See statistics. Monero is only altcoin traded with serious volume. Then there are a handful with moderate volume and those are usually old established ones. Newly added assets are to 99% wasted effort as the statistics show.

Sitting here hating on projects trying to get added with you guys, you are literally crossing out volume that could be brought to the exchange, I also have a large social media following and am fairly well known within crypto. You stomping on feet like you are, is only going to get you in hot water. You stomping out a crypto from even having that chance is unfair and super centralized.

You committing defamation does not help you very much as well.

**Comment by buzzkillb** [comment]
I like how BISQ works, I probably was a percentage of your volume for a bit on a main pair while I played around on the wallet. But the way you treated Carsen for making a mistake that wasn't listed in your documentation makes me wonder how you treat your users making mistakes on your platform and what type of support would be offered if issues arise. What ends up happening is you have users like myself who can help make markets and donate BSQ to keep these projects listed, not even caring anymore to use your product. Is it a loss for me? Not at all. Is it a loss for you? Eventually it will be as people are soured on the way you are treating Bitcoin forks, forks that are making the overall scope of cryptocurrencies stronger.

**Comment by sqrrm** [comment]
Please keep any references to specific assets and people away from this thread as we're discussing the generic process of listing new assets. Could we move those comments to their own relevant issues?

I agree that it's a wasted effort to list all these assets that are mostly never traded. I like the idea of a proof of burn to list an asset. Possibly to be refunded if the asset generates enough trade volume within the first three months, but that's also not necessary. That would at least balance the cost to the DAO to list the asset. I would still leave it open to the maintainer or other contributor to review and merge the PR.

**Comment by carsenk** [comment]
> Please keep any references to specific assets and people away from this thread as we're discussing the generic process of listing new assets. Could we move those comments to their own relevant issues?
> 
> I agree that it's a wasted effort to list all these assets that are mostly never traded. I like the idea of a proof of burn to list an asset. Possibly to be refunded if the asset generates enough trade volume within the first three months, but that's also not necessary. That would at least balance the cost to the DAO to list the asset. I would still leave it open to the maintainer or other contributor to review and merge the PR.

The comments above will remain and are entirely relevant to this discussion.

I do agree with your proof of burn to list an asset and a possible refunding if the asset provides trading volume. I do also agree that it should be left open to anyone not just contributors or maintainers to submit/suggest new assets for listing.

**Comment by wiz** [comment]
> I think we have to reconsider the way how we deal with assets. The listing fee does not solve the up-front costs for adding an asset. So we need to add the costs upfront to ensure a filter machanism to only get added coins which have serious intentions to use Bisq for trading.

Bisq's current DAO proposal process works well, so IMO we should use it for listing new assets. However, too many DAO proposals can become a DoS vulnerability on our time to review and discuss all the proposals, so we should also require a non-refundable Proof of Burn as an *application fee* when submitting a DAO proposal to list a new asset. If the proposal is rejected, the application fee is not refunded.

Additionally, Bisq should make the application fee very expensive, and only allow the reimbursement of the application fee if the asset listing is approved and meets certain criteria for trading volume within the first few months. This will allow legitimate projects that earn fees for Bisq to get listed for free, but financially disincentivize scammers and shitcoiners from wasting our time, since they know they will just be paying the DAO to reject them.

> From 38 assets added since v1.0.0 only 15 paid the listing fee (39%), so that shows that the majority is not even interested to get traded, they probably just want to add Bisq as exchange to their webpage because it is so easy and cost free.

For the Markets API service, it would be great if we mass-delisted all these totally untraded assets from Bisq - it just clutters our website, complicates the API, and increases the load on the server and P2P network, causing even more problems...

**Comment by MwithM** [comment]
It was nice having a free of charge listing model, but it's a window for spam and using scarce resources.
I don't think listing fee should be very high, because it would make Bisq tempted to list scams just for the listing fees.

**Comment by carsenk** [comment]
> 
> Additionally, Bisq should make the application fee very expensive, and only allow the reimbursement of the application fee if the asset listing is approved and meets certain criteria for trading volume within the first few months. This will allow legitimate projects that earn fees for Bisq to get listed for free, but financially disincentivize scammers and shitcoiners from wasting our time, since they know they will just be paying the DAO to reject them.
> 

If you will be doing anything with raising any fees, you should make a transparent itemized list of all costs associated with listing a new asset. In my opinion, it seems a majority of the asset submission is upon the submitter, which they should know what they are actually paying for anyways. By raising a fee also, you could just be giving the actual scammers an advantage and opening to just pay the fees, as they usually have funds from previous scams to pay for listing fees etc. you guys should think of a better method of verifying coin projects rather than just charging a fee/regular asset submission process.

**Comment by justinvforvendetta** [comment]
trying to wrap my head around how "merge pull request" costs anyone time or money...  right now, many "shitcoins" (as @wiz calls altcoins) have more volume than the entire exchange. you want to keep it small and pretend merging a pull request costs a lot of time and money, be my guest. doesn't sound very decentralized to me anymore. maybe pseudo-dex is a better term. i feel like the attitudes of some people have strayed far from @ManfredKarrer original vision for this project.

**Comment by ManfredKarrer** [comment]
> have strayed far from @ManfredKarrer original vision for this project.

No, supporting shitcoins was never a goal of Bisq. Supporting novel altcoins which have done some interesting technical or conceptual achievements is a goal.

**Comment by carsenk** [comment]
> > have strayed far from @ManfredKarrer original vision for this project.
> 
> No, supporting shitcoins was never a goal of Bisq. Supporting novel altcoins which have done some interesting technical or conceptual achievements is a goal.

You are that guy that does not know the meaning of DYOR within altcoins or those that have been mentioned. Plenty of notable advancements and technical achievements. You calling altcoins, shitcoins, just proves your ignorance more, and as to why people should not support your work. A DEX should be open to anything and everything, not a centralized set of rules made by some stuck up BTC/XMR maximalists.

This project needs better direction, instead of just applying hate to your replies, try to come up with something at least reasonable for proposal rebuttal.

**Comment by justinvforvendetta** [comment]
@ManfredKarrer it seems to me, that some people at bisq feel that the only coins not shitcoins are monero and btc.  when you first launched bitsquare, you seemed very excited to be a dex for the entire crypto market, maybe i was wrong. to say that verge in particular has not done anything interesting or technical would be an outright fallacy. i can name several things we have done that we are the only ones doing/have done. but alas, i will leave you to your project. enjoy the bitcoin and monero market and good luck. i envision a large dex will be a top contender soon, but not with the vision i see here.

**Comment by justinvforvendetta** [comment]
lol remind me about this in one year from now, so i can laugh about how i spent more than 30 seconds of energy here

**Comment by alexej996** [comment]
Not a popular opinion within contributors, but I actually think the best solution would be to make altcoin listing not require a PR and add altcoin listing within the app itself, if that is possible code-wise.

I do think most altcoins are just there to grab some quick cash, but I don't think we should generalize in our listings and make it harder then it needs to be. If we make the process not require any dev effort long term, we could have a win-win situation where everyone is happy.

I think that in a perfect world we could review every altcoin and figure out which ones are bad apples and which are fine, but I don't think we should waste our resources on a job that isn't that rewarding. We should let users make Bisq what it is, not just contributors. Bisq isn't a great project only because it has great contributors, but because it has great users as well.

Most popular altcoins should optimally be automatically listed in drop down menu and all of those altcoin dealings, I think, should be left mostly to the users. Altcoins are generally easy to deal with from Bisq's perspective, no chargeback risk, easy to prove payment and etc. There isn't much to worry about here, I think users could handle it and contributors would have less things to take care of.

**Comment by justinvforvendetta** [comment]
@alexej996 well bisq would of course also have more contributors if outside devs were able to make pr's. but that might actually lighten the load for existing devs and seems this is a for-profit endeavor, and not so much an open source dex. i do wish you, personally, the best of luck though, because you seem to be using logic. a dex will come along soon, that has all the top 100 coins, is truly open source, inviting, and sweeps the entire community off its feet. it just has to, law of nature. something bigger and better always comes along. the vision here isnt broad enough to allow for this to be "the one".

**Comment by justinvforvendetta** [comment]
at this point, even if we were added right away, i would not use our twitter account with 300k followers, or our facebook/telegram/discord, with tens to hundreds of thousands of viewers, to promote it. that is why my "shitcoin" has 400x the volume this entire exchange does cumulatively. no one knows about bisq, and many of the people involved are just bias and rude. that's not something we want to advertise to our community lol ☮️

**Comment by ManfredKarrer** [comment]
@justinvforvendetta 
I have not called out any particular coin as shitcoin.

See the initial proposal from @chimp1984 . Many coins listed don't care at all to get traded on Bisq, and it seems their only intention is to have another exchange on their webpage to pump up their scam. 

@alexej996 
Bisq tried many approaches in the past and fact is that way too much effort went into asset listing for very little return (see number above). Automated listing would cause many problems (that is why there are minimal requirements) and listing ICO coins would add unnecessary legal risks to Bisq. The above proposal has a reasonable idea. If that is too complex to find consensus I think we should just halt adding any asset until consensus if found and avoid to waste more time on that topic. Bisq has much more important things to solve than to add each release a bunch of altcoins where 90% are never get traded anyway.

**Comment by justinvforvendetta** [comment]
> Bisq has much more important things to solve than to add each release a bunch of altcoins where 90% are never get traded anyway.

haha, definitely agree here.

**Comment by sqrrm** [comment]
I think @alexej996 has a good point, and it has been discussed a year or two back, I like it.

Allowing anyone to list any asset would remove the burden on developers to review and merge PRs for new assets. Assets listed through the app would have a generic format and only be visible to users that explicitly want to trade that asset (command line argument or similar). Any asset that wants to get listed as a default asset needs to first be traded at a certain rate as a generic asset.

**Comment by justpaulgmx** [comment]
Exactly! Thank you Manfred. 
-- 
Sent from my Android phone with GMX Mail. Please excuse my brevity.On 12/28/19, 6:19 PM Manfred Karrer <notifications@github.com> wrote:

   
   have strayed far from @ManfredKarrer original vision for this project. 
   
  No, supporting shitcoins was never a goal of Bisq. Supporting novel altcoins which have done some interesting technical or conceptual achievements is a goal.

**Comment by mbroemme** [comment]
> 
> 
> > have strayed far from @ManfredKarrer original vision for this project.
> 
> No, supporting shitcoins was never a goal of Bisq. Supporting novel altcoins which have done some interesting technical or conceptual achievements is a goal.

@ManfredKarrer Please keep in mind original goal of Bisq to be an decentralized exchange without centralized control. If there will be an instance which decides by nontransparent rules which asset will be listed it fundamentally contradicts this design principle.

As an intermediate step - to avoid serious drastic changes as a single step - I would force people to keep their original PR updates. I see a lot of PRs where people are dumb and don't know how to squash commits or forgot to sign them. As first step we should apply the following:

1. Force people to squash commits, rather than opening new ones again and again. Yes it is some teacher work, but in long-term it will help and reduce duplicated asset listing PRs.
2. Create a protected branch and enforce signed commits. It will immediately avoid PRs without signed commits. I see many PRs with comment like: "Please sign your commits".

**Comment by justinvforvendetta** [comment]
@mbroemme dont worry, a new, real DEX that actually has a massive market (which is the only way to properly "D" an "EX" (lol) will come along. there are a ton of them being worked on right now, and bisq is easily fork-able anyway. this one will die soon enough. its almost dead anyway.

**Comment by chimp1984** [comment]
Closing as this discussion does not discuss any of the 2 options but continues to burn energy on an area which provided a totally negative balance of added efforts and generated returns. I suggest to put adding assets on hold until there are sufficient resources and other more important problems are solved.

**Comment by carsenk** [comment]
@chimp1984 Your closing this because you disagree with all the disagreement you are getting. Pathetic.

**Comment by m52go** [comment]
> If there will be an instance which decides by nontransparent rules which asset will be listed it fundamentally contradicts this design principle.

This is a fair point, which is why pausing asset listing is probably most appropriate right now. The most recent rules to list _and_ to not list aren't clear. I've [proposed the change to docs](https://github.com/bisq-network/bisq-docs/pull/191).

**Comment by dan-da** [comment]
imho, a "decentralized exchange" should not be in the business of regulating what assets users can exchange.    Rather, it should provide a mechanism for bringing parties together and exchanging whatever assets they wish.  Along with search and categorization of assets.  I think bisq had a lot of early potential but really lost the plot on this, and instead wandered off deep into dao land.

**Comment by bwusth** [comment]
December 2019.....?     Listing of new cryptocurrencies has been "on hold" since December 2019....!?    Is Bisq still being actively developed or is it a dead project?

I agree with the suggestion that users should be able to add assets themselves. The assets "added" by the most active users.... automatically get added.  Period.  That would be truly decentralized. 

Any news about new DEXs or forks of Bisq...?

**Comment by MwithM** [comment]
Since this hold in new assets was approved, I remember that L-BTC, R-BTC and USDT have been added as exceptions. None of them had much liquidity.
Bisq focus is fiat-btc, listing a myriad of coins won't be very useful for Bisq.
The system Bisq had in the past consumed developers time with no benefits for Bisq, listing coins that weren't traded at all.

**Comment by bwusth** [comment]
Perhaps listing altcoins doesn't "benefit Bisq" (whatever and whoever that means), but it would clearly benefit bisq USERS --- like me and my friends.   The more coins available on Bisq, the easier it is to promote and recommend Bisq.   Not everything is about trading fees directed to some centralized authority.

Why not allow users to add coins themselves... through the app itself.  Once that ability is added, it would cost no developers' time at all.

It seems like "someone" wants guaranteed income.... BEFORE making the product completely useful --- rather than the other way around.

You add the ability for users, directly within the app, to "Request a New Altcoin Listing".  They enter the code letters of the coin (i.e. FIRO), and their receiving address.  As soon as 10 people request the same coin, it is automatically added.   If this is done once, programmatically, then why would it involve any work from that point on?

**Comment by MwithM** [comment]
> It seems like "someone" wants guaranteed income.... BEFORE making the product completely useful --- rather than the other way around.

I want that those who propose a coin to have skin in the game. So if someone adds a coin, it needs to generate trading fees, otherwise it's clearly not useful for Bisq or anyone, except maybe for those who can say that their alt is listed somewhere.
My idea on this issue stated that maybe this trading fees should be reimbursed, as I said on this [comment](https://github.com/bisq-network/proposals/issues/153#issuecomment-565830688):

> It's embarrassing to see such a list of not traded unknown altcoins, even if very little effort us put on it.
I completely agree on the need of requiring altcoin listing solicitors to pay BSQ to start working on them. If the altcoin is successful, they could claim some of their listing fee back.

**Comment by MwithM** [comment]
> The more coins available on Bisq, the easier it is to promote and recommend Bisq. Not everything is about trading fees directed to some centralized authority.

Please read [about the DAO](https://bisq.wiki/Introduction_to_the_DAO), it looks like you have no idea about the amount of effort it took developers to create a DAO that can work on Bitcoin to reduce the main central point of failure, which is distributing revenue. 
Before the DAO existed, they worked for no profit to develop a platform that works to trade BTC for fiat. Once the product was good enough and started to attract users, they built from 0 the only DAO in Bitcoin, leaving other simpler (and more profitable) issues to a side in order to build a resilient platform. 
Bisq is a Bitcoin, not a crypto project: alts are welcome, but I don't see that listing all the coins at coinmarketcap will make Bisq better as Bisq won't find way to attract users who, for some reason, dislike Bitcoin.

**Comment by bwusth** [comment]
Most people into crypto investing these days hold more than one cryptocurrency.  The days of it being one-and-only-one almighty Bitcoin... are over... like it or not.  But Bitcoin is still the predominant gateway tool used to buy all of the myriad of newer better competitors out there.  So on one hand, I think that it's very shortsighted to basically censor all new coins on the Bisq platform....

However, having said that, and after having slept on it....  🤔  I think Bisq isn't that important when it comes to buying other coins.   There are tons of instant no-KYC trading sites available now.  In fact, they are even built-in to wallets like Edge.app now....  and they provide a much better user experience and better exchange rates.

So really, the best advice to give new users is....   Go ahead and use Bisq to buy your no-KYC Bitcoin.... then use Edge Wallet to exchange that BTC for all the crypto coins you really want to hold.

**Comment by bwusth** [comment]
"alts are welcome" --- Yet they can't be added by users?

"dislike Bitcoin" --- huh?  If you want an alt then you dislike Bitcoin?
