### ISSUE TITLE
Increase security deposits to avoid future trades and mediation.

### ISSUE THREAD

**Issue by taxd** [bisq-network/proposals#155]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I propose that the minimum security deposit for both buyer and seller should be increased to at least 15%. This will increase the skin in the game for the traders and incentivize them to quickly finalise the trade themselves without going into mediation which is very costly for the DAO. In addition there will be fewer future trades. As is it now a standard trade is in fact an option for the buyer and a cheap one at that. This is not sustainable in the longer run. Sophisticated traders will know that they should increase the security deposit in volatile times, but most traders are not that sophisticated.

**Comment by chimp1984** [comment]
## We have currently following values for the security deposits:

### For buyer (he can do the chargeback, so it is higher here - maker can define between the min-max):
Default: 5%
Min. 0.5% for Altcoin, 5% for Fiat
Max. 20% for Altcoin, 50% for Fiat
Absolute min. deposit in BTC: 0.001 BTC (currently 7 USD)

For Seller:
Fixed: 5%
Absolute min. deposit in BTC: 0.005 BTC (currently 33 USD)


### I would suggest to change to  following values:
For buyer:
Default: 20%
Min. 15% for Altcoin, 10% for Fiat
Max. 50% for Altcoin, 50% for Fiat
Absolute min. deposit in BTC: 0.003 BTC (currently 20 USD)

For Seller:
Fixed: 15%
Absolute min. deposit in BTC: 0.005 BTC (currently 33 USD)
    
I don't remember the motivation why Altcoin buyer deposits have been so much lower as fiat. I think volatility risk is higher with altcoins and should be reflected in the buyer sec. deposit.
A motivation to keep buyers deposit low was to not increase too much the problem that you need BTC to buy BTC. Another one for both buyer and seller was to not require too much BTC to make a small test trade to try out Bisq. But I think the problem of "future trades" and not responding traders is a bigger one than the risk to increase the burden to try out Bisq. Specially if you end up in dispute because the peer has not enough skin in the game to follow the trade protocol at such a "demo" trade the intended effect would be contrary.

I am not sure if the suggested changes are too radical and if we should make smaller iterations to see how much effect they have. But I fear market volatility is a major factor which will overload any of our decisions, so it might be if there is low volatility over the next months that we assume we are fine with a moderate increase, but once a higher volatility hits the market get ger overloaded with future trade disputes and with the refund agent that becomes risky for Bisq (BSQ volatility) and expensive. So maybe its better to play on the safe side and if we see that the higher requirements cause too much opposition we can lower it again.


I tested the changes and tested between old and new client version and all worked without backward compatibility issues. Still would require proper testing but changing those values seems to have no risk.

**Comment by clearwater-trust** [comment]
The entire amount of the trade is the security deposit for the SELLER. In ten days their funds are sent to a "donation address".

Why would we require more skin from the seller when all of their funds are locked in a time-locked 2 of 2?

Security deposits should not increase for sellers. In fact, they should be decreased.

**Comment by m52go** [comment]
I've been loosely advocating for this change in other communication channels so I'm glad to see this proposal.

> The entire amount of the trade is the security deposit for the SELLER.

This becomes moot once the buyer sends payment to the seller. What's the sellers incentive to remain responsive after he's received payment, if he doesn't have a meaningful deposit to lose?

Deposit amount can also be an important measure for preventing [this attack vector](https://bisq.community/t/new-trading-protocol/8575/6).

> A motivation to keep buyers deposit low was to not increase too much the problem that you need BTC to buy BTC.

I don't think increasing the security deposit would have an effect on this issue. It seems the friction is with needing to acquire BTC to begin _at all_, not having to acquire _a particular quantity_ of BTC to begin.

As for amounts, I would prefer to see percentages be as alike as possible (i.e., 15% across the board instead of 10% fiat buyer variable, 15% altcoin buyer variable, 15% altcoin seller fixed, etc). But this is more for ease of understanding and communication than for tactical reasons.

**Comment by sqrrm** [comment]
I like this proposal. I also agree with @m52go that it's worth having the same values for all users, much easier to explain. If one of the main reasons for the security deposit increase is to limit he value of the free option it's even worth making buyers and seller having the same deposit. The free option works for both buyers and sellers, although the seller should not be able to get the payout after exercising the option, the arbitrator is likely to pay out anyway.

**Comment by mpolavieja** [comment]
For fiat, I don´t see why the minimum fiat deposit for the buyer (10%) should be lower than the seller (15%).   If there are no other strong reasons to make them different, I like @m52go suggestion to use 15% as much as possible (default and minimum for the buyer, and fixed for the seller).

**Comment by chimp1984** [comment]
I agree with @m52go about keeping values the same.

@sqrrm 
> The free option works for both buyers and sellers,

You refer to the "future trade" option, right? I only see that the buyer can do that. Once the buyer has sent the funds the seller can only confirm it, not confirming is breach of contract and leads to loss of his funds but he cannot avoid that his BTC got send to the buyer.

Another important issue is that we need to keep a minimal part of the deposit to return to any trader to keep some incentive to accept the mediated payout result. If one trader does not get anything because he violated the protocol he might decide to not cooperate to accept the mediated payout as he has nothing to lose anymore. If a certain part of the deposit always goes back to any trader in the mediated payout suggesting then some incentive stays. When it comes to arbitration the arbitrator will not pay out that min. refund, so a not accepting trader risks to lose that amount.

**Comment by chimp1984** [comment]
### Here is an updated suggestion:

For buyer:
Default: 15%
Min. 15% for Altcoin, 15% for Fiat
Max. 50% for Altcoin, 50% for Fiat
Absolute min. deposit in BTC: 0.006 BTC (currently 40 USD)

For Seller:
Fixed: 15%
Absolute min. deposit in BTC: 0.006 BTC (currently 40 USD)

Min. amount any trader gets back at mediated payout suggestion:
0.003 BTC (currently 20 USD)
This should give enough incentive to the losing trader to cooperate and accept the mediated payout. The UI for mediated payout suggestion would be adjusted so that the mediators cannot go below that amount.

**Comment by taxd** [comment]
I don't see much of an asymmetry here. Before the fiat transfer the buyer can default, but will then lose his security deposit. After the fiat transfer the seller can default, but will then lose his security deposit.
I suggest simplicity here, i. e. not finetuning the security deposits but having the same for alts and fiat and for buyer and seller. 
I would like the situation that mediation and appealing to the refund agent is only needed because of bugs or technical problems. All other problems should be solved by the traders. They can do this, having a communication channel, incentives and the terms written out in the contract.

**Comment by chimp1984** [comment]
@taxd - I agree. 
I think we also should emphasize more in the app that users try to solve their problems by themself first. I added a issue for that here: https://github.com/bisq-network/bisq/issues/3801

**Comment by MwithM** [comment]
If we want to prevent future trades, seller should have min-max values too instead of a fixed value. This way, if buyer as maker expects high volatility, she can protect herself.

I propose 15% min & default, 50% max.

**Comment by user141718** [comment]
While security deposits is needed mainly to avoid spam, also keep in mind that high security deposits is not very forgiving when a party cannon accomplish the trade protocol by some legitimate reason like sickness, accidents, death and other unpredictable events. This creates a harsh and non foreseeable environment and can repel from on-boarding. But this may be more of an issue with the trade protocol.

**Comment by chimp1984** [comment]
> While security deposits is needed mainly to avoid spam,

No, that is not the reason for the sec. deposit. To incentivice traders to follow the protocol is the reason.

> cannot accomplish the trade protocol by some legitimate reason like sickness, accidents, death or other unpredictable events.

Mediators take such things into account.

**Comment by user718141** [comment]
Not a good idea to stress traders and on-boarding users with high security deposits. Maybe a protocol adjustment where in contrary a trade can be cancelled by each party as far as possible, that is until a payment is confirmed in progress, would minimize the need of raising security deposits. This would also be in the spirit to give the traders as much control of the trade as possible to avoid mediation.

**Comment by user718141** [comment]
Better up... Eliminate the need for security deposits by removing meditation and let the traders settle the trade themselves in a deal (original payout) or no deal (refund), or call for arbitration. Still with 2 of 2 multisig and same arbitration as now. If this is not a new feature then propose it for trade protocol 2.1.

**Comment by user718141** [comment]
> > While security deposits is needed mainly to avoid spam,
> 
> No, that is not the reason for the sec. deposit. To incentivice traders to follow the protocol is the reason.

Yup, meant that in other terms ("spam trade").


_Serious about a trade protocol adjustment package 1) omitting superfluous meditation step 2) making trades lately cancellable 3) **eliminating security deposits**, in all giving traders maximum responsibility and power in simplicity. Not as weird as it first may sound._ :+1:

**Comment by user718141** [comment]
> I don't see much of an asymmetry here. Before the fiat transfer the buyer can default, but will then lose his security deposit. After the fiat transfer the seller can default, but will then lose his security deposit.

How about having trades canecellable by each party for a refund (until transferring due to technical constraints)?

> I suggest simplicity here, i. e. not finetuning the security deposits but having the same for alts and fiat and for buyer and seller.

How about zero deposits for each party (for on-board friendliness and trader responsibility)?

> I would like the situation that mediation and appealing to the refund agent is only needed because of bugs or technical problems. All other problems should be solved by the traders. They can do this, having a communication channel, incentives and the terms written out in the contract.

How about remove meditation (shouldn't be motivated by bugs/tech problems). Arbitration handles soft disputes from bugs/technical problems and hard disputes.


In all, simplicity and good faith will succeed...

**Comment by sqrrm** [comment]
With https://github.com/bisq-network/bisq/pull/3826 this is now implemented with the values in https://github.com/bisq-network/proposals/issues/155#issuecomment-566760775

**Comment by mpolavieja** [comment]
@taxd Do you agree to close this proposal as approved?

**Comment by mpolavieja** [comment]
Closed as approved
