### ISSUE TITLE
Redirect #bitsquare to #bisq

### ISSUE THREAD

**Issue by mrosseel** [bisq-network/proposals#16]
The topic message of #bitsquare has now been saying for a few months that we will move to #bisq, and a fair number of people have done so already.
Now is the time to do the actual move.

Goal: activate redirection of #bitsquare to #bisq at the end of this month: 30/04/2018

Necessary actions:
https://epir.at/2016/06/26/redirecting-freenode-channels/

Issue:
Only the channel creator can perform these commands, so I will need the help of @ManfredKarrer 

Proposal:
I propose that Manfred agrees to this transition + its date by commenting on this issue, and I will ping him at the end of the month to actually perform the redirection. 
In the meantime the topic of #bitsquare should mention the actual redirect date.

**Comment by ManfredKarrer** [comment]
I did 
/msg ChanServ SET #bitsquare GUARD ON
and 
/mode #bitsquare +if #2 
If I enter a test msg at #bitsquare it is not shown in #bisq. Shoudn't that be forwarded?

**Comment by ManfredKarrer** [comment]
And now after a restart of the IRC client I cannot access #bitsquare anymore ;-(

**Comment by mrosseel** [comment]
Did you try the undo command?

**Comment by ManfredKarrer** [comment]
Yes did not work

**Comment by mrosseel** [comment]
The proposal did not include actually running the commands (was going to test it first on a test channel) but maybe I should have stated that more clearly.

In any case, when I do ```/msg chanserv info #bitsquare``` I can see the following information:
```
14:49:21] -ChanServ-	Information on #bitsquare:
[14:49:21] -ChanServ-	Founder    : mkarrer
[14:49:21] -ChanServ-	Registered : Jun 25 10:40:52 2014 (3y 42w 2d ago)
[14:49:21] -ChanServ-	Last used  : Apr 14 20:30:13 2018 (1d 16h 19m 8s ago)
[14:49:21] -ChanServ-	Mode lock  : -n
[14:49:21] -ChanServ-	Flags      : GUARD
[14:49:21] -ChanServ-	*** End of Info ***
```

The only difference with the same info on #bisq is the GUARD flag, so could you try:
```/msg ChanServ SET #channel GUARD ON```

Reference page, list of channel modes: https://freenode.net/kb/answer/channelmodes

**Comment by ManfredKarrer** [comment]
I cannot log in anymore in #bitsquare. Tried the command but does not change anything.

**Comment by cbeams** [comment]
A few things on this proposal, with the newly published docs.bisq.network/proposals.html in mind:

This is probably a good example of something that was too small / low-level to merit a proposal. I imagine that everyone involved with Bisq's presence on Freenode on a regular basis, i.e. those in #chat-bridge, those with `op` status could have come to a consensus about this and just made the change.

As Mike mentioned above, work on a proposal should never get done within the proposal issue itself. Proposals are just about getting to a rough consensus about whether to proceed with a given change. The fact that Manfred was so quick to "just do this" (and that it could so quickly be done) is probably more evidence that this didn't merit a proposal in the first place.

I'm saying all of this in hindsight, now having written the document above, which was informed heavily by seeing this and other kinds of proposals going by over the last weeks. So there's nothing wrong here at all. I just want to call these things out so we get a shared sense of what fits in proposals and what should go elsewhere.

One problem in the case of Freenode / #chat-bridge is that there's actually no other good place to put an issue like this, because there is no, e.g. bisq-network/freenode or bisq-network/irc repository. That is intentional, because I figured we just don't have enough need for one to merit the trouble. We can always create one if it does seem necessary, but in the meantime, I'd say just make decisions in Slack.

For issues that don't fit anywhere else, or that people aren't sure where they should go, I've also been thinking about telling people to create issues in bisq-network/bisq, and that we can then "route" the issue to the correct repository from there. Not sure if that makes sense, but thought I'd mention it.

Anyway, it looks like the changes proposed here have already been executed (even though they may have failed). As such, I'm closing this as essentially 'accepted'. Thanks all.
