### ISSUE TITLE
List new Confidential Asset L-BTC pegged 1:1 to BTC on Liquid

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#169]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

## Background

Liquid is a federated sidechain pegged to the Bitcoin blockchain, featuring Confidential Transactions (CT) and Confidential Assets (CA). One of the Confidential Assets issued on Liquid is L-BTC which is a fully verifiable 1:1 backed BTC token. The federation members of Liquid include Blockstream, Bitfinex, BitMEX, and many other reputable Bitcoin exchanges and infrastructure providers.

## Summary

While [listing new assets on Bisq is currently on hold](https://github.com/bisq-network/proposals/issues/166) due to the excess Shitcoinery problem we are facing, I feel an exception should be made to list L-BTC as a new asset in Bisq for its privacy use cases, since L-BTC is pegged 1:1 to BTC.

Since the Liquid federation has 100% cryptographically verifiable BTC backed holdings for the 1:1 peg, the risk of “printing money” inflation or other Shitcoinery related issues is quite low. For example, Bisq users will be able trade (or peg-in) BTC for L-BTC, do some CT transactions on the Liquid blockchain, and later trade (or peg-out) the L-BTC for BTC, all without the risk of exchange rate fluctuation between L-BTC and BTC.

**Bisq users will essentially be able to mix their coins with all of Liquid federation BTC holdings.**

## Verification

Since the Liquid blockchain has Confidential Transactions, it is not possible for a Bisq mediator or arbitrator to verify a trade has taken place, unless the Blinding Key is disclosed by the L-BTC seller. The [full documentation has all the details](https://docs.blockstream.com/liquid/developer-guide/confidential-transactions.html?highlight=blinding%20key), but this shouldn’t be an issue for Bisq trading.

## Proposal

* Exempt L-BTC from the current Bisq policy of putting new asset listings on hold
* Waive application fee, if any exists
* Merge PR to add L-BTC into Bisq

**Comment by FKrauss** [comment]
2 questions:

1) How would pricing work in this case? 0.999 L-BTC/BTC  (0.1% "mixing fee")?  what price feed do you think we should use? Or even, would you lock the price at 1:1? 

2) would L-BTC be listed as an alt-coin? even though it is a sidechain? - seems like a no brainer for me. Just wondering if you thought of something else

**Comment by wiz** [comment]
This would just add L-BTC as another crypto asset in Bisq, and the free market would decide the price. Since it's a no risk 1:1 peg I assume the spread will be quite small but volume might be high, which is good for both Bisq users and Bisq DAO.

**Comment by FKrauss** [comment]
Then the pricefeed will be Bisq itself, like it is with BSQ. 

Cool, makes it even simpler

**Comment by mpolavieja** [comment]
> Then the pricefeed will be Bisq itself

Using Bisq as pricefeed would make unfeasible to send orders with a dynamic price  at a specific percentage above or below an average price, as that Bisq price could be easily gamed by an attacker through self-trades.   Having these orders is important as it increases the liquidity of the order book by allowing users to leave their orders unattended.

**Comment by wiz** [comment]
Uh guys, there is no need for any pricefeed - the asset has a 1:1 peg to Bitcoin lol
We will just use fixed price offers, i.e. I'll trade you 0.999 BTC for 1.000 L-BTC

**Comment by mpolavieja** [comment]
> Uh guys, there is no need for any pricefeed

True, I don´t know why I was thinking of L-BTC trading against fiat, which will not be the case.

**Comment by MwithM** [comment]
If we have a good asset listing policy, we won't have to arbitrarily waive some assets.
If Bisq have asset listing on hold, we have to deal with that first.

PS: Liquid should be added to Bisq. But if we want the DAO to have some credibility, we have to wait a little.

**Comment by objectorange** [comment]
Would supporting Liquid attract traders to Bisq?

**Comment by FKrauss** [comment]
I guess so. It would be the easiest way to "coinjoin". Even easier than
trading in and out of XMR

**Comment by FKrauss** [comment]
Certainly easier UX wise and potentially cheaper fee wise

**Comment by sqrrm** [comment]
The listing fee has to be paid by someone, but it's 30 BSQ for a 30 day window minimum so not a big deal.

@wiz please don't send proposals to DAO voting when there is an agreement already. There is a quite clear support for this outside of voting through the client so there is no need to put that extra burden on voters.

**Comment by wiz** [comment]
> @wiz please don't send proposals to DAO voting when there is an agreement already

I wouldn't normally, but since @chimp1984 called a DAO vote to "put new asset listings on hold" in this same cycle, I wanted a DAO vote to specifically exempt L-BTC from that policy to clarify the intention of the DAO stakeholders. Also if the shitcoiner trolls :-1: this GitHub proposal, the DAO vote would protect against that attack as well.

**Comment by chimp1984** [comment]
> Maintainers have the freedom to add any asset if they consider it interesting but by default no new assets get added to Bisq until we have sufficient resources to deal with it.
(https://github.com/bisq-network/proposals/issues/166)

I think the most efficient way to deal with that mess and energy and attention waste with altcoin is to block all but give maintainers the right to pick whatever they want. As they have proofen their merity with thier long term contribution we can assume they will be smart enought to pick interesting coins if those pop up (like Liquid assets).

**Comment by chimp1984** [comment]
I support to add L-BTC but I don't think its a good idea to start voting on adding assets as it would lead to spam from asset operators. 
It was intentional in the DAO design to use the remove asset feature to filter out 100% clear scams only and not do any interpretation for any other assets if they are good or bad as that would cost too much effort and cause too much communication (as he got the proof over the past weeks). For not traded assets we have the filter mechanism in place so they are not visible anyway.

So i feel conflicted here how to vote, as I dont think its s good idea to vote on such subjects but don't want to signal that I don't support L-BTC. So as a imperfect solution I will support it in DAO voting but want to emphasise that we should not continue that strategy.

**Comment by ripcurlx** [comment]
I also think it is not necessary to put it for a vote as mentioned by @chimp1984. I as a maintainer am happy to merge any PR that integrates this asset. The only drawback letting a maintainer decide is that maintainers might get spammed by asset merge requests on every channel.

**Comment by cbeams** [comment]
At the risk of being repetitive, I'll just weigh in here saying that this is a good example of a proposal where we have broad (indeed unanimous) consensus on a proposal, so there is no need to go to a DAO vote.

We want to put things to a formal vote as infrequently as possible. The ideal number of DAO votes on proposals (other than parameter changes) is zero. Only when we are truly at an impasse, where there are two or more options on the table that have been thoughtfully discussed and cannot be reconciled, should anything like this go to a vote. Voting on anything contentious creates losers and likely resentments. Getting to rough consensus by making good arguments, thoughtfully disagreeing, etc builds respect, cohesion and harmony. I talked with Wiz about this the other day and he understands and agrees; I just want to re-iterate it here because we could probably all use a refresher on this principle.

**Comment by ifarnung** [comment]
Just want to chime in that this could be an amazing asset listing for BISQ and due to the 1:1 peg (market makers don't need to hedge price volatility) , it could generate a **LOT** of volume. Seems like a very good way to move BTC through a privacy filter at a very low price volatility risk.  Great suggestion!!

**Comment by objectorange** [comment]
Completely agree with cbeams. Voting should really never be required so long as people speak up about their concerns, respect each other's space to discuss, and give room for a consensus to happen that's IAW Bisq's mission. Truly great to hear this from others.

**Comment by chimp1984** [comment]
> The only drawback letting a maintainer decide is that maintainers might get spammed by asset merge requests on every channel.

I would suggest to make it very clear that any sort of "advertising" is not welcome and will lead to ban such users.

**Comment by mpolavieja** [comment]
Approved on DAO voting - cycle 9
