### ISSUE TITLE
Adjust BSQ trading fees each cycle to be 60% of BTC trading fees using 30 day average

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#173]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Currently at the start of each DAO cycle, the compensation rate is fixed to something like this:
> BSQ rate for Cycle 10 is 0.67 USD per 1 BSQ

I propose that we enact a new policy to adjust the BSQ maker/taker fees each cycle in a similar fashion, so that they are adjusted to always be 60% of the BTC maker/taker fees, based on the 30 day average BSQ/BTC trading price from the last cycle.

Currently, the DAO trading fees parameters are set as follows:
```
BTC Maker: 0.002 BTC
BTC Taker: 0.006 BTC
BSQ Maker: 10 BSQ
BSQ Taker: 30 BSQ
```

Based on 60% pricing, this represents a BSQ valuation of 12K sats
```
0.002 BTC / 10 BSQ * 60% = 0.00012000 BTC/BSQ
```

Using the most recent 30 days average BSQ/BTC trade price of 5991 BSQ/BTC, this means we should increase the BSQ trading fees as follows to maintain a 60% pricing:
```
Maker: 0.002 BTC / 0.00005991 BTC/BSQ * 60% = 20.03 BSQ
Taker: 0.006 BTC / 0.00005991 BTC/BSQ * 60% = 60.09 BSQ
```

Therefore, the first DAO parameters to change from this proposal will be:
```
BSQ Maker fee: 20.03 BSQ
BSQ Taker fee: 60.09 BSQ
```

If approved I will make a proposal each DAO cycle in a similar fashion. For starters, this will likely double the BSQ burned from trading fees compared to last cycle (assuming same trading volume), and greatly help the DAO return to profitability.

What do you guys think?

**Comment by MwithM** [comment]
This is a way in which users who just trade can benefit from holding BSQ that gains value over time, and it's easy to explain.

**Comment by sqrrm** [comment]
I agree on doing the monthly adjustments. That was the original intent and I think we didn't do it the last few months after experimenting with lowering fees to see if it would drive trading. I haven't done a study on that but my feeling is that it didn't work and that the trading is pretty much uncorrelated to our fees as long as they're kept at a reasonable level.

I do think we should keep the BSQ fee at 50% of the BTC fee though since that's what we have been promoting as the Bisq fees. That is 0.1% maker fee and 0.3% taker fee when paid in BSQ.

**Comment by ifarnung** [comment]
@sqrrm Yeah, I would love to see what the percentage of trades done with BSQ versus BTC is on, for example, a weekly basis.  

To all:
Anecdotally, I am seeing quite a few more small BSQ buys (20-100 BSQs) at these new much lower BSQ prices, which I interpret as the direct incentive being responded to. See image: 
![image](https://user-images.githubusercontent.com/55181240/73068258-df09f680-3ebb-11ea-8479-4031d7e270c4.png)
That's a nice discount on your trading for going through the trouble of buying BSQ from contributors.
To me, this (hopefully)**temporary** discount is a nice benefit for BISQ users and incentivizes people to buy BSQs both for near-term trades and maybe for some future trades as this BSQ weakness may not last forever.  A simple case of more demand eating up more contributor BSQ, IMO.

**Comment by huey735** [comment]
Can't this be more... dynamic? Can't the BSQ maker/taker fee be automatically updated in function of the BTC/BSQ price average? And only have the percentage updated when needed through proposals?

**Comment by sqrrm** [comment]
@huey735 The problem is that for it to be dynamic you need a distributed source of BTC/BSQ price. This might not be impossible since BSQ is colored BTC, but that would only work after we have atomic swaps for the BTC/BSQ trading. That's something we could probably do reasonably easy and perhaps it should be prioritized to get more people to use BSQ.

With that price data it would be possible to get an on chain price feed for BSQ and thus it would be possible to create a 30 day average. Problem is that it would be very easy to paint the tape for this feed, just do some big self trades and suddenly the BSQ price is 10 times the market value, and your fee is a 10th of what it should be.

**Comment by flix1** [comment]
Agree with @sqrrm to keep BSQ fees at **50%** compared to BTC. It keeps the discount simple, easy to understand. 

I'm OK with monthly adjustments.

**Comment by sqrrm** [comment]
I notice the proposals to change the parameter in the DAO are already made. They're targeting 60% of BTC fees which I disagree with, but they're fairly close to 50% at the current 30 day average, which is the previously discussed and agreed on discount. I might vote yes on them.

To me it seems counter productive to raise the BSQ fee too much as it's just easier for traders to pay the fee in BTC, adding to the administrative tasks of the burning man and also adding risk for the DAO.

@m52go It would be good to advertise this to users well ahead of time to avoid that sudden jump that took some by surprise last time we doubled the fees.

**Comment by ifarnung** [comment]
yeah, when it was proposed earlier this cycle, the market value of BSQ was well below 5000 sats, and now it's around 7000-8000  sats,  It definitely doesn't make sense to me to double the BSQ fee rate.  I would propose to submit a less aggressive fee change and let the major BSQ holders decide which route they prefer..

**Comment by wiz** [comment]
@sqrrm alright, how about we amend this proposal to be 60% for the next cycle, and 50% after that

**Comment by sqrrm** [comment]
@wiz that would be good. Although I think @ifarnung has a point in doing more moderate changes to the fees. They need to increase of course but we won't balance the budget this cycle anyway so I think focus should be on minimizing the impact on users. Most won't notice it, but it seems unnecessary to alienate those that do. Perhaps just raising them by 50% this cycle would be better, then for the next cycle the increase would be much less than 50% (barring major movements in price). Much more palatable than a >100% increase.

**Comment by MwithM** [comment]
Last time a sudden fee price increase occurred, trading volume was not very affected, but we had very negative media reactions.
I agree with this proposal but changes should be as smooth as possible.

**Comment by wiz** [comment]
> They need to increase of course but we won't balance the budget this cycle anyway

Actually from what I understand, Bisq was actually profitable last month after some burning man net calculations - @m52go did you figure out our net PnL last cycle?

**Comment by m52go** [comment]
```
    UNVERIFIED: { count: 0, feeSum: 0 },
    INVALID: { count: 0, feeSum: 0 },
    GENESIS: { count: 0, feeSum: 0 },
    TRANSFER_BSQ: { count: 165, feeSum: 0 },
    PAY_TRADE_FEE: { count: 2058, feeSum: 6842.3600000000815 },
    PROPOSAL: { count: 21, feeSum: 42 },
    COMPENSATION_REQUEST: { count: 23, feeSum: 46 },
    REIMBURSEMENT_REQUEST: { count: 0, feeSum: 0 },
    BLIND_VOTE: { count: 25, feeSum: 50 },
    VOTE_REVEAL: { count: 24, feeSum: 0 },
    LOCKUP: { count: 1, feeSum: 0 },
    UNLOCK: { count: 1, feeSum: 0 },
    ASSET_LISTING_FEE: { count: 2, feeSum: 395 },
    PROOF_OF_BURN: { count: 7, feeSum: 135210 },
    TOTAL: { count: 2327, feeSum: 142585.36000000156 }
```

Total burned: 142 585
Total issued: 106 536

Supply effect: -36 049

**Comment by wiz** [comment]
@m52go thanks for the PnL numbers, is there any easy way to see this on the website somewhere? I just want to see PnL for every cycle exactly like you said above "supply effect"

**Comment by m52go** [comment]
Short answer: not yet, but I've been automating the process of getting these numbers recently and would like to replace the stats page altogether with more meaningful stats like these soon. Would also remove the need to manually report numbers in blog posts, which is annoying and prone to errors.

**Comment by ripcurlx** [comment]
> @wiz that would be good. Although I think @ifarnung has a point in doing more moderate changes to the fees. They need to increase of course but we won't balance the budget this cycle anyway so I think focus should be on minimizing the impact on users. Most won't notice it, but it seems unnecessary to alienate those that do. Perhaps just raising them by 50% this cycle would be better, then for the next cycle the increase would be much less than 50% (barring major movements in price). Much more palatable than a >100% increase.

As based on the current BSQ price we have reached already a 56% discount for using BSQ I'll reject the parameter change for this cycle, which would decrease the BSQ discount to 11% otherwise.

**Comment by MwithM** [comment]
This proposal is not about current price (8699 BSQ/BTC), but 30 day average (5630 BSQ/BTC), which is a great discount.

Rejecting this proposal because of current price is focusing on low term. Fees and BSQ market are balanced and it doesn't matter if for some time BSQ is not very attractive to pay fees and BTC is relatively more used.

We've been using 90 day average to claim compensation requests and it's working quite well. If you think that using 30 day average is fine, rejecting the current change parameter because it would make BSQ fees too high in the short term looks like cheating to me.

**Comment by sqrrm** [comment]
I have also decided to vote against. Primarily due to the bad press we get by raising fees by 100%. I also think it will make the fee discount for using BSQ over the coming month too low, there need to be a proper discount compared to using BTC for paying fees in my opinion.

@MwithM Using the 30 day average would put the BSQ fee ~13% higher than target whereas using the 90 day average would be ~36% above target fee. Using last trade price would put it at 75% over target, at the time of writing this comment.

**Comment by wiz** [comment]
Okay so it seems the DAO parameter changes will be rejected for this cycle, but I'll make another proposal next cycle using the 60% adjustment as we discussed.

**Comment by MwithM** [comment]
And maybe a 20 or 30% increase limit for each cycle, so it's easier to implement without disturbing traders very much.
