### ISSUE TITLE
Coinigy integration node 

### ISSUE THREAD

**Issue by 4NobleTruths** [bisq-network/proposals#18]
Coinigy is a commercial, subscription-based charting platform, which seems to be the best of the kind for crypto at this point.
[Coinigy](https://www.coinigy.com/)

I and an associate propose to fund an integration with it for the bisq network.

Purpose:
A. Increase liquidity on bisq by:
1. Increasing public awareness among pro crypto traders by making the bisq markets available in their Coinigy interface.
2. Availing pro crypto traders of the ability to use professional charting tools on bisq markets.

My bet is that this will bring more professional, HF traders to bisq, and consequently increase liquidity when they bring arbitration and market maker bots on the emerging trading API.

Proposed actions:
A. Fund the one-time fee to Coinigy for the basic charting integration.
B. Fund, create and operate a persistent bisq and bitcoin node that will supply Coinigy with bisq markets data via websockets.

Please give this issue a thumbsup, if you think this is a worthwhile integration, which would merit BSQ compensation.

Thank you for your attention.

**Comment by 4NobleTruths** [comment]
Since there is already the website at [](https://markets.bisq.network/), and we would use websockets, I suppose we wouldn't even need another node. Right?

Then we would just fund the one-time integration, and apply to do role #9, if that's still unfilled:
[](https://github.com/bisq-network/roles/issues/9)

Does that make more sense?

**Comment by ManfredKarrer** [comment]
Thanks @4NobleTruths for putting up the proposal! 
Could you add rough estimation of the integration costs Coinigy charges?

@dan-da, @mrosseel Could you give feedback regarding API?
@flix1 Any opinion?

**Comment by flix1** [comment]
@ManfredKarrer  I was unfamiliar with Coinigy, but will review it this week and post feedback here.

**Comment by mrosseel** [comment]
@4NobleTruths if the markets website and more specifically the markets api at https://markets.bisq.network/api/  has all information that you need, there is indeed no need for an own Bisq node. You can just write you piece of software interrogating the markets API and serving websockets to coinigy. 

The markets API is of course also open source (written in PHP) so if something is missing you could provide a Pull Request to add extra features.

**Comment by 4NobleTruths** [comment]
@ManfredKarrer I'm waiting to hear from Coinigy on the latest price for the real basic integration.
@mrosseel Thanks, I'm working on getting the API on the VPS node I have, and will start to figure it out from there.

**Comment by cbeams** [comment]
@4NobleTruths, thanks for submitting this. Yes, it probably would make the most sense to do this work against the existing Markets API and to modify it however necessary, instead of standing up a new node type / dedicated API. Is that role (the Markets API + Website maintainer role) something that you are personally able to take on? We can discuss that in more detail on the role issue itself, but it would be good to know if you're able to actually take over that PHP service, and to run the headless Java-based Bisq node that backs it, to redeploy them on the hosting infrastructure of choice and to be fully responsible for them going forward.

Otherwise, just to be clear, you are proposing to do everything necessary to create pay for and maintain a Bisq-Coinigy integration, and to be compensated for those efforts in BSQ, is that correct?

I agree with Manfred it would be good to see what the base costs would be, but in general I'd like to see this too, especially if it means that we breath new maintenance life into our Markets API.

**Comment by cbeams** [comment]
@4NobleTruths, it's been nearly two weeks since you originally submitted this proposal, and it looks like the trail is going cold here. Could you please review the comments above and weigh in about next steps? Otherwise, I'll close this soon per the process documented at https://docs.bisq.network/proposals.html#step-3-evaluate. Thanks.

**Comment by cbeams** [comment]
Closing as stalled. Reopen at will, but if you do so, please take steps to move the ball forward so that this doesn't stall again.

**Comment by 4NobleTruths** [comment]
Sorry we stalled; were preoccupied with something else. 
So, I guess, we don't have the wherewithal or capacity to run the Markets node for now.

Never received an estimate from Coinigy.
So, we'll revisit this when capable.

Thank you all for your time.
