### ISSUE TITLE
Remove Litecoin as base currency

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/proposals#21]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Due to very low trade activity with Litecoin as base currency, I would suggest to remove it as base currency.
The latest trade has been at Feb. 7th. 2018. Currently there are 0 offers and beside the seed nodes only 1 peer online.
I run 2 LTC seed nodes and the arbitrator. To maintain and monitor those takes some effort. Even that effort is not big the close to zero activity does not justify it IMO.

The code base for supporting other base currencies will stay intact only the UI element for selecting another base currency would be removed (as we removed DASH and DOGE for the same reason already). 

To have the option for alternative base currency gives Bisq more resilience but practice has shown that bootstrapping another network is difficult and we don't have the resources to focus on multiple markets beside the BTC market. Also it would partition the user base thus making the market bootstrapping on BTC even harder.

Please comment below if you agree or oppose to that proposal. If we get sufficient feedback and if the proposal gets support I might add the removal to the upcoming 0.7.0 release.

**Comment by cbeams** [comment]
I've been thinking about doing this as well, glad you suggested it. I wonder about keeping the underlying infrastructure in place, though. We don't have to remove it right away, but over time it may become a liability. It adds considerable complexity and now there will be nothing testing or exercising it. It'll be dead code that does nothing but get in the way.

**Comment by sqrrm** [comment]
I agree with removing the support. I also see that there might come a time when we need to re-enable it considering it's less than a year since it was first needed. I would probably keep the infrastructure in place at least for a while.

**Comment by ManfredKarrer** [comment]
Yes lets see how BTC as base currency develops. Miner fees will for sure rise once again to considerable heights and then we might re-consider to go back if we don't have a new off-chain model by then. I hope for the next 1-2 years we are still good with BTC and on-chain transactions.

**Comment by ManfredKarrer** [comment]
The proposal was accepted  by 4 votes and 0 rejections. I is implemented in v0.7.0.

**Comment by HarryMacfinned** [comment]
I have a little suggestion, hopefully not too complicated:
- would it be interesting to store the Litecoin concerned code in a github repo here ? This in order for potentially interested people to be able to put an eye on it
- would it be interesting to open an operator role for running some LTC nodes in order to be able to (re)propose this feature in the future (if there is interest) ?

I make this suggestion because I imagine it was some work to propose that, and it may be sad to have the code just dissapearing and forgotten.
I make this suggestion for the LTC code and nodes, but maybe it would be more appropriate for BCH ?

**Comment by ManfredKarrer** [comment]
The code stays, we just deactivated in the UI the currency selection.

**Comment by cbeams** [comment]
I've added the `was:approved` label to this issue. @ManfredKarrer, technically, only one of the @bisq-network/proposals-maintainers should actually close issues. (You can do this yourself since you're one of the @bisq-network/github-admins, but the best thing in the future would be to @mention the proposals maintainers and ask them to close the issue, so they can double-check everything is in order process-wise, add labels as appropriate, etc. (by the way, I appreciate that you probably did this on my behalf because of my recent health issues. Just mentioning it here all the same for completeness).
