### ISSUE TITLE
@burningman3 to take over Donation Address Owner role

### ISSUE THREAD

**Issue by burningman3** [bisq-network/proposals#221]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I would like to request to take over the Bisq donation address.

I will continue in the same way as the current burning man. I will set up a bond now but do not change the donation address until the next cycle. I have discussed this with burningman2.

I will request 1000 BSQ per month for compensating my time for trading/burning/reporting if I get accepted. This covers also the included risks (BSQ bond, trade mistakes,...).

The reason to trust me is the same as for the current burning man.
- I have to set up the 50 000 BSQ bond
- Only if some major stakeholders will accept me in DAO voting I can become the "burning man" - I will reveal my identity to some Bisq core contributors (who might up-vote me then in DAO voting), but I prefer to keep my anonymity to the public.
- Do not vote or reject my proposal if you don't trust me

**Comment by burningman2** [comment]
I confirm that we agreed to re-use the address for @burningman3.  The reason is that traders (buyers) who have disabled the DAO would reject sellers (at address verification) as the new address has to be added to the release (hardcoded) in case the users is not using the DAO (its only visible for DAO enabled nodes). Even after the next release it might take a bit until most users have updated to make sure that nearly no trades will fail because of that. A failed trade would result in lost trade fee for both buyer and seller.

So the process will be that we add @burningman3's new address to the list of hardcoded addresses for verification, then wait some time until most users have updated and then @burningman3 will make a DAO param change request with his new address. In the meantime he will get the private key of my current address so he can use that.

**Comment by cbeams** [comment]
While we're on the topic of donation addresses, @burningman2, do you see any issue with separating into two addresses, one for arbitration payouts and one for trading fees paid in BTC? This would make accounting easier.

**Comment by sqrrm** [comment]
I think separating the addresses might not be that easy unless we hard code the addresses. I'm not keen on adding another DAO parameter due to the risks of issues with the DAO, even though I agree that it would be a reasonable separation. In a way it will be quite separated for a while at least with the fees going to the victims of the theft, but that's not a great solution since it depends on the filter.

**Comment by cbeams** [comment]
I've updated the title to follow common convention. /cc #bisq-network/roles#80.

**Comment by burningman3** [comment]
Bonded role proposal.
Tx ID: 973f38f8fb7869d6d54783a5568937a79df5addaab0c0b5d1a2f8e4daab1812e

**Comment by cbeams** [comment]
Closing as approved in Cycle 13 DAO voting; @burningman3 has been assigned to own https://github.com/bisq-network/roles/issues/80 accordingly.
