### ISSUE TITLE
Migrate the Bisq Markets API service to the bisq.market domain name

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#229]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Currently the Bisq Markets API is served from markets.bisq.network which is owned by the Bisq Domain Name Owner. Following up from the spirit of proposal #211, I feel we should migrate the Bisq Markets API service to its own domain name to improve decentralization. I feel `bisq.market` would be best for this.

As the Bisq Markets API Operator, I propose to take ownership of the `bisq.market` domain name, and use that for the new primary FQDN hostname to serve these API requests. The old hostnames would become CNAMEs of the new hostname.

**Comment by wiz** [comment]
@cbeams can we make a decision about this before you leave?

**Comment by cbeams** [comment]
I don't have a strong opinion about it. I will continue to own the DNS Admin role for some time to come; if there is consensus to make this change, I'll be happy to update the current markets.bisq.network record to a CNAME appropriately. Please just make sure to have everything fully set up and tested, e.g. changes made to the JavaScript on the https://bisq.network/markets page, etc before requesting the CNAME change. I'm not sure this change is really worth it in the end, when considering that it's another domain name that someone (you) will have to maintain and renew regularly, and therefore could break. But again, I don't feel strongly about it. Please also make sure to update the duties section of the Markets API operator/maintainer role to indicate that ownership and renewal of this domain is part of the job.

**Comment by m52go** [comment]
On the surface, moving markets.bisq.network to bisq.market doesn't seem like such a big deal.

In the medium and longer terms, a revamped markets site (perhaps with statistics on trading, DAO, etc) may allow for:

- simplified bisq.network site (i.e., no need for markets page), which will be important as more translations become more necessary
- decentralized control of Bisq's web presence
- an additional web property (and entry point) to the world of Bisq

None of the above have been proposed yet, but because of the the possibilities it enables, this change seems like a step in the right direction.

**Comment by wiz** [comment]
Yeah, and after we migrate all the services off *.bisq.network domain name, @m52go can take ownership of that as part of his bonded Website Operator role, and we can eliminate the Domain Name Owner and DNS Admin roles.

**Comment by wiz** [comment]
Closing as approved in DAO voting cycle 15, I will contact the Domain Name Owner and follow up with a full project proposal for this migration.

**Comment by wiz** [comment]
Project proposal posted at https://github.com/bisq-network/projects/issues/41
