### ISSUE TITLE
Allow trader negotiation of disputed BTC payout

### ISSUE THREAD

**Issue by jmacxx** [bisq-network/proposals#234]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

When something goes wrong in a trade, users must resort to mediation which involves a third-party suggesting how the BTC collateral should be distributed.  The mediator has the tools to build a transaction which the users then sign to accept and make the payout happen.  If one user disagrees they are forced to wait for arbitration.

**Bisq should enable traders to negotiate the disputed payout between themselves.**  Since they are the sole owners of the 2-2 multisig they could do this anyway, but there exist no tools to let then collaborate in such a way.

Adding a simple form to trader chat would make it easy to interact.  One user could propose a suggested payout split to the other, which could then be approved or counter-proposed.  This process could repeat until an agreement is made.  The form could include some commonly-used payout suggestions the same way that the mediation GUI does, along with fields for custom payout amounts.  Once both parties agree to a propsal they sign and the seller broadcasts the payout Tx.

This should be considered an advanced feature and should have appropriate warnings about the ability to get scammed?  ("*if you are unsure about anything, choose Mediation*").

Mediation will continue to be an option for either party at any time.  Likewise with Arbitration, if they want to wait the 10 or 20 day timelock period.

Ideas leading to this proposal came from the discussions [here](https://github.com/bisq-network/proposals/issues/220), and [here](https://github.com/bisq-network/proposals/issues/233), and [here](https://github.com/bisq-network/bisq/issues/4340).

---

### Example:

![image](https://user-images.githubusercontent.com/47253594/86548773-38faf780-bf03-11ea-84a0-daeb112b89bf.png)

**Comment by MwithM** [comment]
I think that this proposal adds more complexity to the dispute process, which already has three layers and is difficult to understand for new and intermediate users. Bisq was hesitant to include the trading chat because of risk for scamming and social engineering, and that's why heavy rules are introduced in the trading chat. Also, that a lot of trades that end up in arbitration are because of unresponsive traders. I don't think this would avoid that.
Traders can negotiate a mediation output between themselves at the trading chat (just like they do now to cancel a trade), and then expose that output to the mediator. Maybe just including at the wiki/documentation that traders can also demand mediators a specific suggested agreement is enough.

**Comment by sqrrm** [comment]
I'm not convinced that adding too much complexity here is a good idea. Most traders will not have a good grasp of the trade protocol and it's likely to add more confusion.

@jmacxx I think you were on the right track in https://github.com/bisq-network/bisq/issues/4340 with a cancel button feature. I would frame the cancel something like:
##### Cancel options
1. Cancel and recover 25% of deposit
2. Take to mediation expect to receive 10% of deposit (get less back for wasting mediator time, still need to give some back as an incentive to accept the payout)

##### Accept cancel request options
1. Accept cancel request, receive 75% of counterpartys deposit
2. Take to mediation instead of accepting cancel request, expect to get none of counterpartys deposit (for wasting mediator time)

#### Conflicting incentives
There is a problem however that adding this kind of cancel feature makes the options pricing cheaper than the initial full deposit since using the cancel is now part of the trade protocol. Properly priced, deposits would increase.

**Comment by MwithM** [comment]
Superseeded by project 39.
