### ISSUE TITLE
Concerning the refund agent system

### ISSUE THREAD

**Issue by RefundAgent** [bisq-network/proposals#236]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I am not sure if this is a proposal or not, but I decided to publish is here:

The present refund agent system must be changed. I suggest the following.

- Large payouts are left to reimbursement requests. This strongly decreases the risk and strain on the refund agent(s). The refund agent simply tells the traders that they need to do a reimbursement request with a link to an explanation, and leaves the case open. The software should be modified such that these cases can be closed without payout.

-  Mediators comment on the reimbursement requests such that the stakeholders easily can make a decision.
There has so far been no case where the mediators made any mistake. It will happen, but it will be very rare. A dedicated section on GitHub is made for these types of reimbursement requests, for easy overview.

-  A few refund agents are found that handle the majority of cases which are the small ones. These refund agents do 
not need to have a large capital, 0.2 BTC should be enough. Of the last 21 cases there have been three where
the refund was larger than 0.1 BTC. There are presently about twenty cases/month which might decrease from now on, given the more adequate security deposits now implemented.  This is not clear though, since there are many cases of disputes with a trade value of 0.01 BTC, security deposit of 0.006 BTC (60%) where one trader nevertheless abandons the trade. Three refund agents will, as it is now, get about two cases/week which can easily be handled. The job is certainly not hard.

-  The reports should be made similar to what I do right now but things can be improved. The collateral tx shows that the funds have been paid to the donation address. I don't know how the payout tx is generated but it should be possible to link the payout tx to the collateral tx showing that the payout was done to the correct traders. Maybe some development work is needed here. If Bisq scales it will be necessary to minimise the scam possibilities (such as paying to their own addresses) of refund agents. Right now the Burningman checks my reports and any help he can get will be good.

I will from now on leave large cases to reimbursement and my plan to retire from this role remains. 

Please add any improvements you can think of. Mediation and refunding is at the interface of computers and humans and is very tricky to get working correctly.

**Comment by wiz** [comment]
I still feel we should bring back a form of optional arbitration. Without any Arbitration system, Bisq traders will be required to wait up to 2 months to get their BSQ for reimbursement, and then they will have to sell that BSQ on the open market, potentially at a huge loss, to recoup their trade capital. It is not an acceptable user experience, and trade volume will decrease further.

**Comment by clearwater-trust** [comment]
I like this proposal.  However, the problem remains.

How does this eliminate the need to review ALL OF THE REIMBURSEMENT REQUESTS to correct "clerical" errors?

How can we eliminate the "error" of double charging the DAO like you attempted to do?
Do we have to pay somebody like wiz to birddog the reimbursement requests? 
How do we make it better?

**Comment by wiz** [comment]
> Do we have to pay somebody like wiz to birddog the reimbursement requests?

Well that's what the role of the Refund Agent is currently doing... but since nobody is really incentivized to do this job and risk their own capital, nobody wants to do it, so that's why the role is being phased out...

**Comment by clearwater-trust** [comment]
> that's what the role of the Refund Agent is currently doing

I'm glad you have accepted the birddog role. Thank you for your service to the DAO. 

We should attempt to phase out any birddog roles. Nobody has time to check a long list of TXIDs against a refund agent report. Do you check all of the TXID lists for correctness?

**Comment by QuantumRipple** [comment]
I think a new timelock destination address owner+arbitration role to handle failed trades only would mostly solve this. The associated "donation" address would not be the same as the existing ones, and there could be more than one of these roles to handle different size categories of trade with different bond size and compensation as each size would be prone to a different degree trust and number of cases.

Reimbursement would be funded directly by the timelock transaction used by the failed trade. Large trade reimbursement no longer involves personal risk or a convoluted BTC->BSQ->BTC path. The prevailing trader would not have to deal with a delayed or volatile reimbursement and double payout should be impossible with the client/protocol changes detailed below.

Incoming transactions remain in situ for some [time period] after receipt (say ~1 week in block confirmations). Participants of a failed trade have [time period] time to open an arbitration case and cause the associated on-hold BTC to be moved to an open arbitration case address. If [time period] elapsed without a case being opened, the BTC would be sent to the normal donation address (where it would be involved in multiple transactions to convert to BSQ and burn). If a case was not opened within [time period] traders would have to appeal to the DAO for reimbursement.

All funds sent to the incoming address would be forwarded on to 1 of 2 addresses - the normal donation address (between [time period] confirmations and another limit specified by the role such as a further 2 weeks) or an "open arbitration cases" wallet address (before [time period] confirmations).

An external observer could easily check that this rule was being followed in an automated fashion: the balance of the incoming address calculated with only incoming tx exceeding [time period] confirmations that were not referenced by outgoing tx (made while the associated incoming tx was < [time period] confirmations) to the open cases address should regularly drop to precisely 0.

Double reimbursement would be impossible because the reimbursement wallet could only be funded from a reserved transaction matching the arbitration case validated against the last [time period] blocks, and payout/closure of the arbitration case would return un-reimbursed funds to the normal donation address.

This would also limit the opportunity for embezzlement even with no/minimal oversight. Such a role's  compensation would only be time spent for duties performed, as reimbursement is funded directly by the failed trades. Furthermore, trader funds could not be absconded with without triggering complaints to the other DAO participants (and likely a manual audit). As such, the only funds really available to be stolen without immediately triggering flags would be the un-reimbursed portion of each arbitration case, most of which would otherwise return to the bonded role anyway as compensation.

**Comment by MwithM** [comment]
Superseeded by project: https://github.com/bisq-network/projects/issues/39
