### ISSUE TITLE
Reinstate BCH as a listed altcoin

### ISSUE THREAD

**Issue by QuantumRipple** [bisq-network/proposals#240]
Reinstate BCH as a listed altcoin, invalidating #61. Even at the time it was removed, it was 3rd place altcoin on Bisq in terms of BTC trade volume, 2nd in trade count. The option to trade all of the top few altcoins should be available to maximize exchange volume/DAO revenue. This would be an exception to #166 - asset listing was put on hold to avoid investing resources in coins that have no volume and BCH has a proven track record of volume on Bisq.

> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

**Comment by cd2357** [comment]
FYI: Bisq is open source. You can always just fork it and support BCH there.

**Comment by QuantumRipple** [comment]
@cd2357 that's a disingenuous argument and you know it.
As a developer, I have time to submit the occasional bugfix and reintegrate BCH support. I don't have time to maintain the whole project.
As a user I simply wish to be able to trade all the cryptos I use on a daily basis in one place. Support for one altcoin or another is not suitable justification for splitting a community that is small to begin with and not growing. Unfortunately, even with a DAO, it seems impossible to leave politics at the door and focus on making a better product.

**Comment by cd2357** [comment]
@QuantumRipple Its sometimes hard to tell if someone is trolling, or asking an honest question.

Available time and effort is limited, and this is important work (not just some trading app).

So I just assumed you were trolling, maybe I was wrong.

Either way, I suggest you look a bit deeper into it and decide if you really want to trade (or rather hold), and would you rather hold BCH or BTC.

Good luck and may the best ideas win.

**Comment by darkbluelight** [comment]
To me and many others it seems so ridiculous, the Bisq devs are talking about their high priority goal "liquidity" and "growing the userbase" but they completely neglect the number one reason why almost no one is using Bisq: The high fees of BTC. Since they removed support for BCH, Bisq got nowhere and never will if they stay blind. The Bisq volume now is at around 5-10 BTC per day. While on centralised exchanges the daily volume is around 2 mio BTC... (https://coinmarketcap.com/currencies/bitcoin/markets). Bisq will stay completely irrelevant in the exchange world with BTC as a base layer.

It actually makes me really sad. Bisq would still be my preferred way to trade, IF it was economically at least somewhat competitive to do so, but it is not by a looong shot.

**Comment by MwithM** [comment]
Closed as rejected in Cycle 15 vote.
