### ISSUE TITLE
Automatic renewal of taken offers

### ISSUE THREAD

**Issue by RefundAgent** [bisq-network/proposals#242]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

There are now proposals to automatically confirm receipt of XMR (#239, in development by chimp1984 and wiz) as well as of atomic swaps BTC-BSQ (in development by sqrrm) which will speed up the trading. There may in the future be implementations to automatically confirm receipt of other altcoins also.
It would be very helpful in these cases for traders to have an option of automatic renewal of their sell-offers in case one is taken. This will make trading almost automatic and fulfil most of the wishes of market makers. The increase in trading speed will be very large and probably increase the trading volume on Bisq. This proposal will not eliminate the need for an API, but will complement it.

I thus propose that autoconfirm-enabled offers can automatically be renewed in case it has been taken. A userdefined limit of the number of renewals should exist.

The implementation should be fairly straightforward since no communication with peers is required.

**Comment by ripcurlx** [comment]
Just to ensure I understand the desired functionality correctly. As soon as an offer is taken a new offer should be created with the exact same configuration.

Some considerations:
- BSQ or BTC wallets has to be sufficiently funded to pay trading and mining fees otherwise this will fail. We probably can roughly check this based on the current fees and number of max renewals on offer creation, but it will be only a very rough estimation.

Shouldn't be too complicated to implement.

**Comment by RefundAgent** [comment]
@ripcurlx Yes, the simplest version is to create a new offer with the same exact configuration. A rough check that the wallets have enough funding should be enough, and anyhow the trader should make sure the wallets are fully funded.

For the BSQ-BTC atomic swaps one can also have automatic taking of offers given certain criteria (price, amount).

**Comment by MwithM** [comment]
Closed as stalled
