### ISSUE TITLE
Market price feed aggregator

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/proposals#26]
## Overview
We use BitcoinAverage for Fiat market prices and Poloniex and CoinMarketCap for altcoin market prices. The price data are requested by the price-nodes from those services and Bisq nodes are requesting via http over Tor the price data from our price-nodes.

## Problem
We have an open vulnerability for single point of failure in case BitcoinAverage would fail (happens once in the past) as most Bisq offers are using percentage based prices and therefore are dependent on price data. 
To a lower extent that is the same for altcoin prices but as we have 2 service providers (Poloniex and CoinMarketCap) it has already a bit more resilience.
Furthermore it comes with a security risk as in case the price provider would deliver wrong data, price based Bisq offers would be taken with that wrong price.

## Goal
We would like to have more resilience for those price feeds, so in case one of the services fail or deliver incorrect data the Bisq users are not affected.
It is not intended to offer that service outside of the context of Bisq.

## Proposal
We should implement basically our own lightweight version of BitcoinAverage. Collect price data from the top 5 exchanges and apply a similar weighting algorithm as used in BitcoinAverage on each of the sources to get an average price. 
Use national currency exchange rates to convert it to other currencies. 
We should try to get in that way a similar result to what BitcoinAverage delivers and then we could mix both services to get the price for Bisq users. If one of the sources deliver very different prices it should be filtered out and the maintainers should get alerted to investigate the issue.
For altcoins we could do something similar or find 1 or 2 other price providers so we get more resilience.  

## Implementation
The service could be added to the price-nodes or run as separate service and the price-nodes consumes that service (could be on the same host machine). 
It does not require special Bisq or P2P network knowledge so it should be easier to find a developer who can work on that.

**Comment by AdriaanJoubert** [comment]
Even more resilient would be to use median instead of average price, e.g. if you have 5 sources for price and 1 gives wrong price, median will not be effective, but average will. So you get the benefit of getting a price that is very representative of the average market price but is not vulnerable to one or two outliers.

**Comment by cadayton** [comment]
Always good to remove single points of failure.  I'd say go for it.  I always like to compare BitcoinAverage to say CoinMarketCap when outputting data.  Serveral months ago there was about a $100 difference but recently they are fairly close to each other.

**Comment by HarryMacfinned** [comment]
I see at least 2 ways to achieve such a service (… with not the same cost).
How much do you think the bounty would/could be for that ?

**Comment by ManfredKarrer** [comment]
@HarryMacfinned 
Hm.... its always hard to estimate. Best would be to start with a detail concept/tech spec and see that as first bounty. If that gets approved its easier to estimate effort.

For a tech spec I would agree to about 500-1000 BSQ. 
But its the stakeholders who vote on it in the compensation request who decide at the end. But maybe others can post their opinions so its easier to get an idea....

**Comment by cbeams** [comment]
I've been slow in responding to this proposal, my apologies.

I would not want to see a new service developed. I'd want to see capabilities added to the existing bisq-pricenode service (one of the options @ManfredKarrer suggests above).

It's true that our reliance on BitcoinAverage and the other services are technically single points of failure and it would definitely be good to eliminate that, but I also don't see it as terribly high priority. If something catastrophic happened (BitcoinAverage goes down, gets hacked, whatever), we could mitigate it and redeploy a patched pricenode within a day.

In any case, I would happily work with an experienced Java developer to show them around the pricenode app, find the right approach to implementing these changes, and then let them on their own to implement a PR.

This feels more like a bounty issue for the pricenode than a net new proposal per se. We've gotten very little feedback on this proposal, and I wonder if that's why. It's kind of "down in the weeds". Anyway, even though per the proposals process this should have been closed one way or another a long time ago (my bad), I'll leave this open a bit longer to get any additional feedback.

**Comment by HarryMacfinned** [comment]
I have also been slow on this proposal and I apologize for that. 
I did not at all forget this task and it is still in my objectives, but since I'm already slow on the rest (and occupied with other tasks) it gets delayed in my agenda. (Hot days have also a bad effect on my productivity).
imo it doesn't matter the task being here or there, the point is that we do not forget it.

I'm a bit technically curious about how _we could redeploy a patched pricenode within a day_ ?

If this is indeed doable so rapidly ... then it seems the present task has little reason to exist.

**Comment by wiz** [comment]
This seems like an important issue to fix, as well as the mempool fees estimator API from https://mempool.space/api/v1/fees/recommended

**Comment by chimp1984** [comment]
> It looks to me that this would be easy to pick up by a new developer, as there is no need to know about Bisq codebase.

Agree. But we need to be careful to be on the conservative side. We had often troubles when fees where going up fast the fee estimations did not reflect that good enough and led to stuck txs. So if anyone works on that would be good to check past behaviour and if we use a new model to be careful with fading in new model.

**Comment by mpolavieja** [comment]
Closed as stalled.  This discussion has moved to proposal #163
