### ISSUE TITLE
Increase unsigned account limits from .01 to .05

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#274]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Even after adding SegWit into the trade protocol, a 140 vByte native SegWit transaction currently costs around $5 USD with the high Bitcoin network fees. If a Bisq trade requires 4 on-chain transactions, this means each Bisq trade will cost at least $20 just in mining fees. This essentially prices out the .01 BTC trades for unsigned accounts.

I propose raising the limit for unsigned payment accounts to .05 so that we might have a chance to not lose lots of users and trading volume because of the higher network fees.

Here is a real user complaining of exactly this: https://www.reddit.com/r/bisq/comments/jj7q1o/bisq_and_bitcoin_network_utilization/

**Comment by chimp1984** [comment]
Raising that limit risks to render the protection tool to not work anymore. When we had the SEPA chargeback scammer common amounts of his trades was about 700 EUR (about 0.05 BTC), so that means he would have had no restriction to use Bisq for his scam. 
The account signing tool was the only idea found to improve security (as it turned out the account age was not sufficient). If we lose that tool in case scammers return and people lose confidence in the security of Bisq trades, we might kill Bisq with that.

The miner fee problem is real and need to be addressed as well as the low trade limits. 
There have been in the past periods of high miner fees and it went back to low levels, it still need to be seen if recent spikes will be sustained or are just temporal. 
Beside that we should find payment methods which have low chargeback risk so account signing is not needed anyway (like Transferwise).

**Comment by pazza83** [comment]
Irrespective of whether trading with a payment method that is signed or unsigned. I think Bisq should look to ensure people wanting to trade all amounts of BTC can do so with minimal fees. I don't think it would serve Bisq's growth well if was solely a platform that could be used to trade upwards of 0.05 BTC. 

New users especially might want to start trading lower amounts until their confidence increases with successful trades.

Miner fees are a problem at the moment :(

**Comment by pazza83** [comment]
Adding this as I felt it relevant to the discussion:

> The value held by 50% of current cryptocurrency owners [in the UK] is £260 or less

This is 0.025 BTC.

Reference: https://www.fca.org.uk/publication/research/research-note-cryptoasset-consumer-research-2020.pdf

This is the total amount held. I imagine therefore, median averages trade size would be considerably less.

**Comment by sqrrm** [comment]
I agree with @chimp1984 on this, but I'm not 100% convinced. If we raise the unsigned limit we might as well remove it completely and let users judge the risk themselves. This could work as well. Trading any amount larger than USD100 with an unsigned account would be a risk that some sellers might be prepared to take. UI could help show some kind of risk measure as well. This would however radically change how we treat scams and security around Bisq, pushing all the judgements to traders.

While I personally like the idea of no limits and think it's the proper way things should work, I don't think it would work that well. I suspect it would not be great for Bisq's reputation and likely lead to bad press when people get scammed, blaming the platform rather than themselves or the scammer. Should we add an option to allow for no a no limits mode that's available to those that are happy to take these risks? The "I know people will try to scam me" mode. Might work.

**Comment by chimp1984** [comment]
> I agree with @chimp1984 on this, but I'm not 100% convinced. If we raise the unsigned limit we might as well remove it completely and let users judge the risk themselves. This could work as well. Trading any amount larger than USD100 with an unsigned account would be a risk that some sellers might be prepared to take. UI could help show some kind of risk measure as well. This would however radically change how we treat scams and security around Bisq, pushing all the judgements to traders.
> 
> While I personally like the idea of no limits and think it's the proper way things should work, I don't think it would work that well. I suspect it would not be great for Bisq's reputation and likely lead to bad press when people get scammed, blaming the platform rather than themselves or the scammer. Should we add an option to allow for no a no limits mode that's available to those that are happy to take these risks? The "I know people will try to scam me" mode. Might work.

I think that would destroy Bisq not only from the user base but also because LE would see Bisq as a platform which "welcomes" stolen bank account scammers and does not even try to keep them out.

I think a better way is that we be a bit less restrictive with new payment methods and take those as experiment. If there are scams like with Venmo/Cashapp we remove it and damage is limited and isolated. And generally to look out for payment methods better suited regarding chargeback risk than traditional banks.

**Comment by mpolavieja** [comment]
In my view, the solution for miner fees should be trying to somehow reduce them (i.e. a L2 solution like Bonding BSQ or LN if multisig is implemented).   I agree with @chimp1984 that a new series of scams could scare the shit away from users. It could kill Bisq.

**Comment by mpolavieja** [comment]
> Adding this as I felt it relevant to the discussion:
> 
> > The value held by 50% of current cryptocurrency owners [in the UK] is £260 or less
> 
> This is 0.025 BTC.

This is a good point from @pazza83.  Raising the limit wont help users that want to trade small quantities, but lowering the costs would help a lot those users (yes, i am aware that "lowering the costs" is very cheap to say and extremely hard to do).

**Comment by chimp1984** [comment]
@mpolavieja 
I think https://github.com/bisq-network/proposals/issues/279 is a very realistic path forward. If miner fee is only 25% to current protocol thats quite a big gain. 
I think there is also a lot of headroom for lowering security deposit reqirements. #79 is such a candidate or adding BSQ bonds.
https://github.com/bisq-network/proposals/issues/279#issuecomment-723532933 would make it also possible to avoid the unresponsive trader cases, so turnin the costs into a gain if you get the deposit of the peer.
