### ISSUE TITLE
Implementing Bisq DAO with RSK

### ISSUE THREAD

**Issue by MwithM** [bisq-network/proposals#276]
I don't have technical skills, but I think it's good to share this idea on my mind for a long time to be shared.

### About RSK

[RSK](https://www.rsk.co/) (or rootstock) is a Bitcoin sidechain that allows smart contracts through Solidity, being ETH compatible.
### Rationale

Bitcoin first layer is becoming more expensive as it succeeds, making small transactions irrational due to its cost. Using a Bitcoin second layer like Liquid or Lightning Network to reduce costs and access other features, like quicker trades or improved privacy is something that Bisq will have to face sooner or later. Smart contracts also offer different features like automating DAO tasks and hopefully remove CPOF.

### Features

- Automate burning man task: this [role](https://bisq.wiki/Donation_Address_Owner) buys BSQ with BTC that has collected in the donation address wallet and burns purchased BSQ. If BSQ becomes a RSK token, fees and trade RBTC funds into dispute that are sent to DAO donation contract could automatically swapped for BSQ at [RSKswap](https://app.rskswap.com/swap) and burned.
- Stablecoins integration: DAI or DOC could be used to trade at Bisq, substantially reducing volatility risk for trades and allowing exchange of fixed price payment methods (Amazon gift cards).
- Fast confirmation times: Various RSK blocks are published every minute.
- Small fees: That could be a good reason enough to move for short term, but I'm not going to pretend something that is not; reduced fees depend on reduced network use. For long term, in case blocks get full and fees goes up, Lumino might get used, which is like Lightning Network but for RSK.

### Risks

- RBTC is not BTC. Bisq would be built over BTC and RSK, each new layer multiply risks.
- Smart contracts are complex.
- Export Bisq DAO from BTC to RSK. A huge challenge.

**Comment by chimp1984** [comment]
I have not followed RSK closer but I think the peg in/peg out problem is also not solved in a trust-minimized permissionless way. I assume they have a similar modle like Liquid (some sort of federation). Do you know more details about that?

Beside that do you know any real life application based on RSK? As said I was ignorant in following RSK, so forgive my lack of information here...

**Comment by MwithM** [comment]
Sidechains, the way they work now, aren't completely permissionless (that's why I don't consider RBTC=BTC). Federation can't just censor one tx, it has to lock [all](https://www.reddit.com/r/CryptoCurrency/comments/gwfgtb/ama_session_with_sergio_lerner/fsv4jem?utm_source=share&utm_medium=web2x&context=3) peg-out tx.
I thought I did read about a month ago about a way to make the peg-in and out in a permissionless way, but I couldn't find it now.

I got into RSK because of Money On Chain, which enables leveraged RBTC investment to create a stablecoin called Dollar On Chain (DOC). This project is not huge (150 RBTC locked) but it's growing fast even being still in alpha.
They also imported Uniswap from ETH and called it RSKswap. This is a very new thing, maybe it depends on what you consider "real life application", but I think it has big possibilities other than crazy unicorn speculation (i.e. automatic BSQ/RBTC trading).

**Comment by chimp1984** [comment]
All those casino use cases I do not consider "real life application"... but sure hard to define and my personal opinion when it comes the the 1000 of ETH apps which do not serve anything else than gambling IMO. I think the Ethereum space has developed into a fundamentally different one than Bitcoin. The huge amount of money which got invested and locked in works by now as a kind of perpetuum mobile. But anyway, I agree RSK is interesting and 
Sergio Demian Lerner has a profound reputation. I just have the feeling that their main competitor (beside ETH and clones) is Liquid and I would place my bet on them rather than RSK.

**Comment by MwithM** [comment]
RSK was created less than 3 years ago. What I consider it's main real life functionality, a stablecoin, started a year ago and it's still alfa. Bitcoin didn't have many real life uses 3 years after its creation, some will say it still haven't and that it's still a mad casino. ETH itself did not make (in my opinion) anything valuable until the creation of DAI, also a few years ago. It's devs function to make some weird things that then will work into real life.
AFAIK, Liquid have not developed smart contract functionalities yet.
But let's focus on the possibility I pointed out that smart contracts give: performing the task of the DAO address holder (buying BSQ at a token dex like Uniswap and then automatically burn purchased BSQ). That possibility sounds great in order to remove Bisq's biggest CPOF. What are your thoughts about that?

**Comment by chimp1984** [comment]
> But let's focus on the possibility I pointed out that smart contracts give: performing the task of the DAO address holder (buying BSQ at a token dex like Uniswap and then automatically burn purchased BSQ). That possibility sounds great in order to remove Bisq's biggest CPOF. What are your thoughts about that?

Changing the DAO is a huge enterprise. There are other ideas as well how to automate that (I posted recently a proposal). The BM is a problem but low liquidity and economic unsustainability is a much bigger problem. 
Beside that we should look anyway in new trade protocol possibilities (off chain trade protocol, LN, Liquid,...) which would likely remove or change the situation with the BM anyway.

**Comment by MwithM** [comment]
Your last proposal doesn't makes the DAO address holder to buy BSQ and burn them automatically.

> But the main open problem is how to replace the donation address model. Still the biggest unsolved problem of the whole concept.

Because Bitcoin, LN and Liquid doesn't self execute contracts, but chains with smart contract capabilities do.

**Comment by chimp1984** [comment]
> Your last proposal doesn't makes the DAO address holder to buy BSQ and burn them automatically.
> 
> > But the main open problem is how to replace the donation address model. Still the biggest unsolved problem of the whole concept.


Yes true, but that does not mean there is no solution for that.

> 
> Because Bitcoin, LN and Liquid doesn't self execute contracts, but chains with smart contract capabilities do.
> 
> Let me put it this way: don't you think that a Decentralized Autonomous Organization needs Autonomous addresses?

My resistance is mainly rooted by the huge effort and risk to change the DAO. Just the process to move it from current to a new model would be a huge disruption with unknown risks. I think the open probelem with the BM is not justifying that risk and effort at all.

**Comment by ManuFerrari** [comment]
> I have not followed RSK closer but I think the peg in/peg out problem is also not solved in a trust-minimized permissionless way. I assume they have a similar modle like Liquid (some sort of federation). Do you know more details about that?
> 
> Beside that do you know any real life application based on RSK? As said I was ignorant in following RSK, so forgive my lack of information here...

Here is a guide to use the 2wpeg in a permissionless way. Yes, there is a federation, but the federation is only intervenes in the peg in/out. 
https://moneyonchain.com/blog/send-btc-to-rbtc-bitcoin/

The federation does not have access on the BTC locked on Bitcoin when liberating rBTC on RSK network.
 I  recommend the interview from Chris Bleq to Dieguito to understand the role of the federation:
https://youtu.be/gHmVpTE5rn8

**Comment by ManuFerrari** [comment]
> All those casino use cases I do not consider "real life application"... but sure hard to define and my personal opinion when it comes to the 1000 of ETH apps which do not serve anything else than gambling IMO. I think the Ethereum space has developed into a fundamentally different one than Bitcoin. The huge amount of money which got invested and locked in works now as a kind of perpetuum mobile keeping a failed experiement alive. It reminds me on Microsoft which was and is technically always far behind its competitors but have better marketing and lower ethical barriers to do their business.
> 
> But anyway, I agree RSK is interesting and
> Sergio Demian Lerner has a profound reputation. I just have the feeling that their main competitor (beside ETH and clones) is Liquid and I would place my bet on them rather than RSK.

Hi Chimp, 
Having a Stablecoin backed by Bitcoin is a real use case for millons of people around the world that do not have access to currencies that do not devaluate at +50% annual rate, nor can use the traditional financial system. For example in Argentina now you can not legally save in USD in a bank for more than 200 USD per month, and we are heading for Hiperinflación, again.

Money on chain was build having in mind mainly that use case, which will also enable the usage of Bitcoin by millions in a much easier way, and without the volatility that is not something most people like or can afford to support in the short term.

Bitcoiners are already protecting their saving from high inflation and doing business in Argentina and Venezuela, selling pizzas, Trezors, and selling and renting properties for DOC. The Dollar On Chain ( DOC) is a Stablecoin backed 100% by Bitcoin. So, when using it you are using  Bitcoin. I would be glad if you can take a look at the protocol, you might like it more that other Stablecoins backed by dollars in banks accounts or who knows what. 

The other two use cases/tokens you will find in the Moneyonchain protocol is the BPRO token, and the BTCX.

The BPRO is a token made for BTC hodlers, willing to get some free leverage and a coded income in BTC. It is performing also very well. User adoption is increasing. And yes, this is still an alpha.

The BTCX now offers a 2x leveraged position. That is the kind of instruments used a lot by Bitcoiners that trade in platforms such as Bitmex. The difference when using MoneyOnChain protocol is that you do not operate with a counterparty, but you operate with a protocol, and that interest rates are usually way cheaper than Bitmex.

If you want to know more about moneyonchain you can join the Moneyonchain community in telegram:

@MoneyOnChainCommunity

Or here is the webpage: https://moneyonchain.com/

**Comment by chimp1984** [comment]
@ManuFerrari Thanks for the info and links.
My main problem with stable coins is that I have never seen one so far being honest with the question who pays the costs for the pegging. A peg is a hedge and some party takes the risk for a fee. That is fine as long it is transparent. But all stablecoins I know are free to use, so the user who benefits from the stability (hedge) does not pay the costs. Who pays it?
Usually the investors who don't fully understand the scheme. I talk from own experience when I invested in an early stablecoin (NuBit) via NuShare and got burned for my mistake to not study how it really works before putting money in. It worked pretty good until BTC went on a mega really and then it collapsed.

So please don't misunderstand me, I find stable coins an important instrument, and I don't know anything about DOC, so not implying anything, just genuinely interested in an answer to my above question (who pays the costs). The reason I count most stable coins as casino or max. as "the another fiat" is because they are usually built on (for investors) hard to understand concepts (thus it is a high risk investment) and because they are not trust-minimized/decentralized (you have to trust the issuer/managers thus its just a private form of the FED). This second element makes it also nearly guaranteed to fail once it becomes successful. Libra has shown how the government react when they felt challenged. Tether is still too small to be relevant for their attention but they will face a similar end IMO. The last holder will regret at some point realizing that 1 USDT is not 1 USD.

**Comment by ManuFerrari** [comment]
> @ManuFerrari Thanks for the info and links.
> My main problem with stable coins is that I have never seen one so far being honest with the question who pays the costs for the pegging. A peg is a hedge and some party takes the risk for a fee. That is fine as long it is transparent. But all stablecoins I know are free to use, so the user who benefits from the stability (hedge) does not pay the costs. Who pays it?

Yes. I know. Many projects blow out in the past. And I do agree that not all are transparent.

moneyonchain protocol was build by Bitcoiners mainly having in mind Bitcoiners needs. Bitcoiners who do not like centralized not censorship resistant Stablecoins, but still need to use one might be interested on DoC.

Regarding your question on costs, I would like to reformulate, on what are the incentives (there are some costs for using the protocol, 0,1% for minting/redeeming tokens).

 In the case of DoC, the volatility not wanted is give it away to BPRO holders (who are willing to get that free leverage).

 In the case of a black swan of a 90% percent crash in the price of BTC in 1 hour the system might have  a liquidation, in that case BPRO holders loose their BTC and the DOC holders receive rBTC equivalent to USD holding in DOC at the moment of liquidation. The model is high over collaterallizated. Before launching the protocol we runned thousands of simulations and set parameters highly conservative to avoid any liquidation scenario. Now the protocol is running in an alpha version, next version will avoid liquidations completely. But yes there is a black swan event scenario on which BPRO liquidation is possible. It is not ecommended to add a high proportion of your BTCs to the protocol if you are going to provide liquidity (the BPRO holders adds the líquidy to the protocol).

The model showed to be very robust. None of the mechanisms established to be activated in case of big BTC price crash were activated on the March 13 crash, the largest crash in price of BTC in a short period in the last 7 years. Other Stablecoins models backed by "crypto" crashed that day. Here more info about this: https://medium.com/moneyonchain/money-on-chain-march-13th-crypto-downfall-analysis-253e6b93a7df


> Usually the investors who don't fully understand the scheme. I talk from own experience when I invested in an early stablecoin (NuBit) via NuShare and got burned for my mistake to not study how it really works before putting money in. It worked pretty good until BTC went on a mega really and then it collapsed.

As mentioned, the protocol is highly colateralizated. The team been in Bitcoin space since early days. We know NuBit and we studied all models available before inventing our model. We simulated all bitcoin history past volatility. Even with higher volatility the model should have no problem in next crash after current bull run. I would say that main innovation in moneyonchain protocol is the financial model behind the protocol. Most risk on BTC price crashes is assumed by traders doing leveraged (BTCX) operations. And traders that do 2x leverage operations knows that if price of BTC goes down 50% the position will be liquidated. 
> 
> So please don't misunderstand me, I find stable coins an important instrument, and I don't know anything about DOC, so not implying anything, just genuinely interested in an answer to my above question (who pays the costs). The reason I count most stable coins as casino or max. as "another form of fiat" is because they are usually built on (for investors) hard to understand concepts (thus it is a high risk investment) and because they are not trust-minimized/decentralized (you have to trust the issuer/managers thus its just a private form of the FED). 

In the case of moneyonchain protocol the bitcoiners are the ones that mint the DoC or the BPRO or the BTCX. Bitcoiners interact with the protocol. The only way to mint DoC is for a user to send rBTC to the protocol. 

>This second element makes it also nearly guaranteed to fail once it becomes successful. Libra has shown how the government react when they felt challenged. Tether is still too small to be relevant for their attention but they will face a similar end IMO. The last holder will regret at some point realizing that 1 USDT is not 1 USD.

In case of Moneyonchain there is no bank accounts. Only bitcoin as collateral/protocol. Smart contracts are running on RSK network, secured by Bitcoin Miners.

There is two centralization points now: 
1) upgrades on the protocol
2) Oracles

Regarding 1 there is going to be an issuance of MoC tokens that will provide Decentralized governance on upgrades on the protocol (and other features, as holders being able to get most of the fees charged by the protocol for its usage, etc).

Regarding 2  Decentralized oracles will be launched in the following weeks. Current version are "semi Decentralized" (more than one node feeding prices to the protocol).

**Comment by chimp1984** [comment]
Do you have more details regarding oracles? Which sytem is considered?

**Comment by ManuFerrari** [comment]
The OMOC protocol queries price pairs data from crypto exchanges and sends them into a smart contract on the blockchain. This way, the reported prices become available for other smart contracts. Normally, Oracles are centralized services causing the risks of any centralized architecture, i.e. being prone to single point of failure and to malicious behaviour. The Money on Chain approach circumvents these problems through a decentralized price calculation by opening the possibility to any player to run an Oracle and participate in a consensus protocol for price feed publication. 

Decentralized version will be released soon. More info is going to be share soon. Meanwhile here some price feeders:

https://api.moneyonchain.com/docs/oracles

**Comment by chimp1984** [comment]
But who runs the code which requests from the exchanges the prices? Those could cheat, no?

**Comment by ManuFerrari** [comment]
Current nodes have incentives aligned not to cheat. They are all projects working to develop DeFi for Bitcoin. But, not decentralized enough.

On decentralized version, there is a "competition" between MoC token holders to be able to run a node and feed the price. There are also incentives for running a node. You will have to stake MoC tokens to run node (the more you stake the higher the chance to run a node). If the nodes cheat, the protocol does not perform (and the MoC tokens will be worthless). We think the incentives are aligned.

**Comment by mpolavieja** [comment]
I think synthetic stable coins like DAI are interesting.  Maker/DAI system is just an automated bank, as @chimp1984 says, is like a private FED. But since it is all synthetic, I think it would be much more difficult to censor than Libra.

Projects like Bancor, Uniswap or RSKswap are, in my opinion, awesome.  No matter if they are used now to trade worthless tokens, but a DEX with an Automated Market Maker is a real breaktrough in finance.  Probably silly scam tokens won't exist in a few years, but fiat currencies and specially stocks, bonds and other financial assets issued by hihgly trusted entities won't be swept away by Bitcoin, they will still exist, and if they exist they could be tokenized.  Exchanging those tokens through a DEX with an AMM will be very useful.

**Comment by viperperidot** [comment]
I just wanted to add to this that Sovryn is currently using RSK/bitcoin to build their defi platform which will include a decentralized governance token (not sure if it is considered a DAO or not). Just mentioning this because it shows that a Bisq-type application would be possible to be built on RSK. From what I can tell Sovryn is not as decentralized as Bisq is currently (they use a webapp instead of a desktop app) but thought it might be interesting for the Bisq devs to have a look at it. Everything is available on their GitHub I believe and it should provide a bit of insight as to generally what it might look like to move to RSK. We might be able to learn a bit from what they have done if bisq did decide to move to the side-chain. 

https://sovryn.app/

**Comment by RififiCastorjunior** [comment]
i agree with @chimp1984 views on stablecoin, there are to munch shadows. Those entity doesn't disclose everything and made difficult to verify.

**Comment by pazza83** [comment]
Hi @MwithM thanks for the proposal. I am doing some housekeeping on the proposals. Please can you take steps to move this forward or alternatively close the proposal.

Also see recent post here on using RSK smart contracts to solve the burning man problem: https://github.com/bisq-network/bisq/discussions/5477

Many thanks.

Ref: https://bisq.wiki/Proposals

**Comment by pazza83** [comment]
Hi @MwithM thanks for the proposal.

I am closing as rejected.
