### ISSUE TITLE
Cap max reimbursement from peers security deposit

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/proposals#292]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

In case of a DAO reimbursement the one who does the reimbursement is awarded the peers security deposit as reimbursement for the extra effort and time. In case of a 2 BTC trade that is 0.3 BTC and with currently high BTC price about 8800 USD which seems way too high. 

I suggest to cap that amount to an BSQ equivalent of about 1000 USD.

**Comment by pazza83** [comment]
I agree it seems high. Life happens; computers can be stolen / break. People get sick / die / arrested. Lots of things can legitimately go wrong that do not warrant a loss of 0.3 BTC on a 2 BTC trade.

I think maximum someone should lose for being unresponsive is 7.5% of trade amount (50% of min deposit).

I think 1000 USD compensation cap is too low for a 2 BTC trade. I also think compensation should be proportional to the trade amount and not fixed.

**Comment by chimp1984** [comment]
@pazza83 We got quite some repeated cases where the seller does not respond, even with pretty high amounts. It is a bit of a open miracle why that is the case. It is pretty sure not caused by bugs, UX, new user not known that to do... but rather some unknown motivation or circumstances. There is plenty of time between the trade and the reimbursement request and any econimically thinking trader would finds its way to get in touch with the support.
We increased in the past already the security deposit because of those non-responder cases but seems money is not the issued here.
For Bisq it carries also some risk from BSQ volatility and generally the fact that reimbursment requests should be an exception and not happen often. So that the DAO gets some reimbursement for the extra effort in arbitration and included risks seems justified to me.

**Comment by pazza83** [comment]
> @pazza83 We got quite some repeated cases where the seller does not respond, even with pretty high amounts. It is a bit of a open miracle why that is the case. It is pretty sure not caused by bugs, UX, new user not known that to do... but rather some unknown motivation or circumstances. There is plenty of time between the trade and the reimbursement request and any econimically thinking trader would finds its way to get in touch with the support.

It does seem strange, have people chased up historic lost funds in the past, or do they just never come back for them?

> For Bisq it carries also some risk from BSQ volatility and generally the fact that reimbursement requests should be an exception and not happen often. So that the DAO gets some reimbursement for the extra effort in arbitration and included risks seems justified to me.

Whilst I appreciate the reasoning of wanting to compensate the DAO, in my opinion it does not seem right to seek reimbursement due to the trade size being a larger amount, and when the additional efforts are as a result of something the DAO has created by limiting reimbursement / requiring request to DAO for compensation in BSQ.  

Something like DAO compensation, if applied, should apply across trades of all sizes rather than larger ones. If not it might act as a deterrent for traders to make larger trades amounts.

I made the previous comments here which you responded to https://github.com/bisq-network/proposals/issues/220#issuecomment-716985588

I think it would be good if the following where created:

- Create a policy for what happens to security deposits in the event of trade disputes make this available to traders and part of the trading protocol.

- Create a policy for what happens to fee reimbursements in the event of trade disputes make this available to traders and part of the trading protocol.

I do not think I fully understand the trade process once the trade goes to arbitration.

If funds are sent to the burning man to be converted to burned BSQ can't the DAO request the burning man to send BTC payment for some of the received funds to settle the trade. This would avoid the issue of BSQ volatility?

Could the DAO approve burning man to make payouts of > 0.5 BTC, with this type of authorization not being the norm this would mean less chance of error being made if the transaction is authorized separately?

On the issue of DAO compensation, I would be in favor of this if applied evenly across all trades. This compensation would be met by the trader who was at fault for the transaction.

In my own experience in mediation I have been offered 50% of the other parties security deposit and if they are not responsive arbitrator will payout 100%. Maybe in these circumstances arbitrator can pay as suggested to the affected party and the remaining can be given as DAO compensation?  I do think compensation should be limited to 15% of trade amount (or min security deposit).

**Comment by MwithM** [comment]
@pazza83 said:
> I agree it seems high. Life happens; computers can be stolen / break. People get sick / die / arrested. Lots of things can legitimately go wrong that do not warrant a loss of 0.3 BTC on a 2 BTC trade.

Computer stolen or break can be recovered with the seed. That happens from time to time. Death and sickness related losses can happen using BTC. That's part of the risk people is taking when using BTC and not having an inheritance plan. Bisq being so similar to BTC can't help much to solve this.

> It does seem strange, have people chased up historic lost funds in the past, or do they just never come back for them?

No, they've never came back. 

> I think maximum someone should lose for being unresponsive is 7.5% of trade amount (50% of min deposit). This would still be high 0.15 BTC but more palatable for the unresponsive party and still profitable for the seller. This is also what would likely be proposed in mediation.

Mediation should not offer the same deal as arbitration. That could make all trades go to arbitration. 
What do you suggest we do with the 50% extra amount? Send it back to the unresponsive party? I could agree with it when security deposit is over 20% (this high security deposit are used mostly to prevent future trading). 20% of trade amount might be enough to compensate the trader who has to go through arbitration.

> Something like DAO compensation, if applied, should apply across trades of all sizes rather than larger ones. If not it might act as a deterrent for traders to make larger trades amounts.

Agree. I don't see a reason why we should differentiate between high and low trading volumes. They both set the same security deposit %.

@chimp1984 
> In case of a 2 BTC trade that is 0.3 BTC and with currently high BTC price about 8800 USD which seems way too high.

29600 USD trades which are locked for at least a week (probably at least 2 weeks) are rewarded with 8880USD. The buyer also has 8880USD that could be lost if he was the unresponsive party.
Expressed that way, it doesn't seem that high. 

> I suggest to cap that amount to an BSQ equivalent of about 1000 USD.

Just like Bisq does not cap the amount of trading fees collected from high amount trades or reduces the amount for security deposits, Bisq should not cap the amount of awarded security deposit. If 2 BTC max trade amount is a risk, then this trade amount should be reduced.

> For Bisq it carries also some risk from BSQ volatility and generally the fact that reimbursment requests should be an exception and not happen often. So that the DAO gets some reimbursement for the extra effort in arbitration and included risks seems justified to me.

I also think Bisq should take some profit from arbitration, but not this way. Something like an arbitration fee of 3% of trading and security deposits amount if refund agent is the one who reimburses and a 5% DAO fee if the DAO does it would be the way to go. It would be used for all trades, not only high amounts. In case of bugs Bisq should not take any fee.
It would also fight the possibility about the refund agent creates fake offers just to get BSQ from compensation requests for reimbursing this trades. At least for trades over a certain amount.

**Comment by sqrrm** [comment]
The incentives need to be correct. For cases not caused by bugs, making it more profitable to take a case to the refund agent than accepting the mediation doesn't make sense. Starting at the mediation suggestion, assuming it's a "correct" ruling, I think the most that should be awarded is this suggestion. The party that doesn't accept the suggestion would forfeit their share.

The cost in the form of systemic risk to the Bisq DAO is rather large in the refund step and the ultimate step is to burn all the funds that can't be recovered in the mediation step and issuing refunds as the DAO deem reasonable from funds generated from fees. That's currently not even close to feasible, but it's the core of the risk model as discussed before implementation.

**Comment by chimp1984** [comment]
> I also think Bisq should take some profit from arbitration, but not this way. Something like an arbitration fee of 3% of trading and security deposits amount if refund agent is the one who reimburses and a 5% DAO fee if the DAO does it would be the way to go.

I agree, my initial proposal was not much thought out and I agree to the concerns brought up.

## Here an overview about the whole process (I know most of your will know it anyway...)

### Mediation 
The mediator can only suggest a distribution of the funds. There is a min refund of 0.003 BTC to any party left as incentive to accept the suggested payout for the losing party, so a 100% move of the doposit is not possible.
I think we should not apply any fee to mediation.

Note also that the trader could do a manual payout at any time themself (using the new tool from @jmacxx). So that just makes more clear that mediators have not power at all about the funds and are only providing a suggestion. It is in the full power of the traders how to pay out the funds.

### Delayed payout tx
If one of the traders do not accept the mediated suggestion he can open arbitration after a certian period (10 days after trade started for altcoins, 20 days for fiat).
At opening arbitration the delayed payout tx will be created and all funds from the multisig address are sent to the burning mans address. Without that delayed payout tx no arbitration and refund must me made as otherwise the DAO could get scammed by self-trade (mimic a conflict and later once the refund has been done make the payout from the multisig to one self).

### Burningman
The burningman buys BSQ with the BTC he received from delayed payout txs on the market. He prioritizes trades with the refund agent to help him with liquididy. He uses the price of the best offer in the offer book at trade event. If refund agent trades with him the RA need to make offers with a better price as the first best offer. He trades on announced days (I think its each sunday), so anyone can benefit from a liquidity boost once refund agent has covered his expenses.

The BM is a problematic role we would like to get rid of. Its a security risk and a trusted role. There are some ideas how to get there but its not trivial and nothing we can achieve short term.

### Arbitration
The arbitrator/refund agent is a dual role. He is like a mediator and kind of "supreme court" for haveing a second view on the case. He can see the result from the mediation and will take that as basis. That "supreme court" role was not really exercised by the past arbitrator and I am not 100% sure if the new arbitrator is doing it but I think it would be the better model. It does not mean to start from scratch again, just do double check all and in case of real disputes (which wer the exception) to make a own judgement based on the arbuments of both parties. 
Most cases are bugs or not responding peers, so in those cases this effort is very low anyway.

The second role is the refunding for the loss so that the trader does not need to do the hassle with DAO reimbursement and does not lose more time. The refund agent (RA) can decide freely how much he pais either party. There is no min. payout. He pay from his own Bitcoin and it is conceptually important that it is not directly connected with the delayed payout tx but a voluntarily action. A trader has no "right" to get refunded. It is though in the interest of the DAO to have happy traders who continue to trade, so the incentives are aligned to refund in justified cases.

The RA carries volatility risk and liquidity risks as he need to pre-fund the payment from his pocket and later get it reimbursed by BSQ. In between that time the rates can change so it comes with risks and costs. To mitigate that we use that agreement with the BM so that the RA can convert faster the BSQ to BTC. 
There is a limit (I guess 0.5 BTC ?) to limit those risks/costs. If the amount is higher the trader need to do the DAO reimbursement themself.

So far we never charged a fee and gave 100% of the funds to the winning party (in case that was clear and the winning party acted correctly). 

I think for the refund agent service it is fully justified to charge a fee. He is taking over risk and effort and is doing also the secondary mediation work. 

Note also that the RA role should fade out similarily like the BM role. It was introduced only to lower the friction and burden and once we are at the goal to have close to zero arbitration cases per month we can drop that RA role.

### DAO reimbursement
For those cases the RA does not pay out from his pocket the trader has to go to the DAO reimbursement process.
In GH the trader need to post his details and the signed mediation result, so anyone can verify that the posted summary is really from the mediator. The mediator and RA should comment and ACK the request to make it easier for DAO voters.
I think for the BSQ rate for calculating the reimbursement amount we use the 30 day average (not 100% sure). This carries volatility risk again. 


## Main reasons for dispute cases
I am not very up to date with current statistics but I assume due the bugs around v1.5.0 quite a chunk of cases are due bugs. Hopefully that is history soon. Maybe mediators and arbitrator can add here more details how the current situation is. I would love to see those metrics in an easy to access way where we can see a trend if we are improving in that area... 

### Seller not responding cases
As mentioned before we get plenty of those cases and there is no economically ration explaination for those, specially when its high amounts like 2 BTC trades and the loss is 0.3 BTC. But those cases hurt the DAO most as those are the expensive ones and carry the higher risk. We increased the security deposit because of that but seems it did not had effect on that (on future trades it had effect).

## So should we introduce fees for RA and DAO reimbursement?
I think for the RA service a fee is clearly justified. If the user does not agree he can go to the DAO reimbursement himself.
Maybe 80% of the losers security deposit might be justified. This would have impact on lowering the costs for the RA role.
For altcoins its 10 days delay and a few days for RA resolution. So to get 20% of the deposit seems enough to compensate for the delay. Note that centralized exchanges do not compensate nothing in case they block transfers and it easily takes weeks until its resolved.

For the DAO reimbursement it should be then a lower amount as the trader is taking the risk and extra time. Maybe 50% of the losers deposit?

We could also discuss if the 15% min. deposit could be lowered again, as it has shown that it did not help against those not-responding seller cases (at least my impression, we should look at statistics more closely first).

No strong opinions about the numbers. Just have the feeling that the current model is not optimial.

**Comment by pazza83** [comment]
@MwithM 

> Computer stolen or break can be recovered with the seed. That happens from time to time. Death and sickness related losses can happen using BTC. That's part of the risk people is taking when using BTC and not having an inheritance plan. Bisq being so similar to BTC can't help much to solve this.

It helps in the fact that you do not lose all your funds.

Consider the following you are doing a trade for 2 BTC... Your computer breaks (or you get a cornuted wallet), you need to get it fixed but have a flight to catch. You are unavailable for 10 days.

When you return you have lost 0.3 BTC (15% security deposit). I think this is high. I think limiting it to 7.5% (50% of min security deposit) would be more reasonable. 

Bisq can limit loses to traders that become unresponsive, whilst a the same time protecting the interests of their counterparties. 
 
> Mediation should not offer the same deal as arbitration. That could make all trades go to arbitration. What do you suggest we do with the 50% extra amount? Send it back to the unresponsive party?

Yes. Like in the above circumstance. It would limit traders losers and their counterparty would still be up 7.5% on the trade.

> I also think Bisq should take some profit from arbitration, but not this way. Something like an arbitration fee of 3% of trading and security deposits amount if refund agent is the one who reimburses and a 5% DAO fee if the DAO does it would be the way to go. 

3% / 5% of security deposits amount seems reasonable to me.

**Comment by sqrrm** [comment]
@chimp1984 those are some pretty reasonable suggestions. What I take issue with is the economic incentive to take cases to the DAO rather than the refund agent. I think it should be the opposite, we want to avoid cases going to the DAO as much as possible. Since refund agents might not want to take all cases it might in the end be better to have an equal cost for refund agent vs DAO refunds, and the easy of going through refund agent would motivate most to go that route.

I don't see the refund agent as a fully trusted role so it fits with a distributed model to have one of several of them. There's then always the backstop of the DAO as last stop arbitration but the extra time would dissuade all that can to avoid that route.

**Comment by pazza83** [comment]
@chimp1984 

>So should we introduce fees for RA and DAO reimbursement?

Thinking about this, would it not be more simple just to accommodate the additional fees when cases go to arbitration in the trade fees as a whole. Currently collectively trade fees are 0.008%. 

I do not want to guess at numbers but maybe to above could be reviewed to ensure things such as BSQ volatility risks, additional DAO work, etc are included.

**Comment by MwithM** [comment]
@pazza83 Including this cost to general trading fees is what's been done until now, but I don't think it's fair. Not all traders use arbitration and this cost is paid by those traders who cause trades to go to arbitration (Bisq should not take any profit from bugs).

**Comment by Akira45-0** [comment]
More than two weeks ago I sold XMR for 2 BTC . The BTC seller did not bother to release the coins. Given that this happened during a bull run of BTC and a bear run of XMR I have lost lots of money, way more than the 15% security deposit of the BTC seller, because I still have these coins locked. I need BTC collateral to short XMR. No, 15% is not too much, it's the minimum security deposit as required by Bisq. Yes, 15% from 2 BTC is $10,000 currently but we are talking about a trade worth $70,000. How would you feel when somebody told you that he'll give you your $70,000 back in 24h, and then disappeared forever, and you had to wait a month or more with your funds locked, losing the opportunity to earn twice as much?

**Comment by pazza83** [comment]
> @pazza83 Including this cost to general trading fees is what's been done until now, but I don't think it's fair. Not all traders use arbitration and this cost is paid by those traders who cause trades to go to arbitration 

I think it is fair that arbitration is included in general fees. You never know when you will need arbitration. A user could at anytime end up in arbitration through no fault of their own. 

Do you think any specific type of traders are more likely to end in arbitration than others? Thinking markets / payment methods as opposed to poor communicators!

> Bisq should not take any profit from bugs.

Agreed

**Comment by pazza83** [comment]
Hi @Akira45-0 thanks for the feedback. Sorry that you had a poor experience. It is frustrating when you get an unresponsive trader.

Is there an upper lower limit you would find acceptable?

If your 2 BTC trade has used a 50% deposit how much would you be wanting to claim for in arbitration? 

Likewise do you consider 15% adequate compensation for the trade?

My thoughts are that you should receive the 15% compensation as a result of the unresponsive trade as I do not think anything should be applied retrospectively. However going forward I think a cap of 7.5% is fair. What are your thoughts?

Appreciate any comments.

**Comment by MwithM** [comment]
@pazza83 The cost of arbitration would be paid by the trader who violates the trading rules, not subsidized for every trade or paid by the trader who acted right.
And I have to add that a general trading fee increase is not a good idea. 0.8 and 0.4% is a very competitive trading fee.

**Comment by Akira45-0** [comment]
> Hi @Akira45-0 thanks for the feedback. Sorry that you had a poor experience. It is frustrating when you get an unresponsive trader.
> 
> Is there an upper lower limit you would find acceptable?
> 
> If your 2 BTC trade has used a 50% deposit how much would you be wanting to claim for in arbitration?
> 
> Likewise do you consider 15% adequate compensation for the trade?
> 
> My thoughts are that you should receive the 15% compensation as a result of the unresponsive trade as I do not think anything should be applied retrospectively. However going forward I think a cap of 7.5% is fair. What are your thoughts?
> 
> Appreciate any comments.

Even if it was 200% then 200% would have been just. This is how contractual penalties work, and this is part of the contract. You fail to abide to the terms of the trade not only for 24h, but for more than 10 days, mind you, you get your deposit confiscated. I can understand that Bisq needs money to be developed but this should not be done under the false notion that the traders get too much compensation. If 15% is not enough to force some people to abide to the terms of the trade, you can't expect that lowering it will do any good. BTW, I have never seen a large amount trade with a deposit higher than 15%. Nobody would take such offer. When it comes to XMR trading larger deposits seem to occur only when forced by Bisq due to low amount. I think it would be a better idea to make something to accelerate the reimbursement process, because waiting for more than a month is way too long.

**Comment by pazza83** [comment]
@MwithM 
> The cost of arbitration would be paid by the trader who violates the trading rules, not subsidized for every trade or paid by the trader who acted right.

Two ways of looking at this though. As in the case above this would penalize the trader that would receive compensation, by compensating them minus the cost of arbitration. This does not seem fair.

> And I have to add that a general trading fee increase is not a good idea. 

I agree trade fees should be kept competitive. I am not sure what the total cost of arbitrations would be divided by the sum of trade fees. I would imagine it would be in the hundredths of a percent so pretty small.

**Comment by spx4000** [comment]
> these

How did you lose money?  The trader owed you 2 BTC last month, and now you will receive 2.3 BTC from Bisq.  Maybe not having access to your capital cost you some amount of money but you earned ~15% on that 2 BTC in a few weeks/months by just waiting (still) to receive the BTC.

**Comment by chimp1984** [comment]
Following the discussion at https://github.com/bisq-network/support/issues/684 @spx4000 brought up some valid concern we should address. 
It is a bit off-topic to the proposal but I think it still fits into the wider problem field.

So due the volatility risks there is a risk that DAO reimbursements could be abused to get a free option on BSQ.
@spx4000 suggested to use a higher BSQ price and a guarantee that the burningman (BM) is trading those BSQ to that rate to reimburse the BTC. 
But that would cause a lot of distortion to the BSQ price.

What if we remove the agreement that the BM trades with the trader and to use the reimbursement price?
So the BM would buy BSQ asap after he received the BTC on the market to market price and burns those.
Later once the trader get issued his BSQ with 30 day average price he might be lucky that market price might be higher so he can sell to a better price and make some profit or if not lucky and price has fallen he would lose something in case he sells or keep the BSQ.

From the DAO perspective the DAO got burned 60k BSQ (at 2 BTC trade with 1 BSQ=1 USD). 
If price go up to 2 USD the trader receives 30k BSQ so for the DAO its positive as 60k got burned but only 30k got issued. 
If price goes down its the other way around and the DAO makes have issued more than it has burned. 

I think to go back to that original model where there is no agreement that the trader can trade with the BM to a defined price solves all those problems and distributes volatility risk equally to traders and DAO.

**Comment by chimp1984** [comment]
We have to work hard to reduce the arbitration cases. It is a bad/risky for traders/DAO/BM and refund agent.

**Comment by pazza83** [comment]
> How did you lose money? The trader owed you 2 BTC last month, and now you will receive 2.3 BTC from Bisq. Maybe not having access to your capital cost you some amount of money but you earned ~15% on that 2 BTC in a few weeks/months by just waiting (still) to receive the BTC.

They will not receive 2.3 BTC from Bisq. They will receive a compensation in BSQ, which due to volatility could be a good or bad thing for them.

> However, I do agree that you should receive the security deposit from the defaulting trader, especially since that has always been the Bisq policy.

I agree. Also I am not sure where it is documented on Bisq that trades over a certain amount are compensated in BSQ? 

From: https://bisq.wiki/Dispute_resolution#Level_3:_Arbitration

> Practically, here’s how arbitration works:
> 
> If you’re dissatisfied with the mediator’s suggestion and sure you are entitled to a better outcome, publish the time-locked transaction as soon as it’s possible and request arbitration.
> 1. Collaborate with the arbitrator to clarify the details of your case.
> 2. If the arbitrator sides with you, they will personally reimburse you.
> 3. The arbitrator will then request reimbursement from the Bisq DAO for the reimbursements they’ve paid. This isn’t something you need to worry about as a trader, but it’s good to know how the process works on both sides.
> 4. Arbitrators are required to respond to messages within 5 days, so it may take a bit longer for them to respond than mediators (you should still respond to messages within 2 days).

No information saying "2. If the arbitrator sides with you, they will personally reimburse you, unless it is over 0.5 BTC, in which case you will need to seek compensation from the DAO"

If traders are compensated in what they were trading in the first place it limits the risk of BSQ volatility to both the trader and Bisq. The refund agent would still have to pick up this volatility, but that is part of their role.

If the arbitrator / refund agent cannot make payments due to a security risk maybe refunds could be spread over a number of cycles?

**Comment by pazza83** [comment]
Why not just issue @Akira45-0 with a nominal 1 BSQ that they can sell the the burningman OTC for 2.3 BTC. Essentially burningman pays back @Akira45-0

I still think it the above is messy.

Why cant the refund agent make a refund of over 0.5 BTC, I think the limit was introduced due to a payment being made twice. In that case cant the refund be done using a multi-sig with refundagent1 and refundagent2, therefore, reducing the chance of human error?

I think Bisq should look where possible to refund traders in what they traded vs BSQ. I agree that a free option on BSQ is not to the benefit of BIsq.

**Comment by chimp1984** [comment]
Maybe @RefundAgent can join the discussion...
I think the limit was introduced to limit volatility risk for the RA. But I agree that at least the risk of abuse as option trade could be avoided in that case. We could calculate the costs for volatility of the past cycle and deduct that from the refund to the trader (or part of it). It would have the benefit for the trader to get faster refunded and with less hassle. And the RA can manage to keep volatility risk lower if trade with BM happens soon after refund so it decreases the time span where volatility causes problems.

**Comment by chimp1984** [comment]
Btw: If Bitcoin stay longer that high we should consider to reduce the 2 BTC limit to reduce risk for mediators and arbitrators. It happened repeatadely that they made wrong payouts and with 60k USD chances that the receiver is honest and pay back gets lower. The compensation request for them includes some risk compensation but 60k cannot be really covered otherwise the compensation for the role becomes very expensive. 
A split model can also be considered and I gues the RA has done that already, e.g. 50% direct refund, 50% DAO reimbursment.

**Comment by refund-agent2** [comment]
Without knowing, I might have addressed this issue through  proposals #294 and #296.
Through #294 I don't address the issue of volatility and option trading, but I state that RA and traders to reimburse are in a very similar place and should use the same method. The only difference is that I might be more open to volatility and counterpart risk as I voluntarily advance BTC.
At #296 I wanted to reduce the inconveniences and volatility risk for traders to be reimbursed while still limiting the risk I take. As 0.5BTC refunds would be made only at the beginning of the cycle and left at whole if BSQ issuance is close, they'll see drastically how their volatility is reduce.

I don't think there's a perfect solution for this, but the prices to be used need to be well known. Volatility goes in both directions. I think that some reimbursed traders and @refundagent lost some value because of volatility in the past, but that did not bother that much to the DAO.
Maybe we could try that BM rebuys just a part of the BSQ reimbursements (like 80% of them) and the rest was left to be sold at BSQ open market, or just leave it invested/used to pay trading fees.
If this option was used, I think that I should be able to buy a higher % than traders, as BTC is a tool that I need to use to keep doing my job.

**Comment by Akira45-0** [comment]
> How did you lose money? The trader owed you 2 BTC last month, and now you will receive 2.3 BTC from Bisq. Maybe not having access to your capital cost you some amount of money but you earned ~15% on that 2 BTC in a few weeks/months by just waiting (still) to receive the BTC.
> 
In case you didn't notice, BTC was worth $23,130 at the moment of the trade, then reached as high as $40,666, and all this happended while I had my own money locked. My money is still locked after 46 days, which makes the whole notion of 24h trade a joke. At the same time XMR was worth 0.006685 BTC and then dropped to 0.003505 which means I lost the opportunity to short sell XMR using these BTC as a collateral. The 15% compensation is far from being excessive by any standards.

The whole argument from exploiting the arbitration process is ridiculous, as nobody knows what the BSQ price will be.

**Comment by chimp1984** [comment]
@Akira45-0 Please don't take that discussion personal. We are exploring it more from a systemic point of view and this area is unfortunately one of the weakest parts in the trade protocol design and we look for better solutions.
What @spx4000 mentioned is real and even I do not assume at all that you would abuse or would have benefited from the possibility to use is as a free option trade this is a security risk for the DAO and we need to get that fixed.

**Comment by chimp1984** [comment]
Here is an idea how to replace the burningman with a trade bot: https://github.com/bisq-network/proposals/issues/304

**Comment by spx4000** [comment]
I agree that the 15% isn't necessarily excessive and setting security deposits is the choice of the maker, so you deserve the full deposit.  Though that policy should be discussed going forward.

It's incredibly disingenuous to claim that your losses are from not being able to short BTC at 40k or to short XMR at .0067, I mean, sure you could have gone to Bitmex and used 100x leverage and think you lost 200BTC.

Borrowing rates for BTC using BTC as collateral is generally 6-12% annually, and you will be getting paid 15% for around 2 months?  And you have some credit risk to the DAO but this known before you enter a trade.

I claim nothing malicious about your arbitration exploit.  Nobody knowing what the future price of BSQ doesn't mean you aren't getting a free option on BSQ at the expense of the DAO.

 @chimp1984 's idea of going back to the old way seems even worse as now you are making the person getting reimbursed sell a put on the BSQ price.  The BSQ market just isn't liquid enough to support these flows.  The person getting reimbursement  just wants their money back after the cycle ends, no more, no less. 

Let's remove the free call, and also not saddle them with a giving the DAO a free put.

Pazza83 makes one of the best suggestions so far, with just issuing 1 BSQ and that can be redeemed by the person proving they are @Akira45-0 .  Issues would be that trade messing with the BSQ average price, as well as some incentives for users to fake being @Akira45-0 (in this specific case) .

**Comment by Akira45-0** [comment]
I don't like the way all this is handled by referring to my case. I am waiting for my money since Dec 19th. Today is Feb 2nd. All what people here are concerned about is how to pay as little as possible to me, the screwed trader, while nobody is concerned about the real issue, that this whole process should not take that long. As I said, with the 10-day mediation process without any penalty for the non-abiding peer the whole idea of 24-hour trade becomes ludicrous. I routinely encounter people who don't release coins within 24 hours, though they do so nearly every time within the 10-day period. And I don't collect coins for the sake of collecting them, I use them, so having frozen a lot of money for a long time means real losses for me.

I also don't like the idea of changing the terms while the process is still ongoing and the contract is not fulfilled. That's a foul play. I used the 30-day average price because I was told to do so, and now I hear that the price should be changed because it would mean that I could sell a part of it on the free market (the horror, the horror!).

Many times it has happened that the price has changed within the trade period in my disfavor and it never occured to me that I could just try to cancel the trade because I don't like it that I have to pay. It's a contract, I abide to it, and I want the other parties to do the same.

BTW, until the brilliant suggestion of spx4000 it has never occured to me to try to earn something on the utterly illiquid BSQ market. I also didn't bother to check the BSQ price from the moment I have posted my request in December. I also did not have the idea of keeping any of the BSQ that I am theoretically expecting to finally receive as a reimbursement at some unspecified point in the future, because I still have enough BSQ to pay for the trading fees and BSQ is otherwise useless, but now I think I may keep a thousand or two.

If you want to change the reimbursement rules, then do it for the future, and do not tamper with the ongoing processes. Cryptocurrencies are volatile and if you don't like it then make the whole reimbursement process faster. The whole trade as of today takes 45x more time than it was supposed to take.

**Comment by chimp1984** [comment]
> I don't like the way all this is handled by referring to my case. I am waiting for my money since Dec 19th. Today is Feb 2nd. All what people here are concerned about is how to pay as little as possible to me, the screwed trader, while nobody is concerned about the real issue, that this whole process should not take that long.

I completely agree and ask every one to stop making accusations.

The topic of the proposal is to reflect about the general concept which requires improvemnets, not about a single case.

**Comment by spx4000** [comment]
This case is just the example that is spurring discussion.  No one is trying to pay the littlest possible to @Akira45-0 specifically, and from the beginning it was agreed that your 2.6BTC was safe.  

It's about pointing out the existence of these options either calls or puts and not burdening either the trader with a short put or the DAO with a short call.

**Comment by pazza83** [comment]
Yes, I agree. The discussion of the trade is not personal.  I think everyone agrees @Akira45-0 should end up with 2.6 BTC.

The aim of this discussion is to agree what changes need to be made, and what the process will be moving forward.

I agree that separately to this discussion efforts should be made to compensating @Akira45-0 with their 2.6 BTC or equivalent BSQ that can be sold for this amount.

**Comment by MwithM** [comment]
Even if the secondary timelocks are implemented, i find that giving a cost for opening arbitration is still necessary.
The main flaw of this proposal was to think that traders are getting a reward too high when it's a percentage of the deposit, so it's relative to trade amount.
The valid reasons to put a price to arbitration is to internalize the costs of opening it, make Bisq profitable and deterr fake dispute cases created by refund agents.

**Comment by pazza83** [comment]
> Even if the secondary timelocks are implemented, i find that giving a cost for opening arbitration is still necessary.

I disagree with this. I think it should be met by all traders in the trade fees.

Consider this in your proposal. I have a trade that goes wrong. Mediator makes a suggestion that I do not think is fair, or fails to take in to consideration my loses. I can now either accept the mediation I am unhappy with or risk going to arbitration where their will be an additional cost to pay. 

> The main flaw of this proposal was to think that traders are getting a reward too high when it's a percentage of the deposit, so it's relative to trade amount.

Yes, I agree with this.

I also think the issue was created by the DAO themselves when they limited the amount of BTC the refund agent could send as compensation.

Good to see their is discussion in new issues about how to address the underlying problem of burningman / too many trades going to arbitration.

**Comment by Conza88** [comment]
> ### Seller not responding cases
> As mentioned before we get plenty of those cases and there is no economically ration explaination for those, specially when its high amounts like 2 BTC trades and the loss is 0.3 BTC. But those cases hurt the DAO most as those are the expensive ones and carry the higher risk. We increased the security deposit because of that but seems it did not had effect on that (on future trades it had effect).

Should help somewhat - ignorance has to be the case, got so many trades going etc. No clear notifications at all bringing the issue to their attention: 
[#5097 Add Notification icon for Mediation and Arbitration chat](https://github.com/bisq-network/bisq/issues/5097) 
[#5074 Improving trading chat communication](https://github.com/bisq-network/bisq/issues/5074):

**Comment by MwithM** [comment]
@pazza83 
> I disagree with this. I think it should be met by all traders in the trade fees.
Consider this in your proposal. I have a trade that goes wrong. Mediator makes a suggestion that I do not think is fair, or fails to take in to consideration my loses. I can now either accept the mediation I am unhappy with or risk going to arbitration where their will be an additional cost to pay.

I find it that it would be as intended. Mediation suggestion can be reopened, if there is a reason for it to be changed. Traders could even make their own manual payout if they agreed on something but mediator is not responding.
If mediator really did a bad job and arbitration was needed to be open because of it, arbitrator could not charge any fee just like he would have to do with bugs. If a trader thinks the refund was insufficient or wrong, they could still be able to open a reimbursement request at the DAO.

@Conza88 Alerts need to improve, but I don't think I would ever forget about my 0.006 security deposit for 20 days without reaching support or flaming r/bitcoin. Even if it was just a week, if using SEPA.

**Comment by pazza83** [comment]
There does not seem to be agreement with the proposal to cap maximum reimbursements. The discussion has helped create some alternative ways to address this issue. Maybe another proposal could be made once @Akira45-0 has received their compensation.

**Comment by chimp1984** [comment]
I will close it as rejected.
