### ISSUE TITLE
⚡️ Propose how to make Bisq nodes serve as Lightning Network nodes using ACINQ's Eclair library ⚡️

### ISSUE THREAD

**Issue by cbeams** [bisq-network/proposals#3]
Bisq nodes are long-running. Lightning nodes are too. Why not have Bisq nodes become the simplest form of Lightning node now, as a first step toward deeper kinds of integration later?

To claim this bounty, write a proposal about how to integrate @ACINQ's Scala LN implementation into Bisq such that Bisq nodes automatically participate not only in the Bisq Network for the purpose of buying and selling bitcoin, but also participate in the Lightning Network for the purpose of routing payments. 

Bisq users could benefit from even the most basic LN integration immediately because their already-running Bisq nodes would begin to earn fees for routing LN payments. These fees may be very small, but Bisq users were going to be running their nodes anyway; it's all profit from their point of view. And besides, most Bisq users would likely be happy to get involved with and help support Lightning however they can. How better to do that than with the app they're already running?

Later, deeper integrations could allow Bisq users to send and receive LN payments of their own, and eventually turn Bisq into a full-fledged Lightning wallet; yet further work could go on to integrate Lightning directly into Bisq's trading protocol.

The proposal being called for here is about devising the best way to get started while keeping these larger ambitions in mind. The proposal itself is the bounty: come up with a cogent plan that gets rough consensus from existing Bisq DAO stakeholders and the reward is yours. Work alone or with others—anyone and everyone can [submit a compensation request](https://github.com/bisq-network/docs/blob/master/dao/phase-zero.adoc#submit-a-compensation-request) for the proposal, according to the value they contributed to it.

The work to _implement_ the proposal would be managed as separate issues and separate bounties. The goal is to break work up such that small but meaningful chunks of LN integration can be shipped with each Bisq release.

This work is something we've been thinking about doing for a while, but the existing group of @bisq-network/contributors is busy with other priorities. Ideally, we're looking for **new contributors** to get involved with Bisq for this effort, and to work as autonomously as possible to propose and then implement this functionality.

If you're interested in and able to do this work, please say so in the comments and add your ideas. Ideally a small team would form to take this on. The proposal process need not be too formal. It can start as a discussion here, and eventually a BIP-style doc can be submitted to this repository as a pull request. Or, if the plan is already clear enough, it can be mapped out into a series of issues in the bisq-network/exchange repository.

**Comment by ruboots** [comment]
Probably a simple matter of importing the eclair jars and invoking Setup.boot to get a new "Kit" API.

see: line 101 https://github.com/ACINQ/eclair/blob/6142d92cc189dbc63f4118e349f5bcd30349e565/eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala

**Comment by ruboots** [comment]
Probably a simple matter of importing the eclair jars and invoking Setup.boot to get a new "Kit" API.

see: line 101 https://github.com/ACINQ/eclair/blob/6142d92cc189dbc63f4118e349f5bcd30349e565/eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala

**Comment by citkane** [comment]
Because BISQ nodes are long running, my proposal starts at lower level architecture which will allow BISQ to escape the desktop.

This is a CLIENT <-> SERVER model, where the server is wholly owned and managed by the human trader (ie. one server per client). They can access their BISQ functionality from anywhere, on any device.

Applicable to WWW, this could also be true for LAN and DESKTOP alternate scenarios.

# Top level summary #

- The BISQ GUI (Graphic User Interface) is statically served (templates and logic) over http/s.
- All data is bidirectionally transferred over encrypted [websocket](https://en.wikipedia.org/wiki/WebSocket) ([RFC 6455](http://www.rfc-base.org/rfc-6455.html)).
- Bisq-api/exchange becomes part of an API driven stack of modules, which will include ECLAIR (which has its own JSON-RPC interface)
- All communication is routed through an API manger, which serves to translate all the various module API's into a common standard, thus allowing standardised communication within the stack:

  - Module <-> Module
  - Client <-> Module
  - Module <-> Client
  - Module -> Module <-> Client
  - Etc.  
 
- BISQ exchange development can focus on a reduced scope, while modular development around it can independently grow in resources and community, providing valuable functionality for exchange to leverage.

## Topology diagram ##

![topology](https://user-images.githubusercontent.com/998947/35625534-941ab652-068a-11e8-8b36-9924f891d5e1.jpg)

# Proof of concept #
I have a POC for the above typology here: https://github.com/citkane/bisq-front
It can be installed locally and run on REGTEST.
I am working with @mrosseel to resolve and test https://github.com/mrosseel/bisq-api/issues/13, after which I will publish URL's for BOB and ALICE that anybody can play with in their browsers.

# Eclair Integration #
Given the above typology, it becomes trivial to launch an instance of Eclair with JAVA. This will be exactly the same as launching BISQ. BISQ will be able to talk to Eclair bi-directionally through the API manager.

Equally trivial will be launching the required (by Eclair) Bitcoind. This is however not practical, as it forces every BISQ node to also be a full Bitcoin node with a full blockchain. This will only become practical once [Neutrino](https://github.com/lightninglabs/neutrino), a (preferred by ACINQ) Bitcoin Light Client, matures sufficiently.

## Envisaged development pattern ##

1. Eclair silently runs as a Lightning node
2. Api management is built for Eclair
3. GUI is built for a standalone Lighting wallet within BISQ
4. BISQ now has all the required tools in it's shed to allow EXCHANGE developers to integrate Lightning into trading logic.

**Comment by citkane** [comment]
The proof of concept is now live at:
http://bob.openpoint.ie/
http://alice.openpoint.ie/

**Comment by cbeams** [comment]
Closing as inactive. This got a lot of 👍's but ultimately no discrete proposal was offered for how to integrate Eclair within Bisq as it is today. If someone would like to re-open this or, perhaps preferably, to open a new proposal about this, please do. It's worth noting here that @ACINQ just shipped their first mainnet-ready Eclair release.

And in case someone does re-open this (or open a new proposal), please see the guidance on proposals I've just put together in #11. The goal of a proposal around integrating Eclair would be to put together a brutally minimal approach to running a lightning node within the same process as a running Bisq node, for the purpose of (a) earning fees and (b) generally supporting the Lightning network. Any such integration should be bare-bones to start with. Indeed that's exactly what we're looking for in such a proposal: what is the simplest integration that could possibly work for making a Bisq node serve double-duty as a Lightning node?

**Comment by LeadManPL** [comment]
3 years passed since this proposal, maybe there is some new solution that would easily allow to  run BISQ with Lightning Network?
