### ISSUE TITLE
Distribute trade fee in BTC to DAO stakeholders by using locked up BSQ

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/proposals#316]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

This follows a similar idea as in https://github.com/bisq-network/proposals/issues/305 and is another approach to try to reduce the role of the burningman.

BSQ stakeholders can choose to lockup BSQ and receive in proportion to their locked up BSQ trade fees in BTC.

We would need a new UI field for the BSQ lockup to add the BTC receiver address. We do not want to use the BTC change address as the BitcoinJ wallet in Bisq is not suited for receiving a lot of small transactions. The wallet would become very heavy/slow over time (would render it to a full BTC node). 
The user should use Bitcoin core or any other wallet which can handle 1000s of transactions.

The lockup tx holds already all relevant data:
- the locked up amount 
- a proof of BSQ ownership
- the BTC change address is the receiver address for BTC fees

To distinguish old bonds which we do not want to pollute with many small fee txs we can add a second change output for BTC which is used for the trade fee. Only if that is set the bond is used for the trade fee distribution.

So this model would be relatively easy to implement.
- Add a field to the bond UIs to define the BTC change address (receiver address for fee)
- Collect all bonds which have a second BTC change output and use the 2nd output as fee reeicer address

Bonded roles can be revoked and newly set so they can partizipate in the distribution.

**Comment by pazza83** [comment]
Sounds interesting.

So I am assuming in terms of economics:

- Much less BSQ would be burnt
- BSQ would become more inflationary (negative impact on price)
- Available BSQ would likely be staked to decrease existing supply this would have an upwards pressure on BSQ / less people looking to sell (upwards impact on price)

DAO model would be successful, or not, depending on BTC trade volume:

- Less volume traded, BSQ price decreases, higher inflation due to increased BSQ compensation / reimbursements, negative cycle
- More volume traded, BSQ price increases, less inflation due to decreased BSQ compensation / reimbursements, positive cycle

Not sure if the above assumptions are correct but if so if flips the DAO from currently being successful by achieving BSQ supply deflation to one where it is successful if it manages to limit inflation?

If so currently the value of success if held entirely within the BSQ supply (stakeholders realize these when they sell BSQ), whereas with the proposed model it would be shared between both the BSQ supply and BTC distribution  (stakeholders realize these when they sell BSQ, but also receive BTC)?

**Comment by chimp1984** [comment]
Yes, its hard to predict the economic consequences. 
The locked up BSQ are not available in the supply, so it is not only the issued vs. burned BSQ but:
- issued and available on the market (e.g. contributors selling earned BSQ)
- issued but locked up BSQ (e.g. contributors prefer to receive BTC fees)
- burned BSQ from traders using BSQ as trade fee

I think the inflation/deflation balance did not cause much impact on the BSQ price. We only increased BSQ by about 19%. 3.6M BSQ at genesis, now 4.3M BSQ. This over a (soon) 2 years period (about 29k/month). I think those are low operational costs. But it seems that did not have much impact on the BSQ price (e.g. did not create incentive to buy BSQ).

But the main goal of that proposal is not to change the economic incentives for BSQ, but to partially fix the burningman problem as well as reduce the impact of high miner fees on trade fee districbution.

The BSQ stakeholder do not have time pressure to consolidate those small utxos, so they can act more economically than the burningman who is expected to consolidate/trade at least once a month. With current high fee rates I guess 20-50% of the fees is lost on minerfees. Also the BTC/BSQ trades will eat up a chunk of the fees.

The bigger problem of course that trading will become too expensive with those high miner fees is another topic. And will be the main influence about the BSQ price as well as Bisq's future. Until new models are found a focus on higher trade amounts payment methods might mitigate the issue. Also XMR market can help, for large trades the miner fee is not that relevant.

**Comment by chimp1984** [comment]
Btw. it could be implemented with a new UI screen with the mental model of "staking" (though it uses bonded reputation technically.

**Comment by pazza83** [comment]
This discussion is a little quiet but I think a discussion of how to fix the burningman problem is something that could be discussed in one of the [team meeting](https://github.com/bisq-network/bisq/discussions/5378)?

@chimp1984 is it possible for you to link to all the issues / proposals created that address this so they can be discussed?

**Comment by chimp1984** [comment]
Here are some related proposals:
https://github.com/bisq-network/proposals/issues/304
https://github.com/bisq-network/proposals/issues/317

I think that proposal might be problematic from securities regulations point of view.

**Comment by pazza83** [comment]
Thanks, What do you mean by PR?

**Comment by chimp1984** [comment]
Ah sorry, proposal I meant... Will change the comment...

**Comment by pazza83** [comment]
Hi @chimp184 thanks for the proposal. I am doing some housekeeping on the proposals. Please can you take steps to move this forward or alternatively close the proposal.

Ref: https://bisq.wiki/Proposals
