### ISSUE TITLE
Eliminate the "Keep funds in bisq wallet" and "Move funds to External Wallet" button

### ISSUE THREAD

**Issue by leo816** [bisq-network/proposals#327]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

_On yesterday's support call we mentioned this topic:_

After a trade is completed you get the option to "keep funds in your bisq wallet" but the reality is that the funds are automatically added to your wallet and the button serves no real purpose. The "Move funds to external wallet" does make sense but I see it as a confusing step that is not necessary. A user can just go into send funds and move them to his external wallet without an issue. Perhaps having just a notification saying your funds have been added to your wallet would be better in my eyes.
If there is another reason why this step exists that Im missing please let me know.

**Comment by MwithM** [comment]
This proposal is not a "significant project-wide changes or new initiatives where a broad consensus of contributors is neded", so I'm closing as invalid.
I'm not sure wether [discussions](https://github.com/bisq-network/bisq/discussions) or [bisq/issues](https://github.com/bisq-network/bisq/issues/new?assignees=&labels=&template=bug-report.md) fits better for this requests, since this is not exactly a new feature or a bug.

Closed as invalid.

**Comment by ghubstan** [comment]
@leo816  FYI, I had to add a `keepfunds` method to the API to accomplish what that button does from the UI:  move a completed trade's internal state to CLOSED.  You have a point about the button's apparent lack of usefulness to an end user, but some interaction from the user is needed to close a trade.
