### ISSUE TITLE
@pazza83 to assume mediator role

### ISSUE THREAD

**Issue by pazza83** [bisq-network/proposals#337]
This is a proposal for myself to assume the role of mediator.

**Why do we need a new mediator?**

Currently there are two active mediators @leo816 and @huey735. Having a third mediator would enable more mediation support to be provided when mediators are unavailable for any reason. 

Another mediator would enable an increase in the speed mediation cases can be handled.

**Why me?**

- I have been contributing to Bisq for over 6 months as both a support agent and payment method maintainer.
- I have been using Bisq to trade for over 12 months and have lots of experience with mediation.
- I really enjoy contributing for Bisq and providing users with a good experience 
- I have had a look at the [requirements of the role](https://bisq.wiki/Mediator) and feel I can meet them; provide users with support, available on Keybase, create detailed issues, on Github, create regular reports, and respond within 24hrs (mostly available in the evenings UCT time).

**Compensation**

I will request 1,000 USD equivalent in BSQ per cycle for this role. I believe compensation for mediation is this fixed amount.

**Mediator Bond**

I think the bond for the mediator role has recently been reduced from 10,000 BSQ to 5,000 BSQ as per #311 

If approved for the role I will post a bond of 5,000 BSQ prior to starting the role.

**Comment by leo816** [comment]
I approve this request as Support [Team Lead](https://bisq.wiki/Compensation#Team_Lead).
Given some recent events and expecting that volume will increase in the future, it seems logical to add another mediator so that our workload isn't a bottleneck for trades being resolved. Right now me and @huey735 are coping fine, but this may not be the case in the near future.
@pazza83 Will give this more time before indicating you to lock the bond, in case anyone has any comments.

**Comment by pazza83** [comment]
I made a proposal for the role tx id: 7a6d4da9fd6e3fb7f4ea166289164381f59334eb8b558284a3d0df267572ec25

**Comment by pazza83** [comment]
The proposal was accepted :)

I have locked up a 5,000 BSQ bond.

Tx ID: 2c62e227c08e188c22ce1f147a09bf2b11b717bf2c156d725e3fbb4a886df8a0

Looking forward to my first cycle as a mediator.
