### ISSUE TITLE
Monero Bisq User Research Project

### ISSUE THREAD

**Issue by UX-P** [bisq-network/proposals#349]
As discussed with @pazza83  in my previous proposal  #344 , I am interested in applying the User Researcher role to a project based on Monero Bisq users. Learning about the Monero users aims to gain insight on the primary Monero issues/pain points and identify common topics to provide solutions that will satisfy current Monero users, attract new users and grow the Monero Bisq community.

Some focus areas that will be explored are: Resolution methods, P2P communication, user trading journey, the main trading features and understanding core Bisq issues according to Monero users.

To achieve this I will connect with Bisq users and those who use competitor sites by generating anonymous surveys, proposing one on one 30 minutes user interviews, joining and participating in Monero community chats on centralised and decentralised social media platforms, as well as creating discussion points on a variety of Monero communication channels. 
Of course all the above methods will be executed with user privacy and security at the highest of priorities.

Here are a few questions I will be helping to answer:

- General enquiries on the Monero user’s experience 

- What do Monero users find the most challenging part of the trading process?

- What are the most used and liked features for Monero users?

- What are the least used or dislike features for Monero users? 

- Is there anything missing from this app that the user expects, perhaps from using other trading platforms?

**Objectives**

- Communicate with Monero users to better understand the user’s experience during their time on Bisq, including the obstacles they encounter leading up to the point of trade. 

- Use generative research techniques to gain knowledge in the challenges and needs Monero users face while navigating the site.

- Exhaust all research techniques to pinpoint Moneros main talking points

- Analyse research to provide possible solutions for main Monero issues to encourage user growth, loyalty and usability efficiency. 

- Provide Monero users with a comfortable space to give feedback and suggestions. 

**Design Focus**

These are the main usability design points this research will help stakeholders to consider:

- Utility: Is the content or functionality useful to intended users?

- Efficiency: How easy is it for users to accomplish basic tasks the first time they encounter the design?

- How many errors do the users make, how severe are these errors and how easily do they recover from these errors?

- Satisfaction: How pleasant is it to use the design?

**Research Methods**

- Affinity mapping - identifying and grouping the most common discussion points to define clear solutions. 

- User interviews- one on one discussions with Monero users to have a deeper understanding of the way Bisq is used by this particular user group.

- Analytical report on user research findings

- Heuristics report - Using Nielsen's Heuristics to identify specific usability issues that have a potential effect on Monero users.

- Competitive analysis- UX analysis on approximately two Monero trading sites. 

- Surveys- online surveys asking questions tailored to Monero users.

- Social Media- Discussions based on the main topics, usability features and issues of Monero users. 

This research will help to highlight any current user problems that require improvement concerning the Monero user’s journey, while encouraging new ideas and opportunities for Bisq.

**Timeline**

It will take approximately 4 weeks to gather sufficient qualitative research, analysis findings and construct user reports to effectively achieve the initial objectives and derive a list of suitable solutions.

Please feel free to ask any questions or raise anything  I have not considered and you would like to add. I look forward to your feedback!

**Comment by pazza83** [comment]
Hi @UX-P 

Thanks for the proposal.

From my perspective there are two user groups to consider:

1. Monero users that are using. or have used Bisq to trade XMR <-> BTC
2. Monero users have never used Bisq to trade XMR

For the first group I would like to know what suggestions, improvements, concerns they have with regards Bisq utility to trade XMR <-> BTC.

For the second group I would like to know if they know of Bisq, and if so what has prevented them from using Bisq in the first place.

In terms of the timeline of 4 weeks what would be the budget, and what would the deliverables be from the research? 

It would also be good for @leo816 to add any thoughts / suggestions.

**Comment by UX-P** [comment]
Hi,

Thanks @pazza83,  yes these groups will definitely be considered. 

A user researcher's aim is not to be intruding but to get to know our users and thus help to humanise the bisq product for a better UX experience. Here is a breakdown of deliveries: 

**Week 1- $35**

- Discussions on social media on topical questions regarding Monero users and the improvements they would like to see on bisq while discovering main concerns and issues. 

- Gain a strong understanding of competitors strengths and weaknesses from the users perspective in preparation of a competitive analysis.


**Week 2- $45**

- Analysing social media feedback to create an affinity map that highlights the common factors.  

- Create surveys and manage user interviews discussing bisq usability topics (I am aware that Monero users are extremely private but this option will be open). 


**Week 3- $62**

- Analyse surveys and user interviews 

- Create heuristic report with screenshots ( UX Design web standard report for bisq usability improvements) $62


** Week 4- $74**

- Create user research summary based on Monero users needs.

- Provide a detailed competitive analysis

- List small UX solutions based on user research, that enables bisq to be a more Monero friendly environment. $74


Links will be provided and research will not include any affiliation to the user’s online or offline identity. 


I am not sure how Bisq contributors calculate this efficiently but a budget of $216 is sufficient. I just enjoy the work to be honest so feedback on the amount is welcome. I am a UX Researcher currently working from home, I strongly support decentralised platforms but have not yet made a contribution. I have been using Bisq for just over 3 years and would like to assist in improving the user experience, so I am glad to help!

**Comment by pazza83** [comment]
Hi @UX-P 

Thanks for breaking down costs and plans.

I think $216 USD would be well spent by the DAO finding out more about Monero users.

You have my support to take on this project. 

I think give this a couple of weeks to let other users share there thoughts before it can be determined if the proposal if accepted or rejected.

**Comment by chimp1984** [comment]
Hi @UX-P, thanks a lot for the proposal! I am looking forward to your results! I consider your budget request very moderate, I would not have any problems if it turns out to be higher. Just from the quality of the proposal I have best confidence that the result will have great value for Bisq.

You might be aware of a few potential issues Monero users are facing with Bisq yourself but I can give here a few from what I hear often and want to give also a bit of explaination/background/context to those points.

- Bisq is very slow, takes too much CPU: This problem was recently resolved by changing the way how we deal with the DAO state hash calculations. It is already in master and will be in the upcoming release. The sync for the DAO state if a user had to sync up 1 months took about 20 min with 100% CPU usage. Now its 2-4 seconds. It was a pity that we have not fixed that much earlier as that has for sure turned off many users. The problem was a scaling issue, initially with less data the hashing was fast enough to not cause UX problems but over time the DAO state grows and the concept required an adjustment.

- You need BTC to trade XMR, but the user wants to trade XMR-Fiat directly: This is what Haveno is implementing. From what I have seen in their design it will come though with many drawbacks. Some are inherent from the technical limitations of XMR (no time lock, you cannot create chains of unconfirmed txs, you can only spend XMR after about 20 min, more complicate multisig,...) and others are IMO risky conceptual decisions like using a 3rd party for the whole trade process not only in dispute case, turning a 2 party protocol to a 3 party protocol with higher risks for network failures and bugs and exposing the 3rd party to legal and regulatory risks. So even it is somehow technically possible it comes with a high cost and questionable user experience. Bisq tries to target that use case with a new implementation (Misq) where many fundamental concepts are different which allows more flexibility for different markets and allowing trade protocols not based on BTC. Also Atomic cross chain swap XMR-BTC will be a core priority for Misq.

- BTC bought at Bisq are tainted: This claim appears from time to time on Reddit, but so far nobody had ever brought up any facts backing that claim. As far I am aware there are also no reports from the Bisq support team about cases where Bisq users bought BTC and later got problems spending them because those coins have been tainted (e.g. if sending it to a centrlized exchange). Also user who are concerned about that can use tools like Wasabi to gain back fungability.

**Comment by pazza83** [comment]
Hi @UX-P 

Many thanks for this proposal.  I have marked your proposal as approved. Looks like it has a lot of support from users.

Please feel free to get to work.

Once you have completed the work you can make a compensation request. Details on how to do so can be found here: https://bisq.wiki/Making_a_compensation_request

It would be great if you can message me on Keybase: https://keybase.io/team/bisq

My username there is: pazza 

I would be happy to help if you have any questions, and participate in any user research you would like.

 I am looking forward to seeing the results.

**Comment by UX-P** [comment]
Thank you for the approval! I will begin working on this from Tuesday.
@chimp1984 I am familiar with a couple of these issues, thank you for the in depth explanation this will definitely be helpful when considering potential UX/UI solutions. 

@pazza83 I am glad you are willing to participate, I will be contacting you soon for any questions.

@chimp1984 @pazza83 I am sure you have heard that Kraken will be delisting Monero for UK customers by the end of November.
I am not sure who manages the Bisq social media posts, could they be tagged in this? This is a great opportunity for decentralised trading platforms to reach out to the UK customer base. If you haven't done so already, I would suggest posting a title addressing UK Kraken users directly. A few key words/ points you could mention in the description:

- No KYC

- Decentralised

- Peer to peer

- BTC-XMR and other swap methods (apologies this is the only one I am familiar with)

- If you are planning to introduce Fiat -XMR soon, mention this too providing a timespan if possible.

- Users have expressed that the Bisq UX is a little too complex, perhaps mention something along the lines of Bisq being a working progress and in using Bisq, users are contributing to it's evolution. It helps to provide users with information on Bisq's current state and highlight future implementations.

- Highlight any key services/features Bisq offers to XMR users

- A link to a step by step guide on  how to get started for Monero users, if possible. 

- Provide a support contact and a link to the Bisq platform.

Maybe a social media contributor could look into this? Otherwise I could write out a draft, it will need to be edited with the relevant information as I am not familiar with all the Bisq features. 

Meanwhile, I will update you weekly on any progress made regarding the Monero research project, thanks!

**Comment by pazza83** [comment]
Yes, I think the Kraken Monero for UK customers is an opportunity. Most UK customers are also unable to deposit fiat to Binance due to banks following FCA guidance. This means it is harder to purchase Monero in the UK as onramps are being closed. Bisq could help provide UK users with a bridge to Monero.

**Comment by pazza83** [comment]
Closing as approved

**Comment by UX-P** [comment]
Hello, @chimp1984 @pazza83 @ripcurlx @jmacxx @leo816 

### **Week 1** 
Here is a link to the customer profiles created from an in-depth analysis based on discussions found and questions asked via social media.

[Monero User Profile](https://github.com/UX-P/Monero-user-profile/blob/main/Bisq%20Monero%20User%20profile.pdf)

These profiles represent the typical Monero Bisq user and should be used to make key decisions regarding all things Monero. It helps the team to plan designs based around the customer so as to condense any personal opinions in regards to the implementation of any new features and services.
For the best results, the team should refer to the personas by name e.g, ‘The atomic swap feature will help nipx231 to make quicker and more efficient P2P exchanges.

The two non Bisq users shown on the attachment are not the main Bisq target audience as they typically do not have or will not use bitcoin. However, future actions can be taken to target these profiles. e.g. ‘Make the #buy-bitcoin Keybase channel more accessible to clumpyleakz’.

The Bisq concept seems to be very original which is extremely positive, however, as an overall issue I have found that people are confused by Bisq’s main goals and objectives and therefore unclear what Bisq provides or wants to provide to a Monero trader. If you do not mind, this week, I will be asking the team a few questions to also get an internal point of view.

**Competition**
Local Monero, Kraken and Haveno are the main competitors that have been mentioned. 

List of references

**Matrix:** 
Suggestions for a reliable P2P decentralised exchange?
Could you tell me about your experience while trading XMR using Bisq? Were there any particular issues?
Why do you not use Bisq?
Did you end up using Bisq, how was your experience?

**Discord:**
Can anyone tell me why they prefer to use centralised exchanges to buy XMR?

**Reddit**
https://www.reddit.com/r/Monero/comments/r1ierk/bisq_monero_traders/ 
https://www.reddit.com/r/Monero/comments/hq2hv0/any_other_way_to_convert_btc_to_monero_besides/
https://www.reddit.com/r/Monero/comments/dc0owx/monero_decentralized_exchange_dex_1st_ever/
https://www.reddit.com/r/Monero/comments/micevf/would_you_like_to_be_able_to_use_bisq_to_buy/
https://www.reddit.com/r/Monero/comments/hq2hv0/any_other_way_to_convert_btc_to_monero_besides/

No response from lemmy.ml or Quora users yet 

I have not gotten around to answering back yet so I will continue with these discussions.  
In the meantime please take a look at the [Monero User Profile](https://github.com/UX-P/Monero-user-profile/blob/main/Bisq%20Monero%20User%20profile.pdf), all feedback welcome of course!

**Comment by clearwater-trust** [comment]
Thoughts from a mutant:

Great data. Thank you.

I had the inclination to read up on Haveno and chimp1984 reply here:  https://github.com/bisq-network/proposals/issues/349#issuecomment-974259817

Is there a _profitable_ reason for the DAO to work with Haveno and/or implement native XMR in Bisq client?
Can the DAO benefit from implementing native XMR? (i would argue yes) 
We can _negotiate_: 2 of 2 vs 2 of 3 and other issues here: https://github.com/haveno-dex/haveno/wiki/FAQ 
How can we make **BSQ MORE VALUABLE**?
Is this an opportunity for the DAO? For BSQ? 
Can we consider this a business opportunity **FOR THE DAO**-  and NOT necessarily a corruption of crytpocurrency scripture. We need to find ways to WORK TOGETHER. 

because the people needs us. now, more than ever

it should be noted that Haveno is currently vaporware. That puts BSQ on the high-ground in any negotiations for native XMR inclusion.

**Comment by UX-P** [comment]
### **Week 2** ### 

A link to the [affinity map](https://miro.com/app/board/o9J_lgjWY1s=/?invite_link_id=6795510031) addressing users key comments, pros, cons and issues, I will continue to develop when creating a competitors analysis. 

**Findings**

Here is a summary of the main points:

Buzzwords: Private, cheap, easy, fast, secure, fungible and freedom

**The community**

- Identity preservation is priority

- New traders struggle to find a good exchange to trade Monero

- Monero is difficult to buy 

- Complex user interfaces are very discouraging

- Most users enjoy using exchange platforms that provide ease. These are mostly centralised.

- Litecoin is the main altcoin used as a ‘middle man’ to swap from Fiat to XMR due to its low transaction fees

- There is a large interest in atomic swaps

**Bisq Monero users**

- Main BIsq Monero user profiles/personas are [gotmilk1u29](https://github.com/UX-P/Monero-user-profile/blob/main/Bisq%20Monero%20User%20profile.pdf) and [nipx231](https://github.com/UX-P/Monero-user-profile/blob/main/Bisq%20Monero%20User%20profile.pdf) with the possible recruitment of [clumpyleakz](https://github.com/UX-P/Monero-user-profile/blob/main/Bisq%20Monero%20User%20profile.pdf)

- Main Monero community is [catman621](https://github.com/UX-P/Monero-user-profile/blob/main/Bisq%20Monero%20User%20profile.pdf) and are not Bisq's direct target audience

- Bisq users are comfortable with blockchain transparency

- Supporters of P2P, uncomfortable with using mainstream exchanges

- Communicate mostly for issues and support

- Mostly active on Keybase

- Would like the option to trade Fiat>Monero

**Non Bisq users** 

- Confusion on Bisq’s anonymity and privacy values 

- Have No BTC because unobtainable or user is against the BTC values

- Complex UX, UI too technical 

- Slow, therefore unaware of the changes that have been made to rectify this

- High fees- many who say this seem to not have used Bisq in a while

- Would like a KYC Fiat > XMR option

- BTC not untraceable is an issue

### Survey

I have designed a [survey](http://zlm2m5lntvrxefekrbmh4wtthapwxp34cic4zs46icj2rxpp6we4lbad.onion/) (developed by a lead front-end developer friend), please take a moment out of your day to complete. It focuses on Bisq and its current user journey for Monero users asking specific questions from three points of view: user, developer, contributor. If more than one of these is applicable to you, you are welcome to exit once you have submitted the form and restart, selecting another POV.  

The link supports Brave and tor browsers only. If you agree, I can post the survey on social media channels. 

Thank you :)

**Comment by chimp1984** [comment]
@UX-P 
Great thanks for your update!

I think it might be helpful to create some sort of FAQ-like repsonse to some of the circulating critizisms (maybe on the webpage)  as some of the postings are very distorting and causing ongoing damage to Bisqs reputation if not corrected/countered/brought into context.

Here my 5 cents to some I stumbled over from time to time:
- BTC fees ar super high: Yes at some moments they have been high, but > 90% of the time its not an issue. Provide  [charts](https://bitinfocharts.com/comparison/bitcoin-transactionfees.html#3y) of average BTC fees to show that the times when fees become critically high are rather short periods. Also bring it in context to volatility (e.g. price moves have mostly much more effect on costs of a trade). 
- Bisq fees are high (not often seen though): Just show real trade fees and compare to other CEX/DEX. Make clear that total fee is trade fee+miner fee. Also mention BSQ for lower fees and make clear why BSQ is important to Bisqs mission. Make clear that security deposit is not part of the fees (some seem to confuse that).
- UX/complexity: As shown in your mindmap similar critizism Bisq experience happens also to the Monero GUI wallet, which is pretty good IMO. I think same complaints comes to Bitcoin core. I think people need to understand that convenience comes with some price. So far nobody has found the perfect solution to provide the values we are based on (privacy, censorship resistence, self costody) and the most convenient UX as usually offered by centralized platforms. But sure we should improve here.
- DAO is unnecessary: Show why the DAO is important for censorship resistence with links to existing docs
- Java is slow: Show benchmarks  Java compared to C++. Naked performance is not the main factor. Code complexity is the main challenge with apps like Bisq. Many recent improvements have shown that there is lot of headroom. But sure we should improve here. 
- UI is slow: Same as above. Its not JavaFX, its because of complex code not optimized. Lots of headroom for improvement.
- UX is confusing: users who are used to CEX might be more confused as they come with some expectations which are not fulfilled due the different concepts of a P2P DEX. Sure there are lot of headroom for improvements, but a Uniswap like DEX will likely not be possible with Bisqs concepts and values (most of those ETH based DEX are not very decentralized, as easily shown when they get shut down by regulators, and ETH itself has much lower level of decentralisation due many issues like Infura, ETH foundation, hardforks,...). 
- Bisq has no liquidity: The main markets (USD, EUR, XMR) have sufficient liquidity. Other markets though still suffer from low liquidity, but if everyone just complains about that and not use Bisq to lower the problem it will not go away from itself. Liquidity is created by the users and its in their hands. 
- You need BTC to trade XMR: Yes, but the costs to do Haveno-like XMR-fiat trade is very high due the technical smart contract limitations of XMR (no chained txs, long confirmation time before you can spend from a tx, no timelocks). We probably should not waste energy by confronting the Haveno concept, but it would be good to make clear that its not a free lunch, and future will show if users are willing to pay the extra costs on UX when using Haveno. Beside that it comes with lower censorship properties (as 3rd party is involved in the trade). Also its a bit contradictionary to use XMR for best privacy but then want to do a fiat (bank based) trade, which comes with the biggest privacy risks. Its probably other groups of XMR users and some XMR maximalism/tribalism might be another reason. I guess against those tendencies we cannot do anything anyway.
- Atomic cross chain swaps are the solution to all: Its cool tech but costs for running the infrastructure (full XMR node, full BTC node, swap infrastructure) are a considerable issue, specially for those users who complain already about Bisq or Monero GUI wallet. Also confirmation time is a limiting factor (same as in Bisq) and it will not be able to compete UX/convenience wise with a CEX. And there seem to be some minor security issues (not sure if they are fully solved/solveable - its not about stealing funds but wasting the peers time and liquidity by not cooperating and need to wait for the refunds). Beside that its totally new tech and comes with risks for bugs/unknown security flaws and if funds are lost due of bugs it is probably much harder to get them unlocked. Make clear Atomic cross chain swaps are clearly on the Bisq 2.0 roadmap, but expectations should be confronted with the reality. Its also still heavily in development and not yet ready to get implemented. Here is a good overview: https://www.monerooutreach.org/stories/monero-atomic-swaps.html

**Comment by UX-P** [comment]
Hi,

Please view my Week 3 update in the two links provided below:

Thanks @chimp1984 I agree, a lot of the confusion can be solved through being informed and educated about Bisq. 

Faq will definitely help.  I have listed a few topic ideas in this [competitor's report analysis](https://docs.google.com/document/d/19svHdhqickZAbuqa-cnKayYLuuchJwzLCzN646P-Jm4/edit?usp=sharing). 

>Bisq fees are high (not often seen though): Just show real trade fees and compare to other CEX/DEX. Make clear that total fee is trade fee+miner fee. Also mention BSQ for lower fees and make clear why BSQ is important to Bisq's mission. Make clear that security deposit is not part of the fees (some seem to confuse that).

Yes, also highlighting why it is important for the community to support DEXs, how these fees help in moving away from CEXs, and the longterm benefits.

> DAO is unnecessary: Show why the DAO is important for censorship resistence with links to existing docs

I have seen this. In the competitors analysis there is a 'word of the day' idea I hope interests Bisq

>  UI is slow: Same as above. Its not JavaFX, its because of complex code not optimized. Lots of headroom for improvement.

  What technological plans are there to improve the UI? particular the look and feel. Currently Bisq is designed for 'tech savvy' power users which seem to repel potential traders. 

>You need BTC to trade XMR

In keybase there is a 'buy-bitcoin' channel. Is there a way to perhaps provide a link on the UI for beginners? Maybe in a 'I don't have Bitcoin?'  section. Highlighting that these trades are with reputable Bisq users but all transactions are at the users own discretion.

Atomic cross chain swaps are a great solution to various pain points, a challenge a will be to make it user friendly and understandable to traders, but highly beneficial.  


Here is a [competitors table summary](https://github.com/UX-P/Monero-User-Research/blob/main/competition%20analyis.pdf).

**Comment by chimp1984** [comment]
> What technological plans are there to improve the UI? particular the look and feel. Currently Bisq is designed for 'tech savvy' power users which seem to repel potential traders.

I do not think that is a technological issue but a conceptual and human resources issue.
Conceptually a P2P DEX will never reach the convenience of a CEX (ignoring the pain of getting KYCed). I think users have to be aware of the trade-offs and its unfortunate that convenience seems to be the top priority for too many and those are often not aware of the drawbacks or do not have the consciousness about privacy and security.
Human resource wise we lack on UI development work force. Pedro is a world class designer and there are several design suggestions provided but we did never manage to get it implemented. Beside UI dev resources an UX-expert (like yourself) would be very important to get the UX right.

**Comment by chimp1984** [comment]
I was not aware that one can trade LTC-XMR via the Monero GUI wallet.

**Comment by yoshimo** [comment]
Why wouldn't you be able to reach a similiar level of convenience? There are standards for online banking, HBCI and PSD2 in Europe, there are Atomic Swaps, Payment via Paypal/Samsung Pay/Apple Pay, and probably other convient ways for fiat to enter the Bisq world and be compatible with handling&checks by our dex software.
Has someone looked into automatic confirmation & issuance of payments outside the realm of crypto<->crypto transfers?

**Comment by chimp1984** [comment]
Atomic Swaps are only possible between cryptocurrencies not for Fiat. BTC-XMR atomic cross chain swap is still in development and on the roadmap for Bisq 2.0.
Payment via Paypal... are insecure due easy chargeback.
Security model of a CEX is very different to a DEX. It is easy to "swap" BTC to Fiat when the CEX holds both your BTC and your fiat. Also company based exchanges are exposed to regulatory forces, thus violating users privacy.

> automatic confirmation ...

Some modern FinTech companies offer APIs, but there is no standard and implementing for each institution their API will be a major effort. Also comes with some added security risks.

**Comment by UX-P** [comment]
> I was not aware that one can trade LTC-XMR via the Monero GUI wallet.

@chimp1984 Good spot, no it doesn't. I’ve uploaded an edited copy and actually removed Monero GUI from the table as it’s a wallet solely used to store, send and receive XMR, not for swaps which makes it not too relevant to that particular evaluation.

**Comment by MwithM** [comment]
@UX-P You can use this [wiki page](https://bisq.wiki/Trading_costs) to reference Bisq costs. This page was created to clarify that "Bisq fees are high" is true only when mining pool is full.

**Comment by yoshimo** [comment]
> > automatic confirmation ...
> 
> Some modern FinTech companies offer APIs, but there is no standard and implementing for each institution their API will be a major effort. Also comes with some added security risks.

As far as i remember it was an official standard for every bank in the region so you don't have to rely on different apis for different banks. 
We already had multi-banking apps for desktops and mobile before PSD2 and they only partially relied on parsing the online banking website ;)

**Comment by UX-P** [comment]
Hi all,
Happy New year!

A summary report on Monero Bisq users and non Bisq users based on  research via social media and survey results. (Recommendations in italic).

### **Members of the Monero community are very active on social media.**
Monero is regarded as an ideal medium of exchange due to its fungibility. The community often pitch the idea of financial privacy, freedom from fiat and being a bankless society, praising Monero for being a truly anonymous digital coin. Having said that, research shows that a wide group of users continue to use CEX platforms. It provides that ease of use, instant trades, low fees and a level of privacy that they find acceptable. These platforms are often used by those who utilise Monero as a currency and therefore require Monero immediately or regularly.
It seems to be unclear to users what Bisq has to offer, some are not even aware that Bisq trades XMR.

- _Add an XMR tab on the Bisq landing page_

### **Non Bisq users prefer a scheme where BTC isn’t involved at all**
This is more where Haveno fits in. A large portion of the Monero community would like XMR as a base coin and are generally uncomfortable using Bitcoin, one user saying they would not use Bisq for XMR if it required them to have Bitcoin.
Haveno appeals to the [catman621](https://github.com/UX-P/Monero-user-profile/blob/main/Bisq%20Monero%20User%20profile.pdf) persona. Whereas, Bisq is aimed at those who hold XMR rather than use it regularly. catman621 prioritises the speed in which they receive Monero and cheap transaction fees, unless this changes, Bisq will remain unappealing to this group. 

### **The main reasons as to why Monero traders use Bisq / Bisq USP**

- Trading fiat and crypto currencies without having to rely on centralised exchanges 

- Privacy, no KYC

- Access to a Decentralised platform 

- High level of privacy and anonymity

- Support P2P movement

- Open sourced

- Tor hidden

### **Bisq requires a less complex user journey, or it should be made clear that the platform is aimed at expert users.**
When asked how Bisq can improve, 66% of survey participants mentioned the user interface. In its current state, Bisq is not an exchange aimed for beginners, those who use the platform will admit that the interface is not very intuitive. 

- _The information architecture is not too comprehensible to the average trader, the UI is uncomfortable to use as it is not familiar. The UX web standard principle ‘Match between system and real world’ states that the design should use familiar wording and icons with little to no internal jargon._ 

 
### **Bisq is slow**
50% of survey participants reported the interface as being slow, resulting in technical issues.

- _The Bisq UI should accommodate for the waiting periods by providing clear loading indicators at all relevant touch points or adopt a more social aspect to Bisq so that waiting periods are much less tedious. e.g., link directing to Keybase/Matrix while users await for transactions to complete._ 

 
### **There have been requests for Bisq to integrate a Monero wallet.** 
While using CEXs, it seems that withdrawing from an exchange platform is preferable within the Monero community. When asked on the Monero subreddit if users prefer internal wallets vs external wallets, 100% of redditors replied holding their own keys is the main priority. Walletless and decentralised platforms such as Bisq actually incorporate many of the community's beliefs and it is important that Bisq promotes this concept accordingly.

-  _Promote the fact that Bisq allows users complete control over their own keys and encourages users to not leave their coins anywhere outside of their control._

 
### **BTC is required for the security deposit**
This poses an issue for the majority of the Monero community but is not key for Bisq’s initial target market. Bisq users already have Bitcoin obtained from external means or from Bisq, and will already have the ability to make a trade.

A common obstruction is a user not having Bitcoin in the first place to begin trading on Bisq.  A user claiming ‘this is actually what stops me from using Bisq’.

- _Direct users to the keybase ‘#buy-bitcoin’ channel via the UI. Warn potential users that these trades are made under the user's discretion and that Bisq will not be held liable for any incomplete trades. Disputes are handled between the peers with no internal mediation intervention. Highlight the positives such as no KYC, untraceable BTC trade to help users get started on Bisq and made by reputable Bisq users._ 

 
### **BTC is traceable and transactions are visible on the blockchain.**
There is a misinterpretation of Bisq and its connection with the Bitcoin blockchain. Monero users have a general issue with Bitcoin’s transparency, however, they are comfortable with the Litecoin blockchain due to its provision of cheaper fees and faster transactions.

- _Atomic cross chain swaps will help to widen the Bisq audience and provide the high level of confidentiality that some Monero users are seeking. It gives the trader authority over their own trade and fully incorporates a bankless society where users can buy and then spend Monero privately. However, this must be implemented in a smooth, understandable way as users would like atomic swaps to be more user friendly._

- _It would be great to have atomic swaps described in more simpler terms, an explanation condensed into how this would be implemented into Bisq and how it benefits Monero users._

  
### **Users would like a Fiat >XMR option.** 
Monero users would like Bisq to use an XMR base currency to bypass BTC. However, there is the understanding that in order to trade Fiat > XMR on Bisq, a substantial amount of BTC is still required for the deposit.
Those who demand Fiat > XMR with Monero as a base coin do not necessarily hold BTC or want BTC and therefore are not Bisq’s main target audience. Bisq’s audience have Bitcoin and trade BTC to XMR irregularly or have enough Bitcoin to use as currency to trade XMR in large amounts.

- _Fiat>XMR with Bisq’s target audience, will encourage regular trading while enabling users to continue using Bitcoin as a store of value._ 

 
### **CEXs are also very active on social media, particularly Reddit.** 
However, with the existing problems circling around these exchanges, the promotion of DEXs is required. It is necessary for contributors and traders to join in on discussions using a variety of social media channels to show a good level of involvement in the community. 
As mentioned in the competitors analysis, Bisq’s reputation has been tainted. This can be rectified by having contributors, traders, developers answer all Bisq related questions on social media, correct misinterpretations and help with incomprehension. For example, questions such as ‘How do I buy Monero with Bitcoin?’. This provides a good opportunity for Bisq to be recommended as a reliable DEX.
 
_The Monero social media channels where Bisq has been mentioned are: Discord, Reddit, Matrix, Mastadon and Keybase._

**Comment by chimp1984** [comment]
Great thanks for the summary!

Anyone who is willing to take the lead to get the action points implemented?

**Comment by ghost** [comment]
Dear @UX-P, thank you for the excellent research report and suggestions.  I'm replying here to try and get a handle on what deliverables are to be expected from your suggestions.  

In summary, you suggested:

1. Add an xmr tab to the landing page.
2. Use familiar wording and icons.
3. Accomodate waiting periods with clear indicators.
4. Promote that bisq is non-custodial.
5. Direct users to the buy-bitcoin channel on keybase.
6. Atomic swaps implemented in a simple, smooth, understandable way.
7. Fiat to xmr trading.
 

My request is that you open a [github issue](https://github.com/bisq-network/bisq/issues/new) for each recommendation, to define them in more detail.  That way a developer can implement your recommendation to the spec.   I'm available to help discuss the details either on keybase, in calls or on github, as also are many others in this community.

Here's an example that @pazza83 sponsored for a **community tab** https://github.com/bisq-network/bisq/issues/4904.  It had merit, and was picked up by a developer, but ultimately still needs work to get accepted.  I think this one could benefit from more community "drive" from some people like yourself, pazza83 and xyzmaker123.

Another example, here is one that pazza83 created for **fiat to xmr trading**: https://github.com/bisq-network/bisq/discussions/5285.  This brings up a good point, some suggestions are very difficult and as such do not get picked up.  I think that the first 5 in your list are do-able, the latter 2 are large projects that would require substantial drive and community involvement, and appear unlikely to happen.

As far as UI coding goes, AFAIK we currently have @xyzmaker123, @ripcurlx and myself that tend to pick them up.

**Comment by UX-P** [comment]
Hi @jmacxx, no problem! I'm glad you see it's value.

Yes those are the suggestions in summary and I will follow your advice and create an issue for each. 
In priority order would be best and one at a time as to not overwhelm. @pazza83 's initial proposal appears to be the most urgent and I plan to open an issue starting on this topic. 

Thanks for providing contacts, I'll ensure to communicate with the bisq contributors/developers regarding any progress.

**Comment by pazza83** [comment]
> @pazza83 's initial proposal appears to be the most urgent and I plan to open an issue starting on this topic.

Hi @UX-P sorry missed this comment. What proposal do you mean?

Let me know if you need any assistance with coordinating the implementation of the below:

- Add an xmr tab to the landing page.
- Use familiar wording and icons.
- Accomodate waiting periods with clear indicators.
- Promote that bisq is non-custodial.
- Direct users to the buy-bitcoin channel on keybase. (this will now be Matrix)
