### ISSUE TITLE
Proposal: Add BTC <-> XMR Atomic Swaps

### ISSUE THREAD

**Issue by dginovker** [bisq-network/proposals#353]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

This proposal is to add BTC <-> XMR swaps to Bisq. This follows recent developments regarding the first BTC <-> XMR [atomic swap](https://github.com/comit-network/xmr-btc-swap) implementation and the 1.8.0 Bisq release featuring the first atomic swaps on the exchange.

Note- I'm making this proposal out of strong interest I've seen elsewhere, I'm not particularly interested myself

## Cost

I'll personally be putting $50 towards this proposal, and if the Monero community is interested they can increase the bounty here: https://bounties.monero.social/posts/46/add-monero-btc-atomic-swaps-to-bisq

Edit: According to the Monero Observer, proper etiquette for using bounties.monero.social is to post in the related bounty your intention to work on and claim the bounty ahead of time (to prevent duplicate efforts). Bounty currently sits at 0.27 XMR

**Comment by MwithM** [comment]
I think that this is a feature all of us we would be like to have implemented, specially if it could work as smoot as in BTC/BSQ swap. Now, at least we have a UX model for how BTC/XMR swaps could be implemented at Bisq.
But I think that this is even a higher technical challenge since two different chains need to be able to communicate between each other, and I would like to see a more detailed proposal.

**Comment by chimp1984** [comment]
Thanks for the proposal. Atomic cross chain swaps is on the roadmap for Bisq 2. 

BSQ swaps are a very different thing as BSQ is technically Bitcoin, so a swap is just a bitcoin transactions swapping the inputs and outputs. 

The XMR-BTC swap is a very sophisticated project and as far we follow the farcaster project it will still take a bit until it is considered final from their side.

**Comment by flix1** [comment]
BTC <-> XMR Atomic Swaps would absolutely be a great thing for Bisq to have. 

However as chimp says, it is technically difficult. Others like Haveno (https://haveno.exchange/) and COMIT (https://comit.network) are also working on it and running into many difficulties... however if they manage to get it done, since they are open source, it might be possible to use what they have learned.

**Comment by pazza83** [comment]
There is consensus to add atomic cross-chain swaps for BTC <-> XMR. 

I am sure this proposal will be addressed again in the future.

**Comment by sx7maan** [comment]
Hi i would like to if this proposal is still ON or not , iev been working on something similiar for a while ?

**Comment by HenrikJannsen** [comment]
I think at the moment we have no capacity to take on such a big project. But if you can share some links to the work or yours would be appreciated.
