### ISSUE TITLE
Update "Penalties table" page on Wiki

### ISSUE THREAD

**Issue by w0000000t** [bisq-network/proposals#360]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

During the first support meeting call of 2022, the idea of a new approach to penalties, and a new format of the "Table of penalties" wiki article, has been discussed. 

Following this, me and @MwithM collaborated to prepare a new version of the table that is shorter, easier to read and understand, and also allows partial judgment to the mediator, in order to evaluate the severity of each situation and choose a penalty percentage according to that, "up to" the defined percentages.

The proposed new version of the article can be found [here](https://gist.github.com/w0000000t/6d9ba235578a4fbcbf01154f491f8119), please share your opinion.

**Comment by MwithM** [comment]
The main idea for this update was to simplify the penalties by creating a document that can fit most of the cases, instead of a document where all possible cases are included.

- Penalties shared between buyers and sellers have been merged.
- Most delays are the same, as traders tend to select the excuse with a smaller penalty. There is no increment on the penalties depending on how big the delay is because suggestions can't be enforced and traders can delay a trade even more after a ticket is closed.
- There are two categories for setting a wrong payment reference instead of three. One is those referred to Bitcoin, and the other is any unagreed payment reference (depending on the case, any unagreed payment reference might be concerning for the seller).
- Percentages are very similar to the current version. I find them too big in general, but we propose to left them as they're now, because they indicate a top limit which can be reduced depending on every specific cases.

I find that we need to add the following:
- Mentioning that traders can reach an agreement on the payout. Although this could be added at the [mediation](https://bisq.wiki/Dispute_resolution#Level_2:_Mediation) section of the wiki.
- Links to [trading rules](https://bisq.wiki/Trading_rules) and [dispute resolution](https://bisq.wiki/Dispute_resolution#Level_2:_Mediation).

**Comment by pazza83** [comment]
> Mentioning that traders can reach an agreement on the payout. Although this could be added at the mediation section of the wiki.

Yes I think this is good practice. If more traders start doing this then it will facilitate a scenario where traders can sign the payout transactions themselves (with agreed compensation), therefore, avoiding mediation and speeding up trades.

**Comment by pazza83** [comment]
Thanks @w0000000t and @MwithM for updating this. It looks much improved.

**Comment by w0000000t** [comment]
> > Mentioning that traders can reach an agreement on the payout. Although this could be added at the mediation section of the wiki.
> 
> Yes I think this is good practice. If more traders start doing this then it will facilitate a scenario where traders can sign the payout transactions themselves (with agreed compensation), therefore, avoiding mediation and speeding up trades.

This might be out of the scope of the _Penalties_ article, and be more appropriately added in the [trading rules](https://bisq.wiki/Trading_rules) section, at least in my opinion; then the _Penalties_ could briefly reference this

**Comment by pazza83** [comment]
I think traders discussing and agreeing penalties / compensation between them is within the scope of the article.

The article should be used as a guideline but if traders agree between them something different that is fine and even preferred.

**Comment by w0000000t** [comment]
I'll make some edits to reflect that, so we can discuss about wording and placement

**Comment by w0000000t** [comment]
Closing as implemented
