### ISSUE TITLE
Increase BTC trading fee to 1% of trade amount

### ISSUE THREAD

**Issue by MwithM** [bisq-network/proposals#365]
### Rationale

Getting BSQ to pay trading fees has very little friction since BSQ swaps were implemented.
Bisq needs to increase the use of BSQ. Currentlly, only around 30% of trading fees [come from BSQ](https://github.com/bisq-network/roles/issues/111#issuecomment-1000632728). BSQ is essential for a decentralized distribution of Bisq's revenue. 
From January comptroller's data, Bisq collected 0.66% of total trade revenue, which seems ok but not very high. Current BTC trading fee is 0.8%.

The main goal of this proposal is to increase the rate of trading fees paid in BSQ vs paid in BTC to a 50-60% of total volume in the next 3 cycles. If traders keep using BTC to pay their trading fees, total trade revenue will be higher than current 0.66%.
I don't think there is a big risk of traders stop using Bisq due to high trading fees, since swapping BSQ to pay their trading fees is a simple and cheap option.

### Proposal

I propose to increase BTC trading fees to 1% total. 
Maker trading fee paid in BTC per 1 BTC traded: 0.0012 (0.12%)
Taker trading fee paid in BTC per 1 BTC traded: 0.0088 (0.88%)

This is how the table at the [wiki](https://bisq.wiki/Trading_fees) would look like:

**Trading fees per 1 BTC**
||BTC   |BSQ  |
|------|------|-----|
|Maker |0,0012|16,8 |
|Taker |0,0088|123,2|

For BSQ, current price is considered: 43000 USD/BTC and 30D WMA is 1.23 USD/BTC.

Paying trading fees in BSQ would suppose a 60% discount, instead of the current 50% as BSQ trading fees would remain at 0.4%.

**Comment by pazza83** [comment]
Thanks for creating this proposal.

I am in support of this as it aims to both incentivize more users to use BSQ and increase revenue for DAO from users that use BTC to pay fees.

**Comment by chimp1984** [comment]
The BSQ fees are not increases? I think both should increase so that Bisq gets an average fee of 0.8% instead of the current 0.66%. I think a fee increase of about 20% for bith BTC and BSQ would bring it closer to the target.

**Comment by pazza83** [comment]
I did the sums for Jan 2022 with the trade fees above.

Assuming 1% BTC trade fee:

BSQ X% discount trade fees would increase from 0.66% ​to X%

- 60% discount = 0.76% average trade fees
- 55% discount = 0.80% average trade fees
- 50% discount = 0.84% average trade fees

**Comment by chimp1984** [comment]
Why not stick with the 50% discount? With higher BTC fees some traders might move over to BSQ which would lower the overall fees, so a slight "overshoot" might compensate that tendency, as well as compensate to the past 'undershoot' of our target.

**Comment by MwithM** [comment]
If 50% of trades were paid with BSQ, the total income from trading fees would be 0.7% of total volume. If 60% of trading fees were paid with BSQ, total trading fees would be 0.64% of total trading volume.
I think that at that point is when Bisq should evaluate to increase the BSQ trading fee to 0.5%.

**Comment by chimp1984** [comment]
FYI my comment on an older discussion re 15% cap: https://github.com/bisq-network/proposals/issues/333#issuecomment-1037277577

I think we should try to get asap to the 0.4% per trader (0.8% total) fee revenue target. How to get there in details I dont care so much, but that we have been so long below that target was not intentional but from our lack of accounting/checking business numbers. 
So I think we should adjust each cycle to hit that 0.8%.

**Comment by MwithM** [comment]
I agree with removing the self-imposed maximum allowed 15% raise in BSQ trading fee update.
@jmacxx Do you agree with removing it for good? If the 60% discount target is accepted for this cycle, I would update the BSQ trading fee when BSQ discount is not within the 55-65% range, to restore the 60% target.

I might accept that Bisq should head towards a higher trading fees. 0.8% seems a nice target, but I think it's better that this changes are done gradually and slowly. I am going to edit the top post to review the trading fees every 3 cycles instead of 6, probably a new raise will be proposed then.

**Comment by flix1** [comment]
Agree that fees should be raised for BTC. 

Agree that changes should be gradual and incremental over several cycles, that should allow users to react and/or complain. Surprise, unilateral changes in economic conditions can cause a lot of anger, especially if they were not previously discussed.  Gradual changes also allow for measurement.

We need to test the hypothesis that "higher BTC fees --> higher % BSQ use".

Maybe the key component is the discount... and what we should do is increase that in parallel with fees so that BSQ fee is only 25% of BTC fee.

I would be OK with an eventual fee pressure of **1.6%** in BTC and **0.4%** in BSQ as long as the adjustment is over several cycles.

If 60% of users continue to pay in BTC and 40% in BSQ, that would lead to an average revenue of 
(0.6 x 0.016) + (0.4 x 0.004) = 0.0096 + 0.0016 = 0.0112 = 1.12% of volume. 

Of course my preferred strategy to increase revenue would not be to increase fees, but to increase volume. Double the volume, double the revenue... but that will probably not happen over the next 3 months.

**Comment by MwithM** [comment]
I have sent to DAO voting the Bitcoin trading fee change parameter proposals:
- For maker, the TXID is: `c3a9445a2c2e6f2a6e9edbad2a32694366ee44dc3b1c472649ade30ed07d5dbd`
- For taker, the TXID is: `a503475acd1f55866f9edd8757ce6e435835bde468401a453760f09a86774e11`

I consider the secondary proposal to remove the self imposed 15% cap for increasing BSQ trading fees as accepted, I am updating the [wiki](https://bisq.wiki/Updating_BSQ_trading_fees) to reflect that limit removal and will update the changes needed when the above proposals are accepted on the DAO.
I am calculating the new BSQ trading fees assuming that this proposal will be accepted.

**Comment by pazza83** [comment]
Both proposals were approved by DAO vote in cycle 33

**Comment by MwithM** [comment]
[Wiki](https://bisq.wiki/trading_fees) has been updated to reflect this changes.

Closing as approved.

**Comment by apemithrandir** [comment]
> @flix1 
> I would be OK with an eventual fee pressure of **1.6%** in BTC and **0.4%** in BSQ as long as the adjustment is over several cycles.
> 
> If 60% of users continue to pay in BTC and 40% in BSQ, that would lead to an average revenue of (0.6 x 0.016) + (0.4 x 0.004) = 0.0096 + 0.0016 = 0.0112 = 1.12% of volume.
> 
> Of course my preferred strategy to increase revenue would not be to increase fees, but to increase volume. Double the volume, double the revenue... but that will probably not happen over the next 3 months.

I like having the option to pay fees at a discount and we certainly need something like that to remain competitive. I will say, it took my a little while to realise that I could pay in BSQ and then swap some BTC for BSQ to do as such. Embarrassingly it also took me longer to realise that maker fees were a small fraction of taker fees.

The lowest fees possible of a maker paying fees in BSQ, 0.12%*40% = 0.048%, are very competitive and even the highest possible fees of taker paying fees in BTC 0.88% are not crazy at the moment. Concerns would arise when the highest possible fees of taker paying fees in BTC approach 1.6%*0.88 = 1.408%, this would put Bisq at a big outlier vs other venues:
- [CEX](https://www.cointracker.io/blog/2019-crypto-exchange-fee-comparison), [HodlHodl](https://hodlhodl.com/pages/faq), [LocalMonero](https://localmonero.co/fee?language=en), [LocalBitcoins](https://localbitcoins.com/fees), [LocalCoinSwap](https://localcoinswap.com/fees)

Regardless of how well informed people are, the default for new users on Bisq will be trading as a taker and paying fees in BTC. While the savvy frequent user will trade as a maker paying fees in BSQ, I wouldn't want to punish the new users with a 1.4% fee which might make it so they don't come back again, or worse look at the fee and decide not to trade at all.

I would be against pushing the total fee above 1%, since none of Bisq's competitors (see links above) have ventured that high. If you account for the all-in costs including the bid-ask spread, premium bias in pricing for buyers, mining fees and trading fees this can act as a serious deterrent for new users.

**Comment by chimp1984** [comment]
Good points! I think we also have to consider that new users are mostly Fiat traders with low amounts, so higher fees there will not make a lot of difference in revenue but high fee % might turn off new users. A better strategy might be to try to get better fee rate from the large volume traders. They will benefit currently by being maker and paying in BSQ and with higher amounts the share of miner fee is also much less. I think in that segment we should try to raise fees.

**Comment by apemithrandir** [comment]
Trying to charge a higher fee to large volume traders can be tricky:
- They are engaging in high volume purely to make a profit (as a market maker)
- They will respond by widening their bid-ask spreads to reflect the increased fees
- Wider spread means less trades
- This can lead to a drop in taker fees and overall fee revenue

CEX's often waive fees for high volume traders (market makers) all together so that they can improve liquidity. Considering that Bisq greatly needs liquidity I wouldn't recommend trying to raise fees on high volume traders. 
If you examine carefully the links I provided, I would say that Bisq is roughly in-line with the other venues in terms of fees.

Unfortunately, there are no easy wins to be made from adjusting the fee structure. Instead the increased revenue will have to come from hard fought increases in adoption and subsequently improved volume.

Are we currently struggling to cover costs with the existing revenue? Is there a great desire to increase fees further? I think one should always assume that an increase in fees without an increase in adoption will always result in lower volume and thus the assumed increase in revenue from such fee increases are often overestimated.

**Comment by flix1** [comment]
Very good points @apemithrandir. Looking at fees charged by the competition is essential.  

> [CEX](https://www.cointracker.io/blog/2019-crypto-exchange-fee-comparison), [HodlHodl](https://hodlhodl.com/pages/faq), [LocalMonero](https://localmonero.co/fee?language=en), [LocalBitcoins](https://localbitcoins.com/fees), [LocalCoinSwap](https://localcoinswap.com/fees)

**Comment by MwithM** [comment]
it worries me that @apemithrandir didn't know about trading fee structure and derivations.
Any regular trader (to me, that's anyone planning to do at least 1 trade per week) should use BSQ and the incentives to do so are already there. But they need to know they have this option, otherwise they will just fly away, or not coming.

A red, simple "use BSQ to pay less trading fees" popup should appear when taking an offer.
![image](https://user-images.githubusercontent.com/50149324/159924566-dfdebf93-6dc2-45ce-a1d0-26d18382cb4f.png)

For makers, trading fee is more an antispam measure. It's paid wether or not the offer gets taken, that's why it's so reduced compared to takers so it should not be raised very much.

**Comment by MwithM** [comment]
Another consequence of the trading fee structure is that at markets with good volume, negative spreads should be the norm. We are almost there, the outlier is a F2F offer which is on a particular market on it's own, but here on EUR we have a -0.1% spread.
![image](https://user-images.githubusercontent.com/50149324/159929285-e89e0b41-a1d5-40ae-bdb0-6052b804e188.png)

**Comment by apemithrandir** [comment]
> it worries me that @apemithrandir didn't know about trading fee structure and derivations. Any regular trader (to me, that's anyone planning to do at least 1 trade per week) should use BSQ and the incentives to do so are already there. But they need to know they have this option, otherwise they will just fly away, or not coming.

I did a few offers without knowing and then figured it out. Though I also had to do the extra step of acquiring some BSQ. Maybe a link to the BSQ market from the offer page would help with this (though not completely necessary)?

I also found I had to end up buying way more BSQ than I needed due to the min sizes on the BSQ market. Like if a pleb is stacking a few hundred $'s per week they only need around $20 of BSQ for a year of stacking. I'm not sure if there is a more straight forward way for people to acquire small amounts of BSQ.

Edit: Also I guess doing a small amount of BSQ will have a high % paid as a mining fee but I guess that isn't a big deal vs the fee savings on the real BTC trades.

**Comment by clearwater-trust** [comment]
What is going on here? 
https://github.com/bisq-network/bisq/issues/4579

**Comment by MwithM** [comment]
Yes, buying small amounts of BSQ is still an issue, although it has improved a lot since BSQ swaps.

**Comment by apemithrandir** [comment]
> Yes, buying small amounts of BSQ is still an issue, although it has improved a lot since BSQ swaps.

For the last 3 days as an experiment I started showing offers in small size in BSQ, and I've managed to trade around 10 times as a maker. These trades have been mostly against unique counterparties, so supports the idea that they are people just looking to get a minimum amount of BSQ for access to lower fees on BTC trades.

This has been fully manual but if I spend a few dozen hours on the [API](https://github.com/bisq-network/bisq/blob/master/apitest/docs/api-beta-test-guide.md), it should be possible for me to provide small size liquidity in BSQ and cover my transaction costs.

The % fees on a 20 BSQ trade are around 2-3% at the moment (pretty much all the mining fee), but it looks as though people are willing to pay up as much as 5% to get this sort of service. So long as I don't lose on a massive price swing it should be possible to show some passive liquidity like this and not lose money.

**Comment by ripcurlx** [comment]
> 

This is already implemented. You only see it if you don't have enough BSQ to pay the trading fee at hand.

EDIT: I just checked the code and tested it and it seems it doesn't work as expected right now 🤦 .

It should look like this

<img width="852" alt="Bildschirmfoto 2022-03-28 um 12 30 12" src="https://user-images.githubusercontent.com/170962/160380157-7f5103af-f34f-461e-a5d2-d4b402cb3455.png">
<img width="1660" alt="Bildschirmfoto 2022-03-28 um 12 30 23" src="https://user-images.githubusercontent.com/170962/160380167-88912982-57a1-4ab8-8c7c-782a3df189da.png">

I'm preparing a fix PR as we speak.

**Comment by ripcurlx** [comment]
It did work for create offer as expected, but not for take offer.

**Comment by ripcurlx** [comment]
https://github.com/bisq-network/bisq/pull/6121
