### ISSUE TITLE
Increase Support Compensation

### ISSUE THREAD

**Issue by leo816** [bisq-network/proposals#368]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

Bisq has a history of contributors disappearing due to lack of incentive or sense of coordination within bisq as a unit. In order to incentivize the support team and reward consistency in contribution to the project (as well as inflation) I suggest increasing the compensation after 6 months of consistent contribution so that it would look:

| Role | Current Compensation | New Compensation | 
| --- | --- | --- |
| Burning man | 1000 | **1100** | 
| Mediator | 1000 | **1100**  |  
| Refund Agent | 50 USD per case fee + 1% per cycle interest rate for BTC paid out + 3.3% issuance fee for BSQ requested  |  **55** per case fee + 1% per cycle interest rate for BTC paid out + 3.3% issuance fee for BSQ requested|  
| Support Agent | 500 |  **600** |
| Support interns:  | 0 |  0 |
| Fee Reimbursement Agent | 300 USD (plus fees) | **350** (plus fees) |
| Support Team Lead | 0 | **300** |

**Comment by refund-agent2** [comment]
1. I prefer to have this structure: **50 +1.1%**. 50 USD per case is enough, I get much more low amounts than big amounts to reimburse and arbitration fee covers a bigger part of the cost for higher volume trades, while is insufficient for low amounts. The rest (+1.1%) is the cost of "lending" BTC to Bisq and I find it ok to increase it, specially since after a year I roughly have benefits.
2. Issuance fee (I prefer to call it printing cost) is not part of compensation, it's reimbursement. It's not exactly 3.3% but a cost calculated every cycle depending on BSQ price. Traders will be reimbursed considering this printing cost as well. https://github.com/bisq-network/support/issues/1052

**Comment by pazza83** [comment]
Closing as approved:

Tagging in @refund-agent2, @burningman3 so they can see to up their compensation requests
