### ISSUE TITLE
Compensation and valuation of translations/reviews

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/proposals#37]
Based on discussions in compensation requests https://github.com/bisq-network/compensation/issues/96 and https://github.com/bisq-network/compensation/issues/95 we should decide on how we want to proceed with translation/review compensation before next voting round.

@BravoIndia, @HarryMacfinned and @ripcurlx had a call on this topic last Sunday with following outcome:

## Compensation
Translation and review contributions are up for compensation when following criteria is met:
- Language must be included in the Bisq desktop client or
> added based on discussions below:
- Language was whitelisted by contributor consensus

For languages that are not included within the client the translator/reviewer is advised to spark a discussion in the #transifex channel why this new language should be integrated (e.g. translator also acts as market maker for this market). Decision is made on a case-by-case basis. As soon as language is included within the Bisq client it is up for compensation.

If this one criteria is met all translations that are done in Transifex are up for compensation even if they have not been released yet. We plan to release once a month and all translations will be updated by the [Transifex admin](https://github.com/bisq-network/roles/issues/20) anyways before each release.

## Valuation
As it would be quite complicated to come up with a perfect formular to calculate the compensation amount we'll do it as usual and let it evolve organically out of compensation requests. This should give new translators/reviewers an idea what to expect for compensation.

**Comment by ripcurlx** [comment]
@BravoIndia
I didn't put if partial translations or done translations are up for compensation for a vote as both would be up for compensation if the language is already included within the Bisq client.

**Comment by ripcurlx** [comment]
@BravoIndia, @HarryMacfinned: Did I miss something important that should be put up for a vote?

I didn't included everything we discussed (quality improvements,...) in the proposal only what is needed to be voted on.

**Comment by ManfredKarrer** [comment]
Sounds good to me!

**Comment by BravoIndia** [comment]
@ripcurlx Thank you again for having me on the call and for writing up this proposal.

I believe you left out @HarryMacfinned's suggestion in order to make organic valuations practical: 

> Begin with a small first bunch, eg 300/500 words, make your compensation request for that,
> and tell what are your following plans (and the associated comp. request)
> So you'll know precisely 1/ if stakeholders agree or not with the compensation and 2/ with your plan
> and if it's worth for you to continue.

And in my opinion I think there should be a vote on whether translation work is compensated when:

- Partial translation on Transifex
- Threshold translation on Transifex (say ~50%)
- Full translation on Transifex
- Released translation on Bisq client

As I said in the call, if partial translations are not compensated then organic valuations won't work, because @HarryMacfinned's proposal can't be implemented. Practically speaking, the two are mutually exclusive. It's either a well-defined valuation criteria compensated on release, or an organic valuation that allows for people to submit exploratory requests on initial work.

There is a reason Transifex has been practically barren in the past few months until @initCCG showed up--and it seems from their responses that they've done all of their incredible contribution at great personal risk and expense because they were under the **completely false impression** they'd get much higher compensation for their work.

I don't see that happening again without either:

- partial translations being compensated + organic valuations (allowing for initial 'feeler' requests).
Or
- pre-determined valuations + compensation only upon translation completion.

In my opinion you're guarantying Transifex will return to how it was before June without enacting one of these two. Just look at the evidence:

![untitled](https://user-images.githubusercontent.com/33473721/44615396-aba8df80-a863-11e8-90dc-a094ef100c8c.jpg)

This seems to me to be a complete waste of considerable potential added-value to Bisq at remarkably low cost (Does anybody not think each full translation adds at least $10,000 to a hypothetical Bisq client valuation? Well, @initCCG translated 3 languages for $1,000!). Yet we insist on adding hurdles at every turn--now we won't compensate translation work if the translators aren't market makers too?!

There are also other problems. Such as how compensating only upon release and not upon full translation on Transifex incentivizes premature release and arbitration risk (e.g. avoiding good practices, like ensuring a language is reviewed by a separate entity). Why do this? Compensate well done translation work, and then work carefully to determine the best time to release the language, taking into consideration market-making resources, review quality, arbitration resources, encoding & character limitation, etc.--all the time having the completed translation at your disposal. 

As well as many other such points I've made on the call and in previous threads. Frankly, I'm just repeating myself here and making comprehensive, coherent arguments that don't seem as though they'd be addressed. So I suggest putting it the above to a vote (4 options when to compensate and valuation criteria), and if the community decides to only compensate upon release--which I expect they likely will, we'll just see the results on Transifex.

In any case, I acknowledge that development work is (of course) the priority here. So I'd be content with bringing this issue to a close. Thank you all for your thoughts and ideas throughout this discussion and for indulging my long-winded posts.

**Comment by ripcurlx** [comment]
@BravoIndia Thanks for your remarks! 

> Partial translation on Transifex
> Threshold translation on Transifex (say ~50%)
> Full translation on Transifex
> Released translation on Bisq client

Based on my proposal a voting for your requested options would only be required for languages not yet integrated in the Bisq client.

For all languages included:
- English
- German
- Russian
- Spanish
- Greek
- Hungarian
- Romanian
- Portuguese
- Chinese (simplified)
- Serbian
- French
- Persian, Thai, Vietnamese (included but not enabled yet)

there is no other pre-condition to get compensated than doing translations or reviews in Transifex (no matter how much). People can translate as little or as much they want, of course it makes sense to do a small translation first and request compensation to see if there is a match in the expected and received compensation.

The requirements for adding new languages is not so easy to draft, as we don't want to encourage translation bureaus to translate any language they want no matter if it makes sense to get included in Bisq or not. That's the point why I think it is better to do this in a case-by-case basis. So if someone wants to do translations in a language that is not included in Bisq yet she should first check in Slack or GitHub if it would get included into the client or not. @BravoIndia What's your point on that?

**Comment by BravoIndia** [comment]
@ripcurlx If someone wishes to include a new language in Bisq, and they confirm on Slack or Github that it is appropriate for inclusion in the client, will they be able to:

> do a small translation first and request compensation to see if there is a match in the expected and received compensation   ?

Otherwise I agree with your proposal for languages already integrated in the Bisq client as you listed.

**Comment by ripcurlx** [comment]
@BravoIndia If someone gets the ok from contributors side that the language is a match for Bisq I think it would be ok that she also gets compensated for partial work in Transifex. If it is misused and we are ending up with half translated languages we will need to go back to the limitation that only included languages are up for compensation. Let's see how it turns out over the next couple of months.

**Comment by BravoIndia** [comment]
That's acceptable in my opinion @ripcurlx . I think at least one initial compensation request should be allowed just to give the contributor a gauge of the organic valuation's merit. And I agree with your misuse criteria as well. Thanks for the edit.

**Comment by ripcurlx** [comment]
If there aren't any votes opinions against it I'll close the proposal as accepted.
