### ISSUE TITLE
Limit trade size to refundagent refund size

### ISSUE THREAD

**Issue by onlymarcus** [bisq-network/proposals#413]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

On the bisq platform, trades are limited to a maximum of 2 bitcoins per transaction. However, if a trade goes to mediation and arbitration, the winning party only receives a refund of up to 0.5 BTC from the refundagent, with the remaining 1.5 BTC plus the security deposit being paid in BSQ. Unfortunately, due to the end of the burningman function, there is not enough liquidity for the winning party to sell all their BSQ and convert it into bitcoins for new trades. This negatively impacts the bitcoin buyer who pays with XMR, as the seller receives all the XMR for the trade, but does not release the bitcoins to the buyer and stops responding to the mediator and arbitrator, possibly for technical or personal reasons.

This also impacts the BSQ price, as the selling volume suddenly exceeds the buy limit and the selling force pushes the price lower. When there was burningman, he absorbed the sales force.

To address this issue, a proposal has been made to limit the maximum trade amount in the BTC/XMR pair to 0.5 BTC, since the refundagent can only refund up to 0.5 BTC in case of an arbitration. This proposal aims to enhance the safety of Bisq users and reduce the risk of spending several days trying to sell their BSQs, in addition to the time spent waiting for the arbitration decision.

References:

[Proposal Issues 386](https://github.com/bisq-network/proposals/issues/386)
[Reimbursement 1355](https://github.com/bisq-network/support/issues/1355?utm_source=desktop-client&utm_medium=in-app-link&utm_campaign=language_en)

Look at the difference in liquidity between buyers and sellers of BSQ:
![image](https://user-images.githubusercontent.com/36059034/231306624-9b47d984-ae9d-4b9e-9e94-3e5fbaedffd1.png)

**Comment by leo816** [comment]
I like this idea, here are some thoughts: 
- As @MwithM pointed out, the 2 BTC limit was set when BTC was well below 10k usd, therefore even now reducing it to 0.5 BTC is still a big increase in USD terms, so in favor of this.
- I believe the reason why the reimbursement limit was set was for two reasons 1. because for the refund agent to reimburse 2 BTC + deposits every time comes at a big cost for one person and 2. Because it would require months of bisq's fees to repay traders in case a mistake was made. 
Therefore, why not just add another refund agent in addition to this measure? anyways it's unreasonable to think that as bisq scales one refund agent will be enough. (even though bisq 2.0 will potentially re-direct trades to bisq easy and lightning)

**Comment by pazza83** [comment]
I agree that the currently model of reimbursing high value trades is not working for traders however I am not a fan of limiting the trade size.

Instead I think the underlying issue of traders only being [partially reimbursed for high volume trades ](https://github.com/bisq-network/proposals/issues/296) should be addressed by adding another Refund Agent to the DAO. This way traders can reimbursed in full.

Maybe a second refund agent could have a role where they only get involved in reimbursing high value trades. The reduction in the case numbers would therefore reduce the chance of an error occurring. 

The second refund agent could also have a BTC address that received a fixed percentage of payments from BTC trade fees and delayed payout transactions. The reimbursements could then be paid from this wallet. The filter could be adjusted as needed. They would have to have a BSQ bond that was greater than the value of the BTC they would likely hold at any one time. The role would be protected from an attack from them self trading by keeping the percentage filter under 11%. If needed more than one of these Refund Agents could be added. The role could be preformed quarterly to keep costs lower for the DAO.

**Comment by onlymarcus** [comment]
> I agree that the currently model of reimbursing high value trades is not working for traders however I am not a fan of limiting the trade size.
> 
> Instead I think the underlying issue of traders only being [partially reimbursed for high volume trades ](https://github.com/bisq-network/proposals/issues/296) should be addressed by adding another Refund Agent to the DAO. This way traders can reimbursed in full.
> 
> Maybe a second refund agent could have a role where they only get involved in reimbursing high value trades. The reduction in the case numbers would therefore reduce the chance of an error occurring.
> 
> The second refund agent could also have a BTC address that received a fixed percentage of payments from BTC trade fees and delayed payout transactions. The reimbursements could then be paid from this wallet. The filter could be adjusted as needed. They would have to have a BSQ bond that was greater than the value of the BTC they would likely hold at any one time. The role would be protected from an attack from them self trading by keeping the percentage filter under 11%. If needed more than one of these Refund Agents could be added. The role could be preformed quarterly to keep costs lower for the DAO.

Adding another Refund Agent to DAO, each can refund up to 0.5 BTC, so the trade limit would be 1 BTC.
The important thing is that the trade size is limited to the amount that the sum of Refund agent refunds can support.

**Comment by pazza83** [comment]
Agreed, but I would like to see traders reimbursed in full is possible for 2 BTC trades and everything below that.

**Comment by refund-agent2** [comment]
At least, a message should be displayed when users raise the trading limit over 0.5 BTC.

4 trades for 0.5BTC is the same as one 2 BTC trade, the limit to pay 0.5 BTC was set to reduce a fatal mistake from my part and also so I wouldn't get out of funds.
I doubt it's gonna be easy to find more refund agents right now, but I like the general idea of separating reimbursements and arbitration. Most of the cases don't need much investigation and only need the payout.

**Comment by pazza83** [comment]
Marking this as approved, but will leave open for discussion about how this should be implemented.

**Comment by ghost** [comment]
My worry is that limiting trade amount further could drive certain users away.
Maybe 2.0 BTC offers in the altcoin marketplace are more attractive than 0.5.  

A user can choose their own limit.  Since recently the limit starts at [0.1 and has to be consciously raised by the user](https://bisq.wiki/Account_limits#New_user_opt-out_limits).  There's no need to further restrict **other people** in the amounts they voluntarily trade.  To protect all users, the suggestion above from refund-agent makes sense: "_a message should be displayed when users raise the trading limit over 0.5..._".  To also protect legacy users who may have inherited a high limit based on their past activity, the message could be displayed if necessary at startup with an `I understand` button and `don't show again` option.

Maybe something along the lines of "`You have a x.xx BTC trade limit.  Please be aware when trading trade high amounts in Bisq, arbitration refunds are likely to be partially issued in BSQ by the DAO.  You should consider limiting your trade size to 0.5 BTC in order to avoid potential inconvenience should arbitration be necessary.  You can change your trade limit in the Bisq settings screen.`  [+ link to a bisq wiki page detailing the refund process]"

**Comment by suddenwhipvapor** [comment]
> You have a x.xx BTC trade limit. Please be aware when trading trade high amounts in Bisq, arbitration refunds are likely to be partially issued in BSQ by the DAO. You should consider limiting your trade size to 0.5 BTC in order to avoid potential inconvenience should arbitration be necessary. You can change your trade limit in the Bisq settings screen.

I am in favour of letting users plan their trading as they prefer, while obviously taking responsibility for it.
If I can get a knack at writing the popup message, it would be like:
`New arbitration rules dictate that refunds for trades over 0.5BTC will be partially paid in BSQ. If you want refunds to be entirely paid in BTC, please set a trade limit of max 0.5BTC in Settings.`

**Comment by onlymarcus** [comment]
> > You have a x.xx BTC trade limit. Please be aware when trading trade high amounts in Bisq, arbitration refunds are likely to be partially issued in BSQ by the DAO. You should consider limiting your trade size to 0.5 BTC in order to avoid potential inconvenience should arbitration be necessary. You can change your trade limit in the Bisq settings screen.
> 
> I am in favour of letting users plan their trading as they prefer, while obviously taking responsibility for it. If I can get a knack at writing the popup message, it would be like: `New arbitration rules dictate that refunds for trades over 0.5BTC will be partially paid in BSQ. If you want refunds to be entirely paid in BTC, please set a trade limit of max 0.5BTC in Settings.`

This way it is unfair. How are all the people who were harmed by the reimbursement in BSQ? I received 0.65 BTC in BSQ and I am not able to sell these BSQ for the average price I received, but I am 35% behind.
It is unfair to those who have already harmed themselves. Since I didn't get that message letting me know that I wouldn't be refunded in BTC, then you should in fairness refund me.

**Comment by onlymarcus** [comment]
Only now after 10 months I managed to sell all the bsq at a loss. I opened two trades selling XMR. Two offers of 0.5 BTC on the XMR/BTC pair. Once again they took my orders, I paid the XMR and the trader stopped responding. Will I be harmed again after 10 months of trying to sell BSQ after a case like this? I should receive the 15% from the other party as compensation.
