### ISSUE TITLE
Reduce bond amount for bonded roles

### ISSUE THREAD

**Issue by suddenwhipvapor** [bisq-network/proposals#468]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

Following #467 it is also reasonable to decrease by half the bond amount for new roles.

I am waiting to receive my mediator key to register on the network as per #464  and considering the fiat-value of a 5000BSQ bond, and how I already posted a 5000BSQ bond as Bisq2 moderator, I propose to post a 2500BSQ bond as Bisq1 mediator.

**Comment by MwithM** [comment]
Just for reference, at ~2.5USD/BSQ, 2500 BSQ equals 6250 USD.

**Comment by suddenwhipvapor** [comment]
Indeed, I believe that was the fiat value of my Bisq2 mediator bond when I posted it.

**Comment by HenrikJannsen** [comment]
I understand that with increasing BSQ price the burden for the bond gets higher, though the BSQ has not changed that dramatically (as BTC price). To change the DAO parameters comes with considerable test effort and carries some risk for a hard fork. That's why we are very conservative with changing anything there is not absolutely needed.

**Comment by suddenwhipvapor** [comment]
Oh, I get it, I will go ahead closing the proposal now in this case
