### ISSUE TITLE
Launch initiative to educate users about the DAO

### ISSUE THREAD

**Issue by m52go** [bisq-network/proposals#56]
> This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html).

_This isn't a typical proposal, but I figured it worth writing to convey the initiative and its significance, garner feedback, and perhaps invite some more talent to execute it._

The DAO, BSQ token, and related concepts are intriguing, but they're not intuitive. The DAO—no matter how technically and conceptually robust―won't work if people don't buy BSQ to put it in motion (perhaps even worse, that they're driven away from the project from a misguided notion that Bisq is releasing its own scam token, etc).

Therefore it is critical that we do all we can to explain the DAO as clearly as possible _before it launches_.

I've been in touch with folks in and out of the project this week to discuss a good approach for doing this. What follows is a proposal that includes the insights I gained to launch a multi-pronged approach at explaining the DAO.

Note that I approach this proposal with the primary mission of _educating_, not _marketing_. With that said, we don't want to take time doing all this work and not maximize the number of people who consume it, so some little amount of marketing perspective would be nice.

If you've got experience with content strategy or video production or infographic design or anything else that might be helpful to complete the items below it would be great to hear your perspectives.

I propose we take the following measures to launch an educational initiative for the DAO, in (roughly) descending order of importance:

**3-5 part blog series on bisq.network/blog** 

- Mandate: break the DAO down into 3-5 discrete concepts and form them into 3-5 concise methodical posts so people can more easily understand the concepts. It will integrate key information from the Phase Zero doc, the DAO technical specification doc, and other resources like calls and videos.
- I see this as the the central element of this initiative: emails, tweets, and much other content can be formed from these posts.
- The to-the-point nature of these posts means they could double as PR material for journalists who want to write articles about Bisq so Manfred and others don't have to waste time explaining the same concepts over and over.
- Would be a great way to kick-start the blog again. I think it's important to have Bisq communications published on Bisq-owned platforms where possible (as opposed to on platforms not controlled by Bisq, like Medium, for example).
- May lead to a new role of blogger/writer, since it will be a good opportunity to start publishing to the blog with some regular cadence. I will do the work right now without an official role, but we may want to add one at some point.

**Re-establish email list**

- I propose doing this just as described in #20: use Mailman, send 1-2 emails a month (maximum), and keep the tone straightforward (not promotional).
- For the first few DAO-focused emails we could use the blog series as a foundation for message text.
- @Emzy does anything need to happen from the technical side to make this possible? You [mentioned a while back](https://github.com/bisq-network/proposals/issues/20#issuecomment-388956087) that some work may be involved in migrating the list from MailChimp and enabling a signup form on the website.
- Like the blogger/writer role above, this will probably become its own role at some point ([like it was before](https://github.com/bisq-network/roles/issues/27)), but I'll also do it for now since it aligns well with the job of writing the post series as described above.

**Give talks**

- Digital communication is nice but nothing still beats actually going out and getting in front of people. In fact, I think directing people at an IRL event to a strong digital presence could be powerful. Twitter, Docs, and the new website give us a strong basis already...adding some nice DAO-specific material to those places would make it very strong (more on that below).
- The blog series should provide the basis for a more intuitive way to approach describing the DAO, so it could help people looking to do meetups and conferences. I know I still trip over myself when describing the DAO to total n00bs.
- I'm hammering out details to speak at an event called TABConf in February and considering a number of smaller local events. 
- Having others help with this would be great, I think. @arunasurya [you mentioned](https://github.com/bisq-network/roles/issues/35#issuecomment-423307996) being generally interested in this. Others are welcome too...the more the merrier.

**Infographic / DAO visualization on website**

- I think it's important that people browsing the site are made aware that the DAO is an integral part of Bisq.
- UX perspective: most people probably come to the website and download the software without reading Docs or the Blog. That means there's a considerable chance that they will be blind-sided by BSQ when they go to place a trade.
- I'm thinking some kind of half-page interactive infographic on the front page explaining the main ideas of the BSQ economy could be great. Even if people don't understand it all immediately, just seeing the terms there before seeing them in the software could help prepare them mentally.
- We probably don't need much more than a simple pretty vanilla JavaScript-powered interface to start, which I can do, but if anyone has experience with [D3.js](https://github.com/d3/d3/wiki/Gallery) or similar something more fancy would be fantastic.

**User-facing DAO documentation**

- This is important but probably won't be needed until the DAO is live (unless people think it will be useful to have live for the testnet launch). It will live on docs.bisq.network.
- This differs from the blog series (and existing documentation) in that it's less about _what_ the DAO is and instead provides guidance on _how_ the DAO works from a user's perspective so they can make well-informed decisions about how to best navigate the software.

**Explainers in software**

- We'll probably want to have some explanation / links to explanations of the DAO and BSQ within the desktop software. I'll work with developers on that as needed.

**Medium/personal blog offshoots**

- The blog series on the bisq.network domain will be key, but I think it would be great if other contributors wrote their own offshoots to give the 'official' DAO blog posts some more oomph.
- These could be more editorialized posts that take key DAO concepts and add personal perspective (example: maybe you're fascinated by the idea of systems that thrive on incentives rather than rigid rules, so you could write a "think piece" on that idea and weave in some ideas from the Bisq DAO model).
- Benefit: harness your existing social followings and/or the broader Medium user base (if you publish there) to maximize the reach of the original Bisq blog posts.
- These kinds of opinionated "think piece" posts would be be more easily shareable on social outlets like Twitter and probably Reddit.
- I know this sounds a bit marketing-y, and it's a speculative suggestion on my part, but I think it could be an effective way to evangelize DAO concepts. Thoughts welcome.

**Comment by ManfredKarrer** [comment]
@m52go Great summary!!!!

I agree to all just want to add a few small things...

From our Q&A DAO session (I forgot to record it ;-() I saw that there are 2 main problems of understanding the DAO.
1. Colored coin concept
2. The concept of the issuance transaction (*the contributor is funding his BSQ issunace with a small BTC amount by homself).

I think boths topics are not covered sufficiently in the existing docs and it would be great to get those described in an easy to understand way.

As you mentioned already @arunasurya , I think it would be a good idea that a few people with good communication skills partizipate in that effort. Neiman (I dont know his GH handle) would be also a good candidate and he will present the DAO at FOSDEM conference in February. He helped a lot on the conceptual side and he is working with another developer on the new trade protocol.

**Comment by m52go** [comment]
@ManfredKarrer great!! Yes, those are the exact 2 points I didn't fully understand until that call cleared them up. Those will be top priorities to get right.

I'll see how we can work on gathering more communicators. Maybe we can try Twitter, etc.

**Comment by arunasurya** [comment]
@m52go thank you for taking initiative! I like your ideas and would love to start working together on defining key concepts, including the ones @ManfredKarrer mentioned. I think it is important that we all understand these concepts well and agree on their definitions before presenting them to the rest of the world. I am open to discussing this in greater detail on slack and have a video call.

**Comment by cbeams** [comment]
The plan here sounds great. I'm going to riff below on a topic I think will be important in the education effort. It'll require more discussion and thought than what I'm putting together here, but I'd like to get the ball rolling in any case. 

One thing that's missing from existing documentation, and that smart people will scrutinize, is why BSQ would ever have any value beyond its underlying BTC value. It's important that we avoid accidentally promoting (or believing ourselves) the fallacy that a utility token's value is somehow tied to the value of the project. Potential users of BSQ don't care about the value of the project per se. They care that the BSQ they buy today at a given price is going to be worth the same or more tomorrow, i.e. that it will have the same or better transaction fee purchasing power in the future. For it to do so, there has to be sufficient demand by other users to hold the token so as to keep its value at or above that level. Mere _transactional demand_ isn't enough; there also has to be sufficient _reserve demand,_ i.e. the desire or need to hold the token for longer than it takes just to pay the fees for the next trade. I see several sources of reserve demand in the BSQ economy as we've envisioned it so far:

 1. Bulk-buying and holding BSQ so as to have plenty available for trades over the next days or weeks, as opposed to buying just enough BSQ for the next trade;
 2. Putting up BSQ collateral for time-locked off-chain trading contracts as has been discussed elsewhere;
 3. Holding BSQ for speculative purposes, i.e. holding because one believes the price will increase in the future.

Of these three, I believe (2) is the most important because it involves potentially large amounts of BSQ being locked away for significant periods of time. The more users are doing this, the more BSQ there is tied up over time, creating potentially significant reserve demand. With that said, off-chain trading is something that will come online some time after the initial launch of the Bisq DAO, so it is only a potential future source of reservation demand, not one that we can count on in the beginning.

(1) could become significant as well, but users won't bulk buy in any significant amounts until they trust the token retains its value, so I don't think we should expect much from it in the beginning.

(3) will only become a significant source of reservation demand if users believe that (1) and (2) will generate reservation demand on their own. So it's nothing we have direct control over and I believe should basically be disregarded. We certainly don't want to 'pump' BSQ in any way, i.e. intentionally promote the idea that people should speculate on it. Some will do this on their own, assuming they believe in the project. Our job is to make a credible case for the core economics of BSQ, provide a sound implementation of the system and then let the market do the rest.

I did not include contributor bonding in the list above, because I don't see this as reservation demand in the classical sense. It does reduce the overall amount of BSQ in circulation, but it is not on its own a source of "demand" for BSQ. What's important is that real users—not just contributors—see BSQ as a valuable resource they want to hold and use.

I also have not included in the list above the idea of current BSQ stakeholders forcing a price floor on BSQ by refusing to sell it below a given price (e.g. $1 USD per BSQ). Ultimately, if the market does not see BSQ as being worth $1 per unit, they will bid it down and certain stakeholders will sell at that price, or BSQ will fail altogether because would-be buyers never find willing sellers. As a stakeholder, I think it's good to have a price in mind below which you would not sell, but I think it's also important to accept that we are ultimately at the mercy of our users, and that the process of discovering BSQ's price over time probably will not look like whatever pretty picture we have in our heads. I believe we should be humble as we roll this out, that we should listen closely to the market, and if we're finding the price to be lower than our expectations, to respond by adjusting incentives rather than just doggedly holding out and refusing to sell.

Again, this is just a quick summary of my thoughts on this important topic, and it bears further discussion (probably in some venue other than this proposal). I just want to get the conversation started here, so that as we put together these educational materials we're sure to include in them a coherent and hopefully compelling story about BSQ valuation.

**Comment by m52go** [comment]
@cbeams thanks for that feedback, very thoughtful, and valuation is certainly an important missing element. I hadn't considered (2) before, will investigate.

**Comment by ManfredKarrer** [comment]
@cbeams Thanks for the summary and discussion.
Reagarding point 2: I would not count or involve that at all atm as the concept is still not worked out in detail and it will require a stable and mature DAO/BSQ to enable it. That might take a year that we get there...

The investment motivation is probably the strongest driver and very hard to estimate. Due legal risks we need to avoid to bring that up actively from our side. So I would leave that to the users to figure out themself if it might be an interesting investment opportunity or not.

The fee part is for sure the most important. As we are getting close to break even already I think we should not be too worried that those who understand the whole model are doubting that buying a bit more BSQ as needed. Buying BSQ has also fee costs so to buy just for the next trade would not be very reasonable. 

Another part will be the asset listing fee. Currently we have over 100 coins (which are not traded). Fees will be low initially but I expect that they will get increased by voting soon after the launch. I think a listing fee of 500-1000 USD is reasonable and that would lead with 100 coins to a significant amount of BSQ. 

There is also the burn fee feature which might be used to convert back BTC to BSQ in case the fee payment in BTC stays too high. Maybe that will be used for other features (reputation) as well, but that is not clear enough atm.

The most important is that our users and core followers really understand the model. As I saw in many discussions that is not easy to achieve as there is much resistance against any tokens and many make too quickly assumptions in direction ICO, etc. And of course it carries some complexity and requires some technical understanding. 

So I think we really need to be sure that the majority of our core users understand the model. Many of those are using Bisq despite disadvantages regarding convenience and trade fees, motivated because they want to support such a project. If they understand BSQ they will likely support it by buying BSQ as well.

**Comment by simonmanka** [comment]
Excellent overview. To help with this, I think we need to have a specific target audience (profiles of the readers) for the blog posts. It will help determine the structure of the 3-5 posts and what to include in each one.  Should they be progressive, gaining in complexity as a 5 blog post series? Should they stand alone? Determining who exactly we think the target reader is and why they are reading it will be important and will help us quickly decide all that, and eliminate wasted time and indecision. From a marketing perspective this will help determine where to share the posts etc. as well.

Goals are another key item- I fully support the goal of revamping the email list. However, that should have a few more goals attached to it as far as reach and purpose. A monthly email keeping subscribers updated on Bisq is good, but there are other outcomes that could be important to Bisq which could be helped by a robust email list. For example, driving some viewers to the blog would be good, particularly for new email list subscribers as they may not know much about Bisq and want to learn more. An initial drip of these blog posts via email to new members of the Bisq community could go a long way in making sure those new members and curious people are educated on the platform and don't just fade off into the ether because they just didn't understand it. Thats why we're writing the blog posts and we can use that tool (the blog post explainers) to address that issue.

We should also consider having some moderate goals around how many people we want the monthly email to reach and what is the result we want to have with those emails. In my example in the prior paragraph it's clear we want to help new users find the blog posts which can explain Bisq and answer many questions they might have, but thats one example. Having updates delivered via email is great, but there will be other goals that come up in the future that are important to Bisq that can be met by the email list. Used appropriately, the email list will be an excellent way to have important calls to action seen by the right people. You may have some important calls to action right now i'm not aware of and the email list would be a good distribution method to have those items accomplished. Additionally It would be good to prompt people to subscribe to the email list in a few different places (website etc.) as well because that will be important to Bisq later when marketing becomes more of a priority.

If a non marketing goal is to preserve the leadership team's time by preventing DRY (don't repeat yourself) with media outlets, a media specific kit might be a good option. That kit should likely be updated periodically with roadmap updates, big wins, stats on the growing user base etc. The media is a different consumer of information than a prospective Bisq user, and as such will have different goals for reading it based on what they plan on doing with the information. They of course will need to understand how Bisq works, but they will likely be interested in the future of the project, perhaps the team, and certainly number of users and volume. So a static blog article can only achieve one of those goals-- explaining how it all works and what it's purpose is. It would fail at the goal of providing user statistics etc which the media may be interested in, and they would still reach out to the Bisq team for time/comment as it doesn't hit those goals.

**Comment by simonmanka** [comment]
also-- i'm "OrphanedBlock" @m52go

**Comment by m52go** [comment]
@Emzy any advice for using the email server? I'd like to send an email out by Wednesday to announce the new release.

@simonmanka thanks for the feedback! You made several points I want to discuss more...I'll follow up with you on Slack.

**Comment by Emzy** [comment]
@m52go unfortunately I think the main problem is not technical. The problem is the European GDPR law. 
AFAIK I can't accept a transfer of a list of email addresses to put on my malling list server. The Email addresses are personal data.
The best way would be to ask everyone with the old system to subscript to a new mailing list on my server. 
Or run the server outside of the EU and by someone outside of the EU.

Here some more info to mailing lists and the GDPR:
https://www.mailjet.com/gdpr/email-marketing/

**Comment by m52go** [comment]
@Emzy understood. I think it would be a good idea to prune the existing list anyway since we haven't used it for so long. 

Would you be against using your server to send people that initial message to join the new list? That would be easiest, otherwise we could find another way.

**Comment by Emzy** [comment]
@m52go sorry, but you have to find another way to send the initial message.

**Comment by simonmanka** [comment]
There is a solid open source software called Mautic that would be excellent for managing email announcements and campaigns. I've white-labeled a version, I've white labeled a version of it, I'd recommend it.
