### ISSUE TITLE
Add information about assets doing ICOs to listing requirement

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/proposals#57]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

We should add the requirement to the asset listing to give a statement if the coin was doing or is planning to do an ICO.  

@m52go If we get support for that proposal can you please add that to the docs?

I looked to assets we will ship in 0.9 and I found those 3 assets doing ICOs:
- Quantum Resistant Ledger
- GreenBlockCoin
- Loki
 
Below is a list of all assets. Maybe someone can scan those and we mark those assets as "risk assets". I will make another proposal is we should consider to remove those assets to not expose ourself to legal risks.

See also https://github.com/bisq-network/proposals/issues/58.

New assets (in warming up phase):
Actinium (ACM): Trade amount: 0.00 BTC, number of trades: 0
Bitcoin 2 (BTC2): Trade amount: 0.00 BTC, number of trades: 0
Bitcoin Rhodium (XRC): Trade amount: 0.00 BTC, number of trades: 0
Blur (BLUR): Trade amount: 0.00 BTC, number of trades: 0
Chaucha (CHA): Trade amount: 0.00 BTC, number of trades: 0
Croat (CROAT): Trade amount: 0.00 BTC, number of trades: 0
Dragonglass (DRGL): Trade amount: 0.00 BTC, number of trades: 0
EtherStone (ETHS): Trade amount: 0.00 BTC, number of trades: 0
GreenBlockCoin (GBK): Trade amount: 0.00 BTC, number of trades: 0
Kekcoin (KEK): Trade amount: 0.00 BTC, number of trades: 0
Loki (LOKI): Trade amount: 0.00 BTC, number of trades: 0
Mask (MASK): Trade amount: 0.00 BTC, number of trades: 0
MoX (MOX): Trade amount: 0.00 BTC, number of trades: 0
MobitGlobal (MBGL): Trade amount: 0.00 BTC, number of trades: 0
MonetaryUnit (MUE): Trade amount: 0.00 BTC, number of trades: 0
Neos (NEOS): Trade amount: 0.00 BTC, number of trades: 0
PZDC (PZDC): Trade amount: 0.00 BTC, number of trades: 0
QMCoin (QMCoin): Trade amount: 0.00 BTC, number of trades: 0
Quantum Resistant Ledger (QRL): Trade amount: 0.00 BTC, number of trades: 0
Radium (RADS): Trade amount: 0.00 BTC, number of trades: 0
Ryo (RYO): Trade amount: 0.00 BTC, number of trades: 0
SUB1X (SUB1X): Trade amount: 0.00 BTC, number of trades: 0
Starwels (MAI): Trade amount: 0.00 BTC, number of trades: 0
TurtleCoin (TRTL): Trade amount: 0.00 BTC, number of trades: 0
Zero (ZER): Trade amount: 0.00 BTC, number of trades: 0

Sufficiently traded assets:
01coin (ZOC): Trade amount: 0.0217 BTC, number of trades: 12
Bitcoin Cash (BCH): Trade amount: 44.9139 BTC, number of trades: 72
Bitcoin Clashic (BCHC): Trade amount: 0.01 BTC, number of trades: 1
Byte (GBYTE): Trade amount: 0.11 BTC, number of trades: 2
Counterparty (XCP): Trade amount: 0.025 BTC, number of trades: 1
Dash (DASH): Trade amount: 0.3354 BTC, number of trades: 5
Dash (DASH): Trade amount: 0.3354 BTC, number of trades: 5
Dash (DASH): Trade amount: 0.3354 BTC, number of trades: 5
Decred (DCR): Trade amount: 0.26 BTC, number of trades: 3
Dogecoin (DOGE): Trade amount: 0.065 BTC, number of trades: 4
Ether (ETH): Trade amount: 5.8262 BTC, number of trades: 38
Ether Classic (ETC): Trade amount: 2.0357 BTC, number of trades: 4
Gridcoin (GRC): Trade amount: 0.0717 BTC, number of trades: 4
Litecoin (LTC): Trade amount: 3.0189 BTC, number of trades: 19
Litecoin (LTC): Trade amount: 3.0189 BTC, number of trades: 19
Litecoin (LTC): Trade amount: 3.0189 BTC, number of trades: 19
Monero (XMR): Trade amount: 2642.5725 BTC, number of trades: 3134
Namecoin (NMC): Trade amount: 0.25 BTC, number of trades: 7
PIVX (PIVX): Trade amount: 0.438 BTC, number of trades: 5
Siafund (SF): Trade amount: 5.35 BTC, number of trades: 7
Spectrecoin (XSPEC): Trade amount: 0.811 BTC, number of trades: 8
Unobtanium (UNO): Trade amount: 0.049 BTC, number of trades: 3
Zcash (ZEC): Trade amount: 4.224 BTC, number of trades: 6
Zcoin (XZC): Trade amount: 0.40 BTC, number of trades: 4
ZenCash (ZEN): Trade amount: 0.989 BTC, number of trades: 10

**Comment by aejontargaryen** [comment]
@ManfredKarrer  Thats not us. Dragonglass DRGL was created first.   Later came another DGS-Dragonglass token which is the ICO ether token.  

Completely unrelated to us. 

We are a POW Cryptonote blockchain.

**Comment by aejontargaryen** [comment]
DRGL - https://bitcointalk.org/index.php?topic=2712001.0

DGS- -https://bitcointalk.org/index.php?topic=2934765.0

**Comment by ManfredKarrer** [comment]
@aejontargaryen Ah thanks. Those name squatters are really a pest....

**Comment by ManfredKarrer** [comment]
@m52go Could you add some text that Bisq will not list ICO tokens to the docs. At listing request they need to state that they have not done an ICO. That is a bit beyond that issue here but as the other proposlas for removing ICO tokens got support it would not make sense to just ask if its an ICO if we dont accept it anyway.

**Comment by m52go** [comment]
@ManfredKarrer sure...how detailed do we want to be? Possibilities:

1. Bisq will not list your token if it has taken part in an initial coin offering (ICO).
2. Bisq will not list your token if it has taken part in an initial coin offering (ICO). Given the uncertain regulatory treatment of such tokens, [Bisq stakeholders determined](https://github.com/bisq-network/proposals/issues/58) they are currently too much of a risk for the project.

Let me know if you'd prefer something else.

**Comment by ManfredKarrer** [comment]
@m52go the second is better IMO.

**Comment by ManfredKarrer** [comment]
Close as it is implemented at https://docs.bisq.network/exchange/howto/list-asset.html

**Comment by KeeJef** [comment]
I know you guys have closed this issue but i really think you need to change your wording here. 

The Act of having an ICO is not what should be preventing a coin from appearing on BISQ, For example Ethereum had a large ICO yet BISQ still supports Ethereum. The fact is that the SEC has stated that a coin can be a security and over time it can transition to not being a security anymore, this was the exact situation for Ethereum.

I assume you want to prevent the BISQ team from attempting to predict what decisions the SEC will make when you list a coin, but if this is case you should also remove all coins who raised any money who have not had an explicit ruling from the SEC on their status as a security. For example 
Spectrecoin or Zcash (Which did not have an ICO but distributes a percentage of the block reward to private investors). You could even go further and make the assumption that dev rewards (Taking a percentage of the block reward) could at somepoint be considered legally risky, how far do you want to go to protect yourself?  

The reality of the situation is that the BISQ team will have to make assessments on coins and how "Decentralized" they are, and you should have a framework for doing so, otherwise you will end up unfairly applying your rules across the board.

**Comment by aejontargaryen** [comment]
Very good point, actually. One could even consider premined assets to be in question at a certain point.. considering the steps being taken by the SEC. I think for Bisq this was more of a bitcoin/wikileaks kind of moment where it was better to keep a safe distance until substantial positive impact outweighed any other possible outcomes.  Kinda like “decide you must how to serve them best. If you leave now, help them you could, but you will destroy all for which they have fought and suffered.”
My view is ico's don't usually translate into currency...which is a strength of Bisq, also my opinion. though the future could bring a great many things, most ico's are formed with the intent of a company. Which makes them securities. Its worth noting that the SEC made it a point to say Bitcoin is not a security.

**Comment by ManfredKarrer** [comment]
@KeeJef We are not intending to just comply to the SEC rulings, if they decide that ETH or even BTC is a security we will take the risk to go on. But we DO NOT want to take any risk - even the slightest - for scamcoins doing ICOs with crappy copy pasted whitepapers and bullshit marketing. Most of those scamcoins are associated with ICOs. I don't say that all ICOs are scams but I assuem >95%. That is enough to avoid the work and risk required to deal with it.

**Comment by devinbileck** [comment]
@ManfredKarrer @m52go @blabno Are we planning to add a listing requirement to state that the asset has not done an ICO? If anything, it at least ensures the submitter is aware of the requirement regardless of whether it actually had an ICO. And ideally have them provide link(s) to supporting information detailing the origin of the asset and hopefully proving it was not involved in an ICO. All in an attempt to make our job easier so we don't have to hunt for the information.

**Comment by HarryMacfinned** [comment]
@devinbileck ,
https://docs.bisq.network/exchange/howto/list-asset.html has already 2 lines about ICO tokens not being listed.
You mean adding asking the demanders to prove they didn't use an ICO ?

**Comment by devinbileck** [comment]
@HarryMacfinned Ideally, yes. However, providing solid proof may be difficult, and is still up to the reviewer to verify the claim. But, I am at least suggesting making the submitter acknowledge that they are aware of the requirement by stating it in the description of their PR and declare that the submission process can proceed since the requirements are met.

**Comment by necro-nemesis** [comment]
@ManfredKarrer what's the process to vet coins and address the concern over risk? Clearly there are coins that did acquire funding through ICO and have met that criteria to be listed. For the benefit of Kee and others who arguably demonstrate they fall into that perceived small percentage of valid ICO funded projects; how are they able gain approval in order to proceed and collaborate with the exchange? This appears to be a question of validation.
