### ISSUE TITLE
Proposals for new Bisq tagline

### ISSUE THREAD

**Issue by csacher** [bisq-network/proposals#6]
I'm opening the conversation about the tagline of **Bisq** here on _GitHub_. 
Carrying it over from Slack it’ll allow for time to review and reflect as well as to bring other people into the conversation.

The issue will be the place for brainstorming and proposals. 

Current Bisq tagline: **"The P2P Exchange Network"**

**Comment by csacher** [comment]
@flix1 really liked your approach when you were working on contacting Localbitcoin traders.
**Bisq - Private, safe, decentralized**

@ripcurlx your introduction of Bisq during the growth calls is also a great one
**Bisq - The only real decentralized exchange**

@cbeams please add your ideas and suggestions, no need of perfection at this stage

**Comment by sqrrm** [comment]
I liked something @flix1 said in a call a while back "**it only takes two to trade**".

**Comment by citkane** [comment]
**Crypto trading without the middleman**

**Comment by cbeams** [comment]
Well, the description of our GitHub org (since you emphasized _GitHub_ above, @csacher), is:

> Bisq - A private, safe and decentralized bitcoin exchange network

![image](https://user-images.githubusercontent.com/301810/36970324-7944fb88-2068-11e8-95d6-8157257467ac.png)

On Twitter, we describe Bisq as follows:

> The Bisq network is a safe, private, and decentralized way to buy and sell bitcoin for national currencies and other cryptocurrencies.

![image](https://user-images.githubusercontent.com/301810/36971876-8090f7f2-206d-11e8-99fb-ffe86ed719eb.png)

And what we use in the splash screen of the Bisq desktop client is:

> Bisq - The P2P Exchange Network

We also use it on the homepage of our website (without capitalization):

![image](https://user-images.githubusercontent.com/301810/36970750-e376988a-2069-11e8-8d7c-85f45684956d.png)

----

I think there are a couple things to distinguish here. One is the idea of a _tagline,_ or _slogan,_ and the other is a succinct _description_ of Bisq. Sometimes these things can be the same, but they aren't always.

I think the description used in GitHub and Twitter are very good, and they're tailored to their mediums. I don't think we need one description to rule them all. It can be modified slightly to fit the context as the ones above have.

I think the description used in the app ("The P2P Exchange Network")

I think what we're searching for here, then, is not a description, but indeed a tagline or slogan, the kind of thing that's suitable for a t-shirt or a sticker, and possibly even in the app's splash screen (but I'm not so sure about that).

The only work I've done toward a tagline/slogan for Bisq is what I wrote in the phase zero document [here](https://github.com/bisq-network/docs/blob/master/dao/phase-zero.adoc#why-bisq-exists):

> Where Bitcoin’s motto is "be your own bank," Bisq’s is "**be your own exchange.**"

I think this is powerful. A description should say what something is. A motto/slogan/tagline should emotionally invoke it.

"Be your own exchange" _invokes_ what Bisq stands for: censorship-resistance through decentralized P2P software. It invites the reader / user to embody and actively participate in this ethos.

----

My thoughts on the ideas above:

**Crypto trading without the middleman** sounds cheap to me, and it appeals to baser instincts like bottom-line thinking / penny-pinching, etc. There's nothing wrong with middlemen in principle. They help make trade more efficient. If they didn't, no one would use them. The problem with middlemen in our domain here is that they're subject to attack and capture; they represent chokepoints in the system. I don't want to demonize anybody (Coinbase, et al included). For the most part, these companies (these middlemen) are doing the best they can, and in most cases they are providing a valuable service that people are happy enough with to pay for. The problem is that those same people for the most part have no idea extreme degree of security and privacy risk they're subjecting themselves to by using these services. I'm not sure if we can capture this kind of nuance in a slogan, but I would want in any case to avoid building ourselves up by demonizing anyone else. Bisq should stand on its own merits, everywhere and always. (Michael—I'm sure you didn't mean to "demonize" anyone here. Your suggestion just provided me with an opportunity to talk though some of the principles that motivate me when talking about Bisq, thanks). 

**The only real decentralized crypto-fiat exchange** may be true, currently, but it comes off as weak in the end to me. Don't get me wrong, I say these words myself in certain contexts, but I wouldn't position this as an official description or tagline for the project. It can be wrong tomorrow if another project launches that meets others' definition of "decentralized crypto-fiat exchange", and we'd look pretty silly if we had to change our tagline in response to a new competitor entering the space.

**It only takes two to trade** is interesting to me because it invokes the correct mental model of two individuals choosing to engage with one another. That's what Bisq is about. I don't think this is strong enough to stand on its own as a tagline / slogan for Bisq, but it is, I think, I useful rhetorical tool to have at the ready.

----

A few other thoughts:

I think we need to avoid objectifying or "product-izing" Bisq in our language. Any descriptions we use and any slogans we come up with should be effective at communicating Bisq's nature as a _network_, a _protocol_, and a _set of applications_ that people use to engage in peer-to-peer crypto-fiat transactions with one another.

We're used to thinking about slogans and descriptions for products. Bisq isn't a product in that way, or at the very least, I think we're wise to position it otherwise. At all times, I believe we're wise to look to Bitcoin itself, and now to Lightning as well. Both are powerful brands. Neither are products. Neither has anything like traditional marketing. My greatest aspiration for Bisq is that it grows to inhabit the status of a _global (fiat) foreign exchange layer_ for Bitcoin. Where Lightning is a layer "above" Bitcoin, Bisq is a something like a layer on its side. Bisq provides ingress and egress between the Bitcoin and fiat worlds. Everything we do should be focused on finding ways to communicate that vision to people.

**Comment by ManfredKarrer** [comment]
One of my favorites was: "Bitcoin's native exchange"  - but people seemed to not understand what was meant with native - maybe from my non-native speaker misinterpretation of the word "native" as well ;-)

**Comment by sqrrm** [comment]
I agree with @cbeams almost entirely here. The sound and feel is what makes a slogan powerful. It obviously shouldn't be incorrect, but evoking the right sentiment is its purpose. For that I liked "it only takes two to trade" with its alliterating T's and allusion to p2p nature. It doesn't really evoke the right associations with the connection to "it takes two to tango" though. The line "**Bisq - Be your own exchange**" is alliterating the B in Bisq and it's a command, it feels more powerful and it quite nicely encapsulates the whole concept of p2p trading, including the responsibility of running things yourself.

**Comment by cbeams** [comment]
I have certainly talked about Bisq in these terms, e.g. as Bisq being a "Bitcoin-native exchange". I think it's an excellent way to create the right model in people's head. What you want is a Bitcoin exchange that is based on Bitcoin.

I think Bisq is an early entrant in what will come to be known as something like "Bitcoin applications". 

Web applications use HTTP as an application protocol.
Bitcoin applications use Bitcoin as an application protocol.

Web applications, by nature, are client-server.
Bitcoin applications are, by nature, peer-to-peer.

And so forth. +1 for "bitcoin-native" phrasing in general.

And P.S.: Manfred, your phrasing of "Bitcoin's native exchange" shades the meaning a little differently: It suggests that Bisq is an integral part of the Bitcoin ecosystem, in the same way that Lightning is (one of) Bitcoin's layer two solutions. This is valuable thinking, too. Ultimately, we want people to think of Bisq in both ways:

1. That Bisq is a bitcoin-native exchange, in that Bisq uses Bitcoin as an application layer.
2. That Bisq is integral to the Bitcoin ecosystem.

(2) can only happens if (1) is true, well-executed and widely adopted, so it's best to focus on (1) in our communications now. It will be a measurement of our success there if _other_ people starting talking about Bisq as (2).

**Comment by sqrrm** [comment]
@ManfredKarrer I think the reason "Bitcoin's native exchange" isn't that popular is the feel isn't there. It doesn't flow that nicely and it doesn't evoke the same feelings as "Bisq - Be your own exchange"

**Comment by ManfredKarrer** [comment]
Yes I agree that the second meaning ("That Bisq is integral to the Bitcoin ecosystem.") is a bit too much at the current state. Hopefully people start to see and call it by themselves some day.

 Re: "Bisq - Be your own exchange"
I am not such a fan of the "Be your ...." phrase. Reminds me on slogans from early 2000 internet boom time. 

One good thing with the current "P2P exchange network" might be that is is not so obvious what it means so makes people think (hopefully). But I am also not 100% happy with that, was just the best we could came up in a time when we needed to get the re-branding finished.

"Honey badgers don't care" might be nice as well ;-)

**Comment by blabno** [comment]
Privacy, Money, Bisq

**Comment by sqrrm** [comment]
I like the sentiment of "bitcoin's native exchange" but it doesn't sound 100%.

After reading [Social Architecture](https://www.gitbook.com/book/hintjens/social-architecture), a suggestion by @cbeams which I wholeheartedly agree with, I propose something like:
- "distributed money, distributed exchange"
- "(the) distributed exchange for distributed money"

**Comment by cbeams** [comment]
Per the guidance I just put together in #11, I'm closing this proposal due to (a) inactivity and (b) because we haven't really gotten to a specific proposal that people can give a 👍 or 👎 to. @csacher (or anyone else), please feel free to re-open this and take whatever next steps you see fit, but in the meantime it's better for general proposal hygiene to close those that have gone cold.
