### ISSUE TITLE
Bring BSQ discount on fees from 90% to 80%

### ISSUE THREAD

**Issue by HarryMacfinned** [bisq-network/proposals#94]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

(This proposal is submitted on the DAO. So you can use thumbs up or down here, but it's probably important to vote thru the DAO)

As suggested by @manfredkarrer recently in https://github.com/bisq-network/proposals/issues/92 , I think that the 90% discount when using BSQ to pay trading fees should now be reduced. This discount period did last more than one month now, and probably contributed to the dynamics of the BSQ market.
One month (more in fact) for a 90% discount is a very nice gift/bargain, but I don't think that it's meaningfull to prolongate it indefinitely.
Indeed :
- after 1 month, the BSQ market behaves quite well, and I don't see some reasons why this should change nextly. (95% of altcoins and tokens fall to ~0 in just some days).
- maintaining a 90% discount is concretely not helping the trading volumes on BSQ,
since with such discount very few BSQ is (artificially) sufficient for trading needs.

So 90% is on one hand probably no more necessary and on the contrary helps pushing the BSQ volumes down.

My proposal is that for the next release, the discount using BSQ will go from 90% to 80% (which is still a very strong discount).

One may argue about reducing the discount to 75% or 70% or less. I have absolutely no idea what the "good" number is, but, more important than the precise number, I think that the point is that we should not wait too long to go on the way to reduce the discount.

**Comment by flix1** [comment]
I like the idea of **gradually** over several releases moving from 90% discount to 50%. That way we can measure impact and judge user reaction. It also seems a fair way of compensating developers for work completed. After all the main purpose of BSQ is to transfer value from users to devs.

Users can also not upgrade or skip a release if the consider it an unfair trade-off... it is open source after all.

**Comment by sqrrm** [comment]
Since the BSQ fee is set as a parameter through the DAO it would be best to create two proposals to change a parameter, one to change DEFAULT_MAKER_FEE_BSQ (currently at 0.5 BSQ per BTC traded) and one to change DEFAULT_TAKER_FEE_BSQ (currently at 1.5 BSQ per BTC traded.

Since the value of BSQ/BTC has already changed since launch the current fee in BSQ is even less than it originally was, currently closer to 94% discount. Setting maker fee to 1.6 BSQ and taker fee to 4.8 BSQ would bring it to about 80% discount as suggested.

This is something we'll have to calibrate every month as long as the BSQ/BTC rate is volatile. Might as well start now. I suggest discussing here first to get some consensus on new param settings before publishing a proposal through the client though.

**Comment by sqrrm** [comment]
Another point to make is about the BTC fee. The thinking so far has been that paying the fee in BSQ should yield a discount even when we bring the BSQ fee to 0.4% of trade value. This should be done by also increasing the BTC fee when we increase the BSQ fee. I don't know what the ratio would be in the end, but perhaps a 50-70% discount for using BSQ is reasonable. I suggest we start by bringing it to 80% without changing the fee in BTC this round and next time we increase both BSQ and BTC fees in unison to make sure the discount is still there. Aiming for something like a 1% fee for paying with BTC and 0.4 for paying with BSQ is quite reasonable in the long run.

**Comment by ManfredKarrer** [comment]
@HarryMacfinned Why not make Param proposals with the BTC and BSQ fee changes (maker and taker) instead of the generic proposal?

**Comment by sqrrm** [comment]
@ManfredKarrer I think it's better to discuss it here first before making the proposal in the client to make sure there is some agreement around the proposal first. Since the values need to be agreed on and they can't be changed in the proposals inside the client they would have to be removed and added with the new values if they were created too soon.

**Comment by HarryMacfinned** [comment]
@ManfredKarrer and All
I just wasn't fully aware of the way the discount was technically implemented.
And also feeled perhaps better to have a small discussion in order to know what other contributors think about this discount.
I'm still not fully aware how this discount is implemented. I was absent this week-end, and I'll be absent tomorrow morning. If somebody else make a more precise and technical proposal, it will be ok, since I'll need some time to do that.

**Comment by MwithM** [comment]
I aggree with the general proposal of reducing discount, but the proposal is on the DAO and I don't know exactly what is going to be voted.
I don't feel prepared myself to redact it, but for the voting phase, the proposal needs to be more precise.

**Comment by sqrrm** [comment]
I have created two proposals to change parameter, one to change maker fee to 1.6 BSQ and one to change taker fee to 4.8 BSQ, as calculated in https://github.com/bisq-network/proposals/issues/94#issuecomment-494758515

**Comment by asicminer001** [comment]
debug output show tx. js problem?

**Comment by MwithM** [comment]
What's the difference between these two proposals?

![imagen](https://user-images.githubusercontent.com/50149324/59260197-7aa36b00-8c3b-11e9-9666-f2462e350591.png)

**Comment by sqrrm** [comment]
@MwithM There are two BSQ fee parameters, one for maker fee and one for taker fee. They are set independently so there needs to be one proposal per parameter change. If you look at the details you see under "Option" ("Opción") which parameter is being changed ("BSQ maker fee" or "BSQ taker fee") and that they are being changed to different values.

![image](https://user-images.githubusercontent.com/23560607/59266304-a2003500-8c47-11e9-86a2-682f990d392a.png)

**Comment by MwithM** [comment]
Ok sqrrm thanks for your answer, I didn't open this menu before so that's my confusion. I thought maybe it was something similar to Arnaud's issue but as in the comments for this proposal there were 2 options I also thought I didn't know where to look for the difference.
I'm glad to have asked before submitting my vote, because I haven't checked BSQ quantity and I was trusting the amount displayed on github.

Thanks again.

**Comment by sqrrm** [comment]
@MwithM Indeed, always better to ask questions. In my opinion it's essential to open each request individually since that's where the information that you vote on is displayed. The github issue should have the same numbers and some more explanation but there is no guarantee that the github issue and the data in the request within the client agree. If there is disagreement between the client request and the github issue I would vote against it.

It would probably be good to have some kind of commitment to the github payload within the hash of the compensation request, or param proposal or any other proposal, to make sure that there is no confusion on what's being voted on.

**Comment by sqrrm** [comment]
@HarryMacfinned This proposal has been accepted, fees have been changed. Issue can be closed. We might want to start looking at increasing fees again next month, both BTC and BSQ as planned.

**Comment by HarryMacfinned** [comment]
@sqrrm Yes, I'll close this issue.
Much thanks for converting it in the proper parameter change and proposing it in the DAO.
