### ISSUE TITLE
Gift Cards, PayPal, Google Pay, etc??? 

### ISSUE THREAD

**Issue by angkorfilms** [bisq-network/proposals#96]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

How come these payment methods aren't listed? The Bisq system seems kind of "too strict" by not allowing to use/add other payment methods. There should be a more customizable field where people can input alternative payment methods.

**Comment by reipichu** [comment]
Bisq does not list payment methods that have significant chargeback risk (such as PayPal). I don't know about Google Pay but I would assume it has similar risk. See also discussion here: https://github.com/bisq-network/proposals/issues/93#issuecomment-495247920

**Comment by FKrauss** [comment]
The problem with Google Play and other gift cards is that they have very inconsistent region policies which can be difficult to communicate in the UI. for example: I know that USD google play cards can ONLY be added to US based google accounts. And I am not so sure if French EUR cards can be added only the French google accounts. 

It may make sense to add some of the big ones: Amazon.com and Amazon.de, because they centralise the whole region in most cases and don't have one per country type.

Or maybe we have a better way to handle that on the UI?

Paypal is a distinct prob. It is easy to chargeback

**Comment by HarryMacfinned** [comment]
I had a look at amazon.xx e-giftcards.
My understanding is that giftcards are proper to the country were there are sold. But this is not at all a reason to not implement this payment method. At least to begin with some big country.
Gifcards = 100 Billions $ in the US in 2012 ( https://en.wikipedia.org/wiki/Gift_card )
Also, my understanding is that, once amazon giftcard is downloaded by the recipient, then there is **no more chargeback possible**.
So my feeling is that e-giftcards are well fitted for Bisq, and could have a great potential.
For my part, I would use this payment method to make Bisq buy offers for moneroj market in my country.

I'm strongly in favor of implementing giftcard payment method.
It would be nice if some skilled contributor does it.
If there is no contributor available and willing nextly, I could try to have a look and make a PR by the end of this month (I'll be on vacation tomorrow).

**Comment by FKrauss** [comment]
In the amazon case I agree with you. It is pretty straight forward to have a .com .de .co.uk etc card and a potentially very liquid one.

Why don't you join our next growth call (this Thursday if my memory doesn't fail me) and make a case for it? 

About the coding part, I don't think that is hard because we can just reuse come other payment method classes and swap some fields. But this does require alignment with the rest of the contributors. I'm new contributing but I do know that bisq is avoiding introducing new payment methods until the release of the trading protocol V2 to avoid scams and reduce the attack surface

**Comment by HarryMacfinned** [comment]
I'm sorry, but will be enable to join thursday's growth call because I'll be on vacation tomorrow for ~10 days, without internet.
In order for scam to occur, chargeback must be possible. No chargeback possible = no scam possible.
I'm not a java/javafx dev, so if you @FKrauss are interesting in coding the thing, please just do it.

Apart from coding, if we begin eg with amazon.somecountry, the only point to verify deeper imo is about chargeback versus the first targeted country. As said, my understanding is that once downloaded/activated by the recipient, it's not possible for the sender to have the sended giftcard amount back (would be a bit absurd btw). But, for safety, I would investigate a bit deeper and/or give it a try before coding something.

**Comment by Spigfish** [comment]
Lets find other ways where a charge-back is not an risk. I would like to be able to buy a giftcard for cash that i can buy XMR with

**Comment by FKrauss** [comment]
I was reading up the terms of amazon gift cards and it seems there is no
charge back.

Have you had a different experience?

**Comment by mpolavieja** [comment]
@angkorfilms please review the [proposal submission and review process](https://docs.bisq.network/proposals.html).  For now I am closing this proposal.  If you want, you can open a new one following the guidelines.
