### ISSUE TITLE
Increase trading fee

### ISSUE THREAD

**Issue by deltahandler** [bisq-network/proposals#99]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

The current trading fee in BSQ is too low that the Bisq DAO can be sustainable. 

9248 BSQ have been burned so far by fee payments but 92188 BSQ have been issued to contributors since the DAO has been launched.

<img width="1043" alt="Screen Shot 2019-06-26 at 17 58 29" src="https://user-images.githubusercontent.com/52250737/60195793-0cb29280-983c-11e9-9156-f4f95df98796.png">

Trading volume is very high at the moment and with the 0.4% fee target that would easily outperform the issued BSQ and would make Bisq profitable. If Bisq reaches 20M USD in trade volume 0.4% would be 80000 USD.

The current BSQ fee is 1.6 BSQ for the maker and 4.8 BSQ for the taker.
The BTC maker fee is 0.001 BTC (0.1%) and the BTC taker fee is 0.003 BTC (0.3%).

All those fees are for a 1 BTC trade. BSQ is traded around 1 USD in average. Current BTC price is 12800 USD. The current BSQ maker fee is only 0.0125% and the BSQ taker fee is 0.0375%.

I suggest an increase of the BSQ maker fee to 8 BSQ which would be still only 0.0625% and an increase of the BSQ taker fee to 24 BSQ which would be still only 0.1875%. Both percentage values are then still much lower than the current BTC fees.

To keep a good discount ratio to motivate users to use BSQ for the fee payment I suggest to increase the maker fee in BTC to 0.002 BTC (0.2%) and the BTC taker fee is 0.006 BTC (0.6%).

**Comment by MwithM** [comment]
I think that this is not a good moment to raise fees, at least at the proposed level.
Is true that Bisq trading volumes are spiking, but we don't know if it's due to Bitcoin skyrocketing price or steady Bisq adoption. I'm more inclined to say the first, but both are related anyway.
After the chargebacks and urgency limit for new accounts, Bisq is not offering the best service, there's a lot of new users that want to buy and face limits of 0.1 and we can't even tell them when this will change. I'd be more inclined to raise a little bit now the  BSQ fees, to make it at least the 50% of BTC fees in a couple of voting cycles, and try to head towards the levels of this proposal after protection tools are developed.
Now I think it's time to focus on growing in userbase and try to bootstrap new markets.

**Comment by meapistol** [comment]
I fully support increasing the fees. Bisq needs strong developers and they need to be paid, preferably well. The BTC price can easily change 20% in a day and changes far more than the fee within the trading window. Fees are of no importance to traders, in particular in comparison with the friction that Bisq has. Friction that can in many ways be avoided, e. g. automatic altcoin trading, Monero tx verification, API deployment etc. Friction that can be avoided given more development resources, but not without.

**Comment by mrosseel** [comment]
It is indeed clear that either trading has to go up (even more) or fees have to go up to make it sustainable.
Fees is the only thing we can control so seems the best route, not sure about the exact numbers though. 
Gentle increase might be the safest route.

**Comment by sqrrm** [comment]
This is in line what we have previously discussed. The current BSQ fee is lower than planned due to the rapidly increasing BTC price so by doing the max increase as suggested here we still only get to about half of our planned BSQ fee. Increasing the BTC fee to double our target BSQ fee also seems like a reasonably incentive to use BSQ for trading. I support this proposal.

I think this is a good time to raise the fees. They were artificially low for the first two DAO cycles and we're now getting them closer to the target. This will still only bring them half way there so there is still a discount.

**Comment by initCCG** [comment]
To our group, seems that trading fee discounts are not what is bringing new users to Bisq; the actions of the Big-brothers are...
Therefore, deep discounts seem counterproductive now...

Seems useful to look at competition's fees:
[LBC](https://localbitcoins.com/fees)
[HoblHobl](https://hodlhodl.com/pages/faq)

LBC is now a big-brother exchange, and was never decentralized in any meaningful way.
(Effectively seems 0.5% [1% / 2])

HoblBobl is decentralized only in name, but since it's non-custodial fiat shop, it's probably closest Bisq competitor now. 0.5-0.6%  

As far as we know, Bisq is still by far the most decentralized Bitcoin-fiat exchange.
So, its fees for fiat trades should be at least close to its closest competitor, which is HH.

The market leader in altcoin trading is 
[Binance](https://www.binance.com/en/fee/schedule)
In their own coin, their highest fee rate is 0.075%.
Bisq and Binance are not really direct competitors, but Bisq should try to match BNB's fees rate on BSQ, if it can be done profitably.

If it's not too difficult technically, perhaps given the above, it does makes sense to offer two-tier fee rates - 1 for BTC-fiat trades, another for BTC<>Alts trades.

Perhaps something like this:
BSQ discount: 25%
Altcoin trades Maker:Taker fee ratio: 1:2
Altcoin trades fee in BSQ: 0.075% (Maker) : 0.15% (Taker)
Altcoin trades fee in BTC: 0.1% (Maker) : 0.2% (Taker)

Fiat trades Maker:Taker fee ratio: 1:2
BSQ discount 20%
Fiat trades fee in BSQ: 0.2% (Maker) : 0.4% (Taker)
Fiat trades fee in BTC: 0.25% (Maker) : 0.5% (Taker)

May be sensible to ramp it up to that level in quarterly intervals?

**Comment by deltahandler** [comment]
As > 90% of volume is generated on the altcoin side (XMR) I think that would not work to make Bisq sustainable. Goal should be that revenue from the fees is equal or higher than BSQ spent for contributors. I also think that centralised exchanges like Binance cannot be compared to Bisq. They can only offer such low fees (some have 0) because of further revenue streams they have (front running, business with data, fractional reserve banking, high altcoin listing fees,...) and even they would not do such shady things they can handle much higher volume due their centralised structure. Similar as one should not compare Visa with Bitcoin....    

Beside that the currently high miner fee is for many smaller trades higher than the trade fee. As that cannot be changes anyway soon, I think trying to get new users with a low trade fee is a wrong approach. 

Bisq biggest problem is that there are not enough developers to improve and fix issues (see long list in Github and open proposals). To attract new developers the BSQ payment need to be sustainable and not represent a high risk that the contributor need very long to sell some BSQ to the expected price. To achieve that fee revenue needs to match or outperform the issuance of BSQ.

**Comment by initCCG** [comment]
Let’s assume that Binance and BNB should not even be considered as indirect competitors to Bisq and BSQ.

Neither should XMR volume on Bisq be considered “trading” that is not shady for comparison purposes. The way it is steadily being poured back and forth in such amounts, suggests Bisq is being used as some kind of a Bitcoin mixer, perhaps by the free (aka dark) markets.

If it were actual trading, there would be other altcoins with similar volume...

If not Binance, then the main competition to match becomes the altcoin DEX’s, such as IDEX, Etherdelta, …

[IDEX](https://idex.market/faq)
[Etherdelta](https://www.reddit.com/r/EtherDelta/comments/6hrvwl/how_fees_work/)

We’re back to 0.1 – 0.3% for altcoins. The apparent leader's - IDEX - maker/taker fee ratio is 1:2.
Put a BSQ discount fee on that. 

On the fiat side still match or beat HH, and also have a BSQ discount.

In Bisq, we as makers take more risk and do more work, but 1:3 ratio seems excessive.

Furthermore,  the line of reasoning that:

> As > 90% of volume is generated on the altcoin side (XMR) I think that would not work to make Bisq sustainable. Goal should be that revenue from the fees is equal or higher than BSQ spent for contributors.
> ...
> Bisq biggest problem is that there are not enough developers to improve and fix issues (see long list in Github and open proposals). To attract new developers the BSQ payment need to be sustainable and not represent a high risk that the contributor need very long to sell some BSQ to the expected price. To achieve that fee revenue needs to match or outperform the issuance of BSQ.

suggests the elephant in the room – that the current contributor compensation system is unsustainable.

If the biggest problem with Bisq is not enough devs, and the only way to fix that is to make contributor compensation the top priority, then even Bitcoin itself was unsustainable from the start.

By this line of logic, the more contributors show up, the higher the fees will have to be.

Perhaps, instead of the customers being forced to accept the highest fees among their choices, it’s the contributors that should accept that the Bisq DAO can’t afford to pay us on a FOSS project at the same rate as we get paid in our IRL, LTV centralized economy? 

Our view is that no business can survive by putting competitive compensation for its principles and employees ahead of competitive pricing for its customers.

> Beside that the currently high miner fee is for many smaller trades higher than the trade fee. As that cannot be changes anyway soon, I think trying to get new users with a low trade fee is a wrong approach.

30%+ of the Bisq fee problem is that it doesn’t have Segwit. Is that not going to change soon? 

If off-chain exchanges such as Binance can’t be compared to on-chain exchange Bisq trades in terms of fees, then neither should they be compared in terms of trade size.

The days when small on-chain trades on Bitcoin/Bisq made sense are over. Only LN integration seems likely to make small trades worthwhile on Bisq again, and that for sure cannot happen any time soon.

**Comment by deltahandler** [comment]
> If the biggest problem with Bisq is not enough devs, and the only way to fix that is to make contributor compensation the top priority,...
 
It is not the only way to attract devs but an important part in the mix. Bisq has the potential to attract contributor with its close alignment with Bitcoins philosophy as well with its interesting and challenging technical and conceptually aspects. Money is not always that important for all devs. But they also have to pay bills and not all are early Bitcoin holders to be in the lucky position to not care much about a steady income stream. As it is hard or any project (including very well funded ones) to find good developers in the space we would make our position weaker if the compensation with BSQ is not reliable (e.g. if it is very unclear how much you can sell at which price). 

> ...then even Bitcoin itself was unsustainable from the start.

Not all OS projects need a funding model. Some got lucky enough to got bootstrapped without it, like Bitcoin, Linux and a handful more. The other million of projects which never got that fate you have never heard of. We do not know how many other potential Linux and Bitcoins would have been developed if there would be a more sustainable environment for OS projects. Having a funding model is not a absolutely necessary precondition for an OS project to be successful but it increases the survival chance significantly. 

> By this line of logic, the more contributors show up, the higher the fees will have to be.

More the opposite. If the pressure to finding devs is lower BSQ stake holders can also prefer to decrease the fees. If the majority of BSQ stakeholders are traders that might be actually be a pretty realistic scenario as they have clear incentives for lower fees. But also if the majority of BSQ stakeholders are contributors/developers it is an interesting strategy for them to lower the fees if the revenue is higher than the burned fees to attract more traders by that. 

> Perhaps, instead of the customers being forced to accept the highest fees among their choices, it’s the contributors that should accept that the Bisq DAO can’t afford to pay us on a FOSS project at the same rate as we get paid in our IRL, LTV centralized economy?

As said ,competition is though in that space and I think we should avoid to make our position weaker. Dealing with the more complicate tax situation when earning BSQ instead of Fiat from a company is already an extra burden some developers might not be willing to take. Don't forget that traders will not be happy if not enough devs are around to fix problems and improve the system. If for instance some relatively small open issue like the bad fee estimation service would be fixed all traders can safe a lot of money by lower miner fees. Native segwit support is another similar thing. No devs - no improvements and no the long term no future for Bisq.

> 30%+ of the Bisq fee problem is that it doesn’t have Segwit. Is that not going to change soon?

Yes exactly. Bisq had a BitcoinJ dev who was working on that. Unfortunately he left recently. Without a strong BSQ it will be even harder to find a new one. They have a very good market position as there are more projects out using BitcoinJ than experienced devs. Devs in the Blockchain space are among the best paid in the industry.

> The days when small on-chain trades on Bitcoin/Bisq made sense are over. Only LN integration seems likely to make small trades worthwhile on Bisq again, and that for sure cannot happen any time soon.

Yes, agree that the on-chain trade protocol will not work forever. When that time comes when it becomes too expensive is not clear though. I expect we have 1-2 more years at least. Segwit will move much of the pressure away, so its highly dynamic and hard to predict. 

It is technically not clear how to use Segwit with the current trade protocol (multisig based) or any new variant. Feel free to make a proposal if you know how to do it. But the off-chain trade protocol using BSQ bonds (or a variant with BTC bonds) might be a realistic solution to the miner fee problem as well will increase privacy.

**Comment by deltahandler** [comment]
> In Bisq, we as makers take more risk and do more work, but 1:3 ratio seems excessive.

Feel free to make a proposal to change that ratio. I think its better to discuss those aspects separately (e.g. increase fee and change ratio). Consider that the taker pays 3 times the miner fee, so that makes reasoning about it a bit harder as the miner fee is not depending on trade amount so it hurts small trades more than large trades.

**Comment by initCCG** [comment]
We can discuss all we want and come up with rationalizations, but we know from experience that traders we know don't care about our technical and ideological reasons.

In the wake of the LBC changes, word is that most traders we know in Thailand for example are moving to Paxful of all things. :( They don't even want to deal with learning browser-based  HoblHobl, much less Bisq.

The position we hear is pragmatic: Bisq has no trader reputation system, legacy mining fees, no mobile app, a slow, unusual, complicated, expensive, trading protocol, no liquidity in most fiat markets, and so on.

Most traders or even crypto users just don't care about privacy and decentralization, or even understand why anyone does.
Many if not most trade from their phone most of the time.

Even with the rate volatility, their calculation is simple: 

1. How do the fees compare to other exchanges they use? 
2. Can they use it on their phone through a browser or app, without learning a new protocol?

If the answer is negative, it's unreasonable to expect them to use Bisq over its competition. It's hard to justify that even though Bisq still needs so much dev work, the devs and other contributors already need to collect top fees among exchanges percentage wise, and get paid top compensation.

The fact that even the USD book still doesn't get above 2-4 BTC most days, already suggests that most traders and users worldwide consider it not worth their time even at discounted fees.

We support raising fees immediately to approach or even match the competing DEXs on altcoins and fiat respectively, but think it's unreasonable to exceed them.

However our position as traders remains one of simple business logic: if the revenue and cash flow the market currently provides Bisq DAO is not enough to support the contributor labor costs, the problem is in the high labor and operations costs, and can't be fixed with uncompetitive fees for Bisq's current and potential customers.
Numerous organizations in history have demonstrated that basic fact in every part of every economy.

**Comment by huey735** [comment]
I agree with @initCCG that we should look to our peers when pricing the fees. And maybe we should change the compensation model and instead of singular values, contributors would be asking for a percentage of Bisq's revenue in the previous cycle.

With the current model the amount of BSQ minted is one order of magnitude above the amount burnt so contributors aren't really getting paid. Ideally all the trading fees should be in BSQ and it'd be great if that was a requirement to trade on Bisq from a financial point of view. But unfortunately, BSQ creates too much friction and it's quite unnecessary for one time traders and for the reasons discussed above it isn't even worth acquiring in small amounts.

**Comment by deltahandler** [comment]
> And maybe we should change the compensation model and instead of singular values, contributors would be asking for a percentage of Bisq's revenue in the previous cycle.

So you want to risk to lose the few active contributors Bisq has and make sure it is even harder to find new ones? 

> ...all the trading fees should be in BSQ
Does not work as you can only buy BSQ on Bisq and for that you need to pay a trade fee (chicken and egg problem). Also I think it is not good to force people to use BSQ.

**Comment by MwithM** [comment]
>contributors would be asking for a percentage of Bisq's revenue in the previous cycle.
I've thought about that too and I see two problems in that:
- Making a compensation request in a cycle of high trading volume would be more profitable for devs than creating it in a low volume cycle.
- BSQ monetary mass would be fixed and deflationary, and the DAO could not continue this idea of acting like a central bank creating inflation or deflation considering the circumstances. It's a big change on the originary idea.

> With the current model the amount of BSQ minted is one order of magnitude above the amount burnt so contributors aren't really getting paid. 
You are paid, but in a currency which at the moment is highly inflationary. If price of BSQ increases, the value of devs working at the beggining will be highly compensated. At least I don't expect BSQ to be highly inflationary for ever. BSQ is not and should not be a stable coin so in the future, if Bisq grows, holding should reward those who don't sell.

>Ideally all the trading fees should be in BSQ and it'd be great if that was a requirement to trade on Bisq from a financial point of view. But unfortunately, BSQ creates too much friction and it's quite unnecessary for one time traders and for the reasons discussed above it isn't even worth acquiring in small amounts.
With discounts relative to BTC, if BSQ is useful, the market should choose to make all the trades in BSQ. BSQ is still a very new thing, I know it's not a joke but we should not try to hurry up to make it succeed.

**Comment by sqrrm** [comment]
The client side implementation of the DAO has only been live since April so I think it's too early to draw many conclusions from the current state of BSQ usage and contributions. What can be said is that it's operational, there are trades using BSQ and people are voting and getting their requested BSQ. How this will evolve with time could hardly be clear to anyone but I will lay it out the way I see it.

The DAO is an organization that consists of people and code. There is a governing structure, as written in code, but also very much in our culture. This culture has evolved over the last couple of years and I think the most important document describing this is the zero phase doc at https://docs.bisq.network/dao/phase-zero.html that laid out a plan to get to where we are now. It has worked remarkably well in my opinion.

Since we have now exited phase zero, more or less, we need to figure out where we want to go from here. Bisq is still in a very early phase and it can’t be expected to work at its full potential right now. If every contributor were to expect full compensation at the same level they would get at a traditional company it obviously wouldn’t work, there isn’t enough trade volume to cover those expenses unless the fees were raised to such a level that traders wouldn’t use the platform. That’s not a problem however, as long as Bisq is on the path to reach the state of a fully operational DAO.

There are a few reasons for the the BSQ token to exist, but in this context, and probably the main reason, is to funnel the fees paid by users to those that contribute to the project. Up until the launch of the DAO the contributors had been working for no compensation. For the last few months it has been possible to sell some BSQ received during phase zero but it still hasn’t been possible for early contributors to get the full nominal value for their BSQ. It seems unlikely that contributors that have not received anything for months or even years would suddenly leave now that there actually is a reasonable prospect of getting some kind of compensation.

For these reasons I don’t think there is any rush to change course drastically any time soon. Bisq is on the path set out in the phase zero document. The project is growing, there are more contributors and more traders. The price of BSQ has been quite stable, trade volume has been increasing and the manifestation of the DAO in code has worked well so far. I think we should increase the fees as planned, which is what is proposed in this issue, and continue these discussions elsewhere if there is a strong wish to change direction.

**Comment by deltahandler** [comment]
> Up until the launch of the DAO the contributors had been working for no compensation.

There was a "socially defined" contract/promise that they will get BSQ once the DAO is live, as it happened. So I would not say "had been working for no compensation". It was just not a hard guarantee and it was not convertible to money.

> ...it still hasn’t been possible for early contributors to get the full nominal value for their BSQ

Depends on the amounts. Trading volume has been about 50 000 USD/month or higher and average price is above 1 USD. So decent amounts can already be sold by contributors. I assume most contributors would not sell anyway 100% of their stake....

**Comment by sqrrm** [comment]
> There was a "socially defined" contract/promise that they will get BSQ once the DAO is live, as it happened. So I would not say "had been working for no compensation". It was just not a hard guarantee and it was not convertible to money.
What I meant but "no compensation" was that there has been no monetary reward until in the last couple of months. That it hasn't been possible to live off the spread sheet entries.

Some contributors are now able to sell all their BSQ, but the project as a whole is nowhere near that level. Hopefully we will soon get to a level where the amount of issued BSQ is on par with the amount of burnt, that would be excellent and give a stable basis for the BSQ market in my opinion.

**Comment by BLOCKCHAINSMOKER** [comment]
I am voting NO on this one. I am concerned that we may make BSQ too expensive for customers in the countries that may actually fully adopt Bisq... Like China, Iran Venezuela ect. Also and perhaps most importantly we may dis-incentivize users to purchase BSQ if there is not enough of a benefit to paying with BSQ from BTC. Basically I am worried that the effect that you want to accomplish (more BSQ burnt up) may not actually happen by increasing the BSQ fees. YOU MAY ACTUALLY END UP WITH LESS BSQ PURCHASED!

** Why not propose to have all BTC fees used to purchase BSQ at $1 per BSQ?** In other words WHY IS THERE EVEN A CHOICE OF BSQ OVER BTC? Force users to use BSQ by getting rid of BTC fees. This would be the better proposal. 

I also do not think that raising the fees is a good Idea when the price of BSQ has been relatively stable. BSQ has Stayed in my calculations at a little over a dollar per BSQ or at about 1.15 I think. You can increase the value of BSQ artificially by doing exactly what you propose, maybe, or we can increase the amount of BSQ burned by promoting the use of Bisq and making the application better. 

I agree that we need to keep the developers happy and we need to attract people to the project, however we do not want to make BSQ too expensive too fast and we also do not want to artificially increase the price of BSQ when it is already stable at $1. Why was BSQ set so low?... I think it was to incentivize users to purchase BSQ, to get them addicted to BSQ. If the price is too high then there may not be incentive enough to entice people to buy BSQ over paying with BTC. Where do all of the BTC fees go anyway? Why are they not converted into BSQ? 

Buying BSQ is an extra step that most people will not take if there is not enough incentive. 

Get rid of the BTC fees by converting them directly into BSQ. Is that already planned? 

Any thoughts on this idea?

**Comment by MwithM** [comment]
> Get rid of the BTC fees by converting them directly into BSQ. Is that already planned? Any thoughts on this idea?
It's planned, but is not easy and not a priority. I don't expect to see that near in the future (I guess for the next trading protocol, I'm not sure about this). Offering a slight discount (20-30%) to those  who pay fees in BSQ seems fair at the moment.

**Comment by ManfredKarrer** [comment]
> Get rid of the BTC fees by converting them directly into BSQ

That does not work. How should you buy BSQ when you need  BSQ for the fee? Chicken and egg problem. Also we always stated we do NOT want to force users to use BSQ.

**Comment by huey735** [comment]
@BLOCKCHAINSMOKER @MwithM 

### The ideal scenario
The goal is to have BSQ replace BTC in the trading fees. In my mind, the ideal seems to be to have only the first trade's fees be paid in BTC. At that moment users would acquire a "membership" in BSQ that they could spend for future trades and it'd represent 100% of the trading fee, there'd be no discount. But I don't know how realistic that is. A data analysis needs to be done to figure this out. Every cycle, contributors mint BSQ and the goal is to have a market in place so they can trade it for BTC. If the trading fees in BSQ are too cheap, that market won't ever materialize and contributors will be left holding BSQ that gets devalued with each cycle as more are minted. The trading fees are known in advance so even markets with a weaker currency should be able to price that in in their offers.

### Redistribute the trading fees paid in BTC
It seems difficult to replace BTC as the favorite method to pay trading fees. It's simply more convenient and I imagine most traders don't trade enough to justify them buying BSQ. So in case BTC remains as the favorite method, the ideal would be to aggregate all the fees in one wallet and distribute from that pool to the contributors at the end of each cycle. The problem is how to do that in a decentralized manner where we don't have to trust n persons to hold custody and distribute it. And if we design a method where we can assign that responsibility to those people, how do we reduce the risk of fraud and what would be the requirements to hold such positions? And how easy/difficult would it be for new contributors to join that circle and for old contributors to be pushed out of it?
If we get that worked out I'd prefer having that group redistribute those funds directly to the contributors instead of selling buying BSQ in the market with it.

**Comment by BLOCKCHAINSMOKER** [comment]
> > Get rid of the BTC fees by converting them directly into BSQ
> 
> That does not work. How should you buy BSQ when you need BSQ for the fee? Chicken and egg problem. Also we always stated we do NOT want to force users to use BSQ.

Thanks for the replies.

Here is a way that this could work manually and without complicated formulas.

At the end of each cycle or week we gather all of the BTC fees. We post an order for BSQ at the price of $1USD = 1 BSQ using the collected BTC fees. This creates price support for BSQ with the BTC fees at the price of $1USD for one BSQ.

If the BSQ is sold then the market price prevails until the next order comes forward at the price of 1usd = 1BSQ.

It does not matter if BTC is $24,000 or $3,000. We set the price conversion at the time we post the order to purchase BSQ. 

I hope this is clear because I would appreciate some feedback @ManfredKarrer @MwithM @huey735

**Comment by sqrrm** [comment]
> At the end of each cycle or week we gather all of the BTC fees. We post an order for BSQ at the price of $1USD = 1 BSQ using the collected BTC fees. This creates price support for BSQ with the BTC fees at the price of $1USD for one BSQ.

How do you gather the BTC fees? Who places the BSQ order? That can't be done in a decentralized fashion. I think we need to move away from these centralized methods rather than adding more centralized points in the system.

What you suggest is not that far from a plan that has been discussed though. All fees are paid to one person who sells the BTC for BSQ in the market every month and burns the BSQ, thus distributing the fees to the BSQ holders. This person would have BSQ bond to make sure they don't run away with the BTC but it's still not great to have that kind of centralization in my opinion.

I think there are other ways to handle this but I would like to see the DAO stabilize and see how the fee payments are distributed in reality before embarking on a new big project.

**Comment by huey735** [comment]
@BLOCKCHAINSMOKER , yeah all that @sqrrm  said plus I'm worried about people gaming the market and getting the BTC away from contributors.

**Comment by BLOCKCHAINSMOKER** [comment]
It sounds to me that the only way to make this truly decentralized is to require people to purchase BSQ. I do not see any other solution. The fees can be burned and people can purchase the BSQ at the market rate. 

I know @ManfredKarrer said we dont want to require people to purchase BSQ but I do not see another solution. By the way why not require people to buy BSQ? They come here for privacy, anonymity and most importantly safety. If they need to be required to purchase BSQ then thats the price to pay. 

You are right having the BTC fees go to another wallet is a bad idea and is centralization, even if they are later donated or used to buy and burn BSQ.

It creates incentive for theft and will become another side industry within the BSQ environment as to who gets to have the donated BTC. This seems like a very bad idea and something we should not do concern ourselves with. I think it is better to have one goal and it is to have a truly decentralized exchange. When you are millionaire then you can donate your BSQ, BTC, USD, RUB or other money to whoever you want. 

Having BTC fees go to arbitrators is also centralization and a bad Idea for the Bisq project. 

BTC fees should therefore be done away with and users should be required to purchase BSQ. 

The BSQ used in transactions is burned and we do not have to worry about BTC fees because we do not have any. 

We do not need to worry about discounts because we do not have BTC fees. 

We do not need to worry about donations and what to do with BTC because we do not have any BTC. 

We only need to focus on the project and keeping it afloat by making sure the contributors are paid for their contributions.

**Comment by ManfredKarrer** [comment]
As said, if we only allow BSQ for the fee one cannot buy BSQ without having BSQ....

**Comment by BLOCKCHAINSMOKER** [comment]
@ManfredKarrer Can we turn off the fee's for BSQ purchases?

**Comment by ManfredKarrer** [comment]
No, that is not possible.

**Comment by deltahandler** [comment]
Proposal has been accepted in the DAO voting and can be closed.
